"""Run one share of plan D, the certification that G_13 has no proper 5-colouring, on one machine.

usage (in g13-plan-d/):  python3 share_driver.py K [--jobs 4]      run share K (1 to 14)
                         python3 share_driver.py regen               rewrite the re-split formulas (for verify_plan_D.py)
KISSAT and DRAT_TRIM (environment) name kissat 4.0.4 and drat-trim 2e3b2dc (scripts/worker_setup.sh builds them).

The case formulas are regenerated by the code (enum_cert.py, g13cnf.py) and checked against cases/SHA256SUMS. The cube
files cases/CASE.icnf (cuber2.py, 14 decisions along work/vars_s_lex.txt or work/vars_c0_lex.txt, cover checked) are
committed, so that every machine splits alike. The shares:
  1        Part A (E37_A6, E37_A7, E37_A9, E37_A11, into logs/E37_A.log) and every leaf of E37_B
  2        every leaf of F36 (at first also every leaf of F35, which shares 6 and 8 now run)
  3, 4, 5  the leaves i < 1016 of F34 with i % 3 == K - 3 (at first every i % 3 == K - 3, then i < 3600)
  6        the leaves i < 759 of F35 (added later to shorten share 2; at first every leaf of F35, then i < 1400)
  8        the leaves i >= 1400 of F35 (the leaves of F35, like those of F34, are harder at low i, so this splits the
           first pass about evenly); then the 38 leaves 759 <= i < 1400 of F35 on which kissat reached 120 s in the first
           pass of share 6, re-split at once, from the top down
  7        the 100 leaves i >= 1016 of F34 on which kissat reached 120 s in the first pass of shares 3 to 5 (381
           leaves in all, every one below 2 500): it re-splits them without running them again at 120 s
A leaf on which kissat reached the time limit of its level is not run again at that limit when the driver is
restarted: it goes straight to the re-split.
Pass 1 certifies each leaf with a 120 s kissat limit (certify.py: kissat with a DRAT proof, then drat-trim). Every leaf
of the share left without a VERIFIED line is then re-split as resplit.sh does (CASE_leafI.cnf is exactly the leaf
formula; cuber2.py cuts it with 8 more decisions, cover checked) and its sub-leaves are certified with 1 200 s; a
sub-leaf that still fails is re-split again with 3 600 s, down to four levels. A satisfiable leaf stops the share
(file SAT): for F36, F35 and F34 its model is a proper 5-colouring of G_13 (check_colouring.py checks it); for E37_B it
is an independent set of at least 37 points. At the end the driver writes DONE (every leaf of the share certified,
re-splits included), SAT or FAILED, and it logs its progress in progress.txt. Resumable: rerun it; VERIFIED leaves are
skipped. verify_plan_D.py checks the merged result of all shares.
"""
import argparse
import json
import glob
import hashlib
import os
import re
import shutil
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.setrecursionlimit(100000)
from cuber2 import check_cover  # noqa: E402

GEN = {f"E37_A{c}": f"enum_cert.py {{}} 37 --L 0 --rosette {c}" for c in (6, 7, 9, 11)}
GEN.update({"E37_B": "enum_cert.py {} 37 --norosette",
            "F36": "g13cnf.py {} --big0 36 --cap 36 --dom0 --lex0 25 --vp 1234 --domcap 36",
            "F35": "g13cnf.py {} --big0 35 --cap 35 --dom0 --lex0 25 --vp 1234 --domcap 35",
            "F34": "g13cnf.py {} --rigid34 --lex0 25"})
VARS = {"E37_B": "work/vars_s_lex.txt", "F36": "work/vars_c0_lex.txt", "F35": "work/vars_c0_lex.txt",
        "F34": "work/vars_c0_lex.txt"}
LIMITS = [120, 1200, 3600, 3600, 3600]        # pass 1, then the kissat limit at each re-split level
# plan E (shares 15 on, planE.json): re-splits named CASE..._splitI (a leaf may also have an older CASE..._leafI
# re-split; verify_plan_D.py accepts either), cut by the corrected cuber2.py into up to 256 leaves, 1 200 s each
LIMITS_E = [120] + [1200] * 7
CHUNK = 200
VERIFIED = re.compile(r"(\S+): sha256 ([0-9a-f]{64}); .*drat-trim VERIFIED")
SAT = re.compile(r"(\S+): sha256 [0-9a-f]{64}; kissat SAT ")
TIMEOUT = re.compile(r"(\S+): sha256 ([0-9a-f]{64}); kissat UNKNOWN in ([\d.]+) s")
# share 8, after its first entry: the leaves 759 <= i < 1400 of F35 that timed out at 120 s in the first pass of share 6,
# from the top down (share 6 keeps the leaves below 759)
F35_HARD_8 = [1255, 1023, 1022, 1021, 1019, 1018, 1015, 1013, 1011, 1005, 1004, 1003, 1001, 991, 989, 959, 957, 956, 955, 951, 949, 943, 939, 937, 927, 925, 919, 895, 894, 831, 830, 799, 796, 767, 766, 763, 762, 759]
# share 7: the leaves i >= 1016 of F34 that timed out at 120 s in the first pass of shares 3 to 5; first those with
# i % 3 == 1, which share 4 no longer covers, then the others from the top down (shares 3 and 5 may still run their
# earlier plans, which cover them, from the bottom up)
F34_HARD_7 = [1018, 1021, 1111, 1219, 1231, 1246, 1252, 1255, 1261, 1279, 1405, 1429, 1438, 1444, 1450, 1486, 1492, 1501, 1516, 1525, 1528, 1534, 1639, 1717, 1735, 1783, 1789, 1975, 2026, 2824, 3505, 3507, 3506, 3504, 3185, 3132, 2856, 2828, 2034, 1974, 1935, 1791, 1787, 1781, 1779, 1743, 1739, 1638, 1635, 1634, 1535, 1533, 1532, 1529, 1527, 1526, 1524, 1523, 1521, 1517, 1515, 1500, 1499, 1497, 1494, 1493, 1491, 1485, 1469, 1454, 1451, 1434, 1428, 1406, 1379, 1340, 1263, 1262, 1260, 1257, 1254, 1253, 1251, 1250, 1247, 1244, 1239, 1238, 1229, 1214, 1127, 1109, 1107, 1106, 1103, 1023, 1022, 1020, 1019, 1016]

# the leaves i < 1016 of F34 with i mod 3 = 0 (share 3) and 2 (share 5) on which kissat reached 120 s, not yet re-split
# by those shares at 17:04, from the top down (shares 3 and 5 go up)
F34_HARD_9 = [1011, 1005, 1002, 993, 981, 975, 957, 951, 948, 945, 942, 939, 930, 906, 903, 879, 867, 861, 831, 828, 825, 822, 819, 816, 795, 792, 780, 762, 759, 756, 753, 750, 741, 726, 690, 684, 618, 615, 606, 594, 483, 465, 462, 453, 447, 444, 438, 429, 423, 420, 417, 414, 411, 402, 381, 375, 366, 363, 351, 345, 342, 336, 333, 324, 300, 279, 252, 249, 246, 237, 234, 231, 228, 225, 216, 204, 177, 171, 165, 156, 153, 144, 141, 132]
F34_HARD_10 = [1013, 1004, 1001, 971, 959, 956, 953, 950, 941, 938, 935, 917, 881, 875, 869, 860, 830, 827, 797, 782, 776, 767, 761, 758, 755, 749, 743, 737, 734, 725, 722, 716, 698, 695, 653, 623, 611, 605, 509, 491, 479, 473, 461, 455, 452, 449, 446, 437, 434, 431, 428, 425, 422, 419, 413, 410, 398, 383, 380, 377, 374, 359, 356, 350, 347, 344, 338, 335, 329, 293, 287, 248, 239, 236, 233, 230, 224, 209, 185, 179, 173, 167, 161, 152, 149, 140, 137, 134, 131, 128, 77, 74, 71]

# 27 September, 19:42: every leaf of F34 and F35 still without a complete answer that no share above takes from the
# other end. Share 11: those of F34 below 1016 (the hard leaves of share 4, and one of share 3), from the top down
# (shares 3 and 4 go up); share 12: those of F34 from 1016 up, in the reverse of the order of share 7; share 13:
# those of F35 below 759, from the top down (share 6 goes up); share 14: the others of F35, in the reverse of the
# order of share 8. All re-split at once.
F34_HARD_11 = [1015, 1012, 1009, 1003, 1000, 979, 970, 967, 958, 955, 943, 937, 934, 931, 925, 922, 919, 907, 895, 892, 880, 877, 871, 829, 823, 820, 817, 796, 781, 766, 763, 760, 754, 751, 742, 739, 736, 727, 724, 721, 718, 712, 694, 652, 619, 607, 604, 598, 589, 511, 505, 478, 469, 463, 460, 457, 451, 448, 445, 436, 433, 430, 421, 415, 409, 403, 379, 376, 358, 346, 343, 337, 334, 322, 295, 292, 238, 232, 229, 226, 220, 187, 169, 163, 160, 157, 145, 136, 129]
F34_HARD_12 = [1016, 1019, 1020, 1022, 1023, 1103, 1106, 1107, 1109, 1127, 1214, 1229, 1238, 1239, 1244, 1247, 1250, 1251, 1253, 1254, 1257, 1260, 1262, 1263, 1340, 1379, 1406, 1428, 1434, 1451, 1454, 1469, 1485, 1491, 1493, 1494, 1497, 1499, 1500, 1515, 1517, 1521, 1523, 1524, 1526, 1527, 1529, 1532, 1533, 1535, 1635, 1638, 1739, 1743, 1779, 1781, 1787, 1791, 1935, 1974, 2034, 2828, 2856, 3132, 3185, 3504, 3506, 3507, 3505, 2824, 2026, 1975, 1789, 1783, 1735, 1717, 1639, 1534, 1528, 1525, 1516, 1501, 1492, 1486, 1450, 1444, 1438, 1429, 1405, 1279, 1261, 1255, 1252, 1246, 1231, 1219, 1111, 1021]
F35_HARD_13 = [755, 751, 749, 743, 618, 598, 511, 505, 491, 483, 479, 463, 462, 447, 446, 433, 431, 430, 428, 421, 417, 413, 383, 379, 375, 367, 346, 343, 255, 230, 224, 216, 161, 160, 136]
F35_HARD_14 = [759, 762, 763, 766, 767, 796, 799, 830, 831, 894, 895, 919, 925, 927, 937, 939, 943, 949, 951, 955, 956, 957, 959, 989, 991, 1001, 1003, 1004, 1005, 1011, 1013, 1015]

def path(*p):
    return os.path.join(HERE, *p)


def say(msg):
    line = time.strftime("%H:%M", time.gmtime()) + " " + msg
    print(line, flush=True)
    with open(path("progress.txt"), "a") as fh:
        fh.write(line + "\n")


def finish(flag, msg):
    with open(path(flag), "w") as fh:
        fh.write(msg + "\n")
    say(f"{flag}: {msg}")
    sys.exit(0 if flag == "DONE" else 1)


def sha_file(p):
    return hashlib.sha256(open(p, "rb").read()).hexdigest()


def formulas():
    """regenerate the case formulas that are missing, and check every one against cases/SHA256SUMS"""
    want = dict(reversed(l.split()) for l in open(path("cases", "SHA256SUMS")) if l.strip())
    for name, cmd in GEN.items():
        out = path("cases", name + ".cnf")
        if not (os.path.exists(out) and sha_file(out) == want[name + ".cnf"]):
            args = cmd.format(out).split()
            subprocess.run([sys.executable, path(args[0])] + args[1:], check=True, capture_output=True)
        if sha_file(out) != want[name + ".cnf"]:
            finish("FAILED", f"cases/{name}.cnf differs from cases/SHA256SUMS: the code does not write the formula "
                             "that was split")


def cubes_of(icnf):
    out = []
    for line in open(icnf):
        if line.startswith("a "):
            out.append(line.split()[1:-1])
        elif line.startswith("c closed"):
            out.append(line.split()[2:-1])
    return out


def leaf_text(cnf, cube):
    """the leaf formula exactly as certify.py and resplit.sh write it"""
    head, body = open(cnf).read().split("\n", 1)
    nv, nc = map(int, head.split()[2:4])
    return f"p cnf {nv} {nc + len(cube)}\n" + body + "".join(f"{lit} 0\n" for lit in cube)


def leaf_shas(cnf, cubes, idxs):
    """sha256 of the leaf formulas, sharing the hash of the common part as verify_plan_D.py does"""
    head, body = open(cnf, "rb").read().split(b"\n", 1)
    nv, nc = map(int, head.split()[2:4])
    pre, out = {}, {}
    for i in idxs:
        cube = cubes[i]
        if len(cube) not in pre:
            pre[len(cube)] = hashlib.sha256(f"p cnf {nv} {nc + len(cube)}\n".encode() + body)
        h = pre[len(cube)].copy()
        h.update("".join(f"{lit} 0\n" for lit in cube).encode())
        out[i] = h.hexdigest()
    return out


def log_state(log):
    ok, sat = set(), set()
    for line in (open(log) if os.path.exists(log) else []):
        m = VERIFIED.match(line)
        if m:
            ok.add(m.groups())
        m = SAT.match(line)
        if m:
            sat.add(m.group(1))
    return ok, sat


def found_sat(case, name):
    model = path("proofs", name + ".model")
    shutil.copy(model, path("SAT_" + name + ".model"))
    if case.startswith("F"):
        r = subprocess.run([sys.executable, path("check_colouring.py"), model], capture_output=True, text=True)
        last = (r.stdout.strip().splitlines() or ["no output"])[-1]
        finish("SAT", f"leaf {name} is satisfiable: {last} (check_colouring.py exit {r.returncode}); "
                      f"model in SAT_{name}.model")
    finish("SAT", f"leaf {name} is satisfiable: an independent set of at least 37 points; model in SAT_{name}.model")


def timed_out(log, limit):
    """(name, sha256) of the leaves on which kissat reached this time limit (a run stopped early is not counted)"""
    out = set()
    for line in (open(log) if os.path.exists(log) else []):
        m = TIMEOUT.match(line)
        if m and float(m.group(3)) >= 0.95 * limit:
            out.add((m.group(1), m.group(2)))
    return out


def certify(case, cnf, idxs, limit, jobs):
    """certify the leaves idxs of cnf's cube file with the kissat limit, in chunks; stop on a satisfiable leaf.
    A leaf that already reached this limit is left for resolve() to re-split."""
    stem = cnf[:-4]
    tag = os.path.basename(stem)
    shas = leaf_shas(cnf, cubes_of(stem + ".icnf"), idxs)
    skip = timed_out(stem + ".certlog", limit)
    idxs = [i for i in idxs if (f"{tag}_leaf{i}", shas[i]) not in skip]
    for k in range(0, len(idxs), CHUNK):
        chunk = idxs[k:k + CHUNK]
        subprocess.run([sys.executable, path("certify.py"), "--log", stem + ".certlog", "--jobs", str(jobs),
                        "--time", str(limit), "--base", cnf, "--cubes", stem + ".icnf",
                        "--only", ",".join(map(str, chunk))], check=True)
        ok, sat = log_state(stem + ".certlog")
        for i in chunk:
            if f"{tag}_leaf{i}" in sat:
                found_sat(case, f"{tag}_leaf{i}")
        say(f"{tag}: {min(k + CHUNK, len(idxs))} of {len(idxs)} leaves run (limit {limit} s)")


def resolve(case, cnf, idxs, level, jobs, style="leaf", limits=LIMITS):
    """make every leaf idxs of cnf certified: VERIFIED, or re-split (CNF_{style}I) with all its sub-leaves resolved"""
    stem = cnf[:-4]
    tag = os.path.basename(stem)
    cubes = cubes_of(stem + ".icnf")
    shas = leaf_shas(cnf, cubes, idxs)
    ok, sat = log_state(stem + ".certlog")
    todo = [i for i in idxs if (f"{tag}_leaf{i}", shas[i]) not in ok]
    if level == 0:
        say(f"{tag}: {len(idxs) - len(todo)} of {len(idxs)} leaves VERIFIED, {len(todo)} to re-split")
    for i in todo:
        if f"{tag}_leaf{i}" in sat:
            found_sat(case, f"{tag}_leaf{i}")
        if level + 1 >= len(limits):
            finish("FAILED", f"{tag}_leaf{i} is not certified after {level} re-splits")
        sub = f"{stem}_{style}{i}.cnf"
        text = leaf_text(cnf, cubes[i])
        assert hashlib.sha256(text.encode()).hexdigest() == shas[i]
        if not (os.path.exists(sub) and sha_file(sub) == shas[i]):
            with open(sub + ".tmp", "w") as fh:
                fh.write(text)
            os.replace(sub + ".tmp", sub)
        sub_icnf = sub[:-4] + ".icnf"
        if not os.path.exists(sub_icnf):
            vars_ = open(path(VARS[case])).read().strip()
            subprocess.run([sys.executable, path("cuber2.py"), sub, "8", sub_icnf, "--vars", vars_], check=True)
        n = len(cubes_of(sub_icnf))
        say(f"{tag}_leaf{i}: re-split as {os.path.basename(sub[:-4])} into {n} leaves (level {level + 1}, "
            f"limit {limits[level + 1]} s)")
        certify(case, sub, list(range(n)), limits[level + 1], jobs)
        resolve(case, sub, list(range(n)), level + 1, jobs, style, limits)


def regen():
    """rewrite every re-split formula CASE_leafI...cnf or CASE_splitI...cnf from its parent (they are not committed:
    too large)"""
    subs = sorted(set(glob.glob(path("cases", "*_leaf*.icnf")) + glob.glob(path("cases", "*_split*.icnf"))), key=len)
    for icnf in subs:
        sub = icnf[:-5] + ".cnf"
        m = re.fullmatch(r"(.*)_(?:leaf|split)(\d+)", icnf[:-5])
        parent, i = m.group(1) + ".cnf", int(m.group(2))
        text = leaf_text(parent, cubes_of(parent[:-4] + ".icnf")[i])
        with open(sub, "w") as fh:
            fh.write(text)
    print(f"{len(subs)} re-split formulas written")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("share")
    ap.add_argument("--jobs", type=int, default=os.cpu_count() or 4)
    a = ap.parse_args()
    formulas()
    if a.share == "regen":
        regen()
        return
    k = int(a.share)
    plan_e = {int(s): v for s, v in json.load(open(path("planE.json"))).items()} if os.path.exists(path("planE.json")) else {}
    for f in ("DONE", "SAT", "FAILED"):
        if os.path.exists(path(f)):
            os.remove(path(f))
    os.makedirs(path("logs"), exist_ok=True)
    say(f"share {k}: start, {a.jobs} jobs; kissat {os.environ.get('KISSAT')}, drat-trim {os.environ.get('DRAT_TRIM')}")
    if k == 1:
        names = [f"E37_A{c}" for c in (6, 7, 9, 11)]
        ok, _ = log_state(path("logs", "E37_A.log"))
        if not all((n + ".cnf", sha_file(path("cases", n + ".cnf"))) in ok for n in names):
            subprocess.run([sys.executable, path("certify.py"), "--log", path("logs", "E37_A.log"), "--jobs",
                            str(a.jobs), "--time", "1200"] + [path("cases", n + ".cnf") for n in names], check=True)
        ok, _ = log_state(path("logs", "E37_A.log"))
        if not all((n + ".cnf", sha_file(path("cases", n + ".cnf"))) in ok for n in names):
            finish("FAILED", "Part A (E37_A) is not VERIFIED: see logs/E37_A.log")
        say("Part A: the four rosette formulas VERIFIED")
    # (case, (m, r, lo, hi)): the leaves i with i % m == r and lo <= i < hi; None: every leaf; a list: those
    # leaves, known to time out at 120 s, re-split at once
    if k in plan_e:                                # plan E: each listed leaf re-split at once, the new way
        for case, idxs in plan_e[k]:
            cnf = path("cases", case + ".cnf")
            cubes = cubes_of(path("cases", case + ".icnf"))
            if not check_cover([tuple(map(int, c)) for c in cubes]):
                finish("FAILED", f"cases/{case}.icnf is not a cover")
            resolve(case, cnf, idxs, 0, a.jobs, style="split", limits=LIMITS_E)
            say(f"{case}: every leaf of the share certified ({len(idxs)} leaves, re-splits included)")
        finish("DONE", f"share {k}: every leaf certified")
    plan = {1: [("E37_B", None)], 2: [("F36", None)], 3: [("F34", (3, 0, 0, 1016))],
            4: [("F34", (3, 1, 0, 1016))], 5: [("F34", (3, 2, 0, 1016))], 6: [("F35", (1, 0, 0, 759))],
            7: [("F34", F34_HARD_7)], 8: [("F35", (1, 0, 1400, 10 ** 9)), ("F35", F35_HARD_8)],
            9: [("F34", F34_HARD_9)], 10: [("F34", F34_HARD_10)], 11: [("F34", F34_HARD_11)],
            12: [("F34", F34_HARD_12)], 13: [("F35", F35_HARD_13)], 14: [("F35", F35_HARD_14)]}[k]
    for case, sel in plan:
        cnf = path("cases", case + ".cnf")
        cubes = cubes_of(path("cases", case + ".icnf"))
        if not check_cover([tuple(map(int, c)) for c in cubes]):
            finish("FAILED", f"cases/{case}.icnf is not a cover")
        if isinstance(sel, list):
            idxs = sel
        else:
            idxs = [i for i in range(len(cubes)) if sel is None or (i % sel[0] == sel[1] and sel[2] <= i < sel[3])]
            certify(case, cnf, idxs, LIMITS[0], a.jobs)
        resolve(case, cnf, idxs, 0, a.jobs)
        say(f"{case}: every leaf of the share certified ({len(idxs)} leaves, re-splits included)")
    finish("DONE", f"share {k}: every leaf certified")


if __name__ == "__main__":
    main()
