"""Colour unit-distance graphs in Q(sqrt-3, sqrt-11, sqrt-247) by reduction at the place above 11.

Every unit vector reduces to the 12-element norm-one group N1 of F_121, and every point to a residue
in F_121 (relative to its coset of O_v), so a 5-colouring of the finite plane Cay(F_121, N1) colours
the whole graph.  Checks unit vectors and every edge in exact arithmetic, at both places above 11.

usage: python3 reduce11.py <file.json> ...   (fields generated by 3, 11, 247 or a subset)"""
import sys, os, json, time
from fractions import Fraction as Fr
import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from hn.field import Field
from hn.geometry import Point
from hn.adelic import reduce11, finite_plane_11_colouring
t0 = time.time()
col, N1 = finite_plane_11_colouring()
N1s = set(N1)
key = lambda p: (round(p.fx, 9), round(p.fy, 9))
for path in sys.argv[1:]:
    d = json.load(open(path))
    gens = tuple(d["field_generators"])
    F = Field(gens)
    mk = lambda xy: Point(F.element([Fr(a, b) for a, b in xy[0]]), F.element([Fr(a, b) for a, b in xy[1]]))
    P = [mk(xy) for xy in d.get("points", [])]
    units = [mk(xy) for xy in d.get("units", [])]
    # edges: exact unit distance, found through float hashing on the unit directions of the file
    # (or all pairs within the graph's own directions)
    if not units:
        from hn.graph import build_graph
        g = build_graph(P)
        E = list(g.edges())
        Ud = {}
        for a, b in E:
            for w in (P[b] - P[a], P[a] - P[b]): Ud.setdefault(key(w), w)
        units = list(Ud.values())
    else:
        vk = {key(p): i for i, p in enumerate(P)}
        E = set()
        for i, p in enumerate(P):
            for u in units:
                j = vk.get((round(p.fx + u.fx, 9), round(p.fy + u.fy, 9)))
                if j is not None and j != i:
                    E.add((min(i, j), max(i, j)))
        E = sorted(E)
    for place in (1, -1):
        ru = {reduce11(u, place) for u in units}
        assert ru <= N1s, (path, "a unit vector does not reduce into N1")
        r = [reduce11(p, place) for p in P]
        bad = 0
        for i, j in E:
            dx = ((r[j][0] - r[i][0]) % 11, (r[j][1] - r[i][1]) % 11)
            assert dx in N1s, (path, "an edge does not reduce to a step in N1")
            bad += col[r[i]] == col[r[j]]
        assert bad == 0
    print(f"{os.path.basename(path)}: {len(P)} points, {len(E)} edges, {len(units)} unit vectors -> "
          f"{len(ru)} residues in N1; 0 monochromatic edges at both places above 11   [{time.time()-t0:.0f}s]", flush=True)
