"""Unit vectors generated by named rotations, in any multiquadratic field, for the gates and growth.

A rotation is cos + i sin with cos rational and sin = c * sqrt(r): the complex number
(a + b sqrt-D)/n.  Units: omega^k * prod_j R_j^{e_j} * (1, 0) for exponents |e_j| <= range_j.

Named rotations (denominators in brackets):
  sigma  (5 + sqrt-11)/6        [3]     Moser
  lambda (49 + 3 sqrt-11)/50    [5^2]   Exoo-Ismailescu
  rho7   (1 + 4 sqrt-3)/7       [7]
  kappa  (-11 + 5 sqrt-3)/14    [7]     omega * rho7
  tau    (119 + 3 sqrt-247)/128 [2^6]   the sqrt247 spindle
  mu2    (-3 + sqrt-7)/4        [2^2]   the basic 2-adic rotation of Q(sqrt-7)
  rho11  (-3 + 4 sqrt-7)/11     [11]
  dg4    (31 + 3 sqrt-7)/32     [2^5]   de Grey's 4e rotation
  dg2    (7 + sqrt-15)/8        [2^3]   de Grey's 2e rotation

usage: python3 rotwords.py <gens e.g. 3,7,11> <spec e.g. sigma:1,lambda:1,mu2:1> <out.json>"""
import sys, json, os, itertools
from fractions import Fraction as Fr
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from hn.field import Field
from hn.geometry import Point, Rotation
ROT = {"sigma": (Fr(5, 6), 11, Fr(1, 6)), "lambda": (Fr(49, 50), 11, Fr(3, 50)),
       "rho7": (Fr(1, 7), 3, Fr(4, 7)), "kappa": (Fr(-11, 14), 3, Fr(5, 14)),
       "tau": (Fr(119, 128), 247, Fr(3, 128)), "mu2": (Fr(-3, 4), 7, Fr(1, 4)),
       "rho11": (Fr(-3, 11), 7, Fr(4, 11)), "dg4": (Fr(31, 32), 7, Fr(3, 32)),
       "dg2": (Fr(7, 8), 15, Fr(1, 8))}


def units(gens, spec):
    F = Field(tuple(gens))
    def rot(name, sign=1):
        c, r, s = ROT[name]
        return Rotation(F.rational(c), F.sqrt(r) * F.rational(sign * s))
    om = Rotation(F.rational(Fr(1, 2)), F.sqrt(3) * F.rational(Fr(1, 2)))
    names = [n for n, _ in spec]
    U = {}
    for exps in itertools.product(*[range(-e, e + 1) for _, e in spec]):
        p = Point(F.one(), F.rational(0))
        for name, e in zip(names, exps):
            R = rot(name, 1 if e > 0 else -1)
            for _ in range(abs(e)):
                p = R(p)
        for _ in range(6):
            U.setdefault(p, p)
            p = om(p)
    return F, list(U)


if __name__ == "__main__":
    gens = [int(x) for x in sys.argv[1].split(",")]
    spec = [(t.split(":")[0], int(t.split(":")[1])) for t in sys.argv[2].split(",") if t]
    F, U = units(gens, spec)
    enc = lambda u: [[[x.numerator, x.denominator] for x in u.x.c], [[x.numerator, x.denominator] for x in u.y.c]]
    json.dump({"field_generators": gens, "units": [enc(u) for u in U],
               "points": [enc(Point(F.rational(0), F.rational(0)))], "A": 0, "B": 0,
               "note": "rotation words " + sys.argv[2]}, open(sys.argv[3], "w"))
    print(f"{len(U)} unit vectors written to {sys.argv[3]}")
