"""Six circles with LISTS: the strongest local certificate available for rung one.

If the hexagon about h is 2-coloured then its two inscribed sqrt3-triangles are
monochromatic, say T in gamma and T' in delta.  That excludes gamma from every
point a unit from T and delta from every point a unit from T', so the union of
the SIX unit circles about the hexagon's vertices carries a list-colouring
problem rather than a plain one:

    a point a unit from T only        -> four colours
    a point a unit from T' only       -> four colours
    a point a unit from both          -> THREE colours

and h itself lies on all six circles, so its list has three.  If that list
problem is infeasible, the hexagon can never be 2-coloured, which is rung one
from geometry alone -- no ambient graph, no solver on ten thousand vertices.

Plain chromatic numbers were not enough: three circles about the sqrt3-triangle
give chi = 3 (2 on generic orbits, 3 on the two orbits carrying a unit triangle,
stable to 3002 vertices), against the 5 a plain certificate would need.  Lists
are the sharper instrument, because they remember WHICH colour each region lost.

Generated by breadth-first search along the six circles, seeded both at h and at
the unit triangles that put odd cycles into the orbit.
"""
import sys, time, math
from collections import deque
from pysat.solvers import Solver

t0 = time.time()
R3 = math.sqrt(3.0)
HEX = [(math.cos(math.radians(60 * k)), math.sin(math.radians(60 * k)))
       for k in range(6)]
T_IDX = [0, 2, 4]          # the sqrt3-triangle at 0, 120, 240 degrees
TP_IDX = [1, 3, 5]         # the other one

def circle_points_at_unit(p, k):
    cx, cy = HEX[k]
    dx, dy = p[0] - cx, p[1] - cy
    d = math.hypot(dx, dy)
    if d < 1e-12 or d > 2.0 - 1e-12: return []
    a = d / 2.0
    h = math.sqrt(max(0.0, 1.0 - a * a))
    mx, my = cx + dx * a / d, cy + dy * a / d
    ux, uy = -dy / d, dx / d
    return [(mx + h * ux, my + h * uy), (mx - h * ux, my - h * uy)]

def lists_of(p):
    onT = any(abs(math.hypot(p[0]-HEX[k][0], p[1]-HEX[k][1]) - 1.0) < 1e-7
              for k in T_IDX)
    onTp = any(abs(math.hypot(p[0]-HEX[k][0], p[1]-HEX[k][1]) - 1.0) < 1e-7
               for k in TP_IDX)
    bad = set()
    if onT: bad.add(0)          # gamma
    if onTp: bad.add(1)         # delta
    return [c for c in range(5) if c not in bad]

def build(seeds, cap):
    seen = {}; order = []; q = deque()
    for s in seeds:
        k = (round(s[0], 7), round(s[1], 7))
        if k not in seen:
            seen[k] = s; order.append(s); q.append(s)
    while q and len(order) < cap:
        p = q.popleft()
        for k in range(6):
            for r in circle_points_at_unit(p, k):
                key = (round(r[0], 7), round(r[1], 7))
                if key not in seen:
                    seen[key] = r; order.append(r); q.append(r)
    pts = list(seen.values()); E = []
    for i in range(len(pts)):
        for j in range(i + 1, len(pts)):
            if abs(math.hypot(pts[i][0]-pts[j][0], pts[i][1]-pts[j][1]) - 1.0) < 1e-7:
                E.append((i, j))
    return pts, E

def list_colourable(pts, E):
    K = 5
    X = lambda v, c: 1 + v * K + c
    cnf = []
    sizes = {}
    for v, p in enumerate(pts):
        L = lists_of(p)
        sizes[len(L)] = sizes.get(len(L), 0) + 1
        cnf.append([X(v, c) for c in L])
        for c in range(K):
            if c not in L: cnf.append([-X(v, c)])
    for a, b in E:
        for c in range(K):
            cnf.append([-X(a, c), -X(b, c)])
    s = Solver(name="cd19", bootstrap_with=cnf)
    ok = s.solve(); s.delete()
    return ok, sizes

# seeds: h, plus the unit triangles that sit on three of the circles
seeds = [(0.0, 0.0)]
found = 0
for k in range(6):
    for a in [2 * math.pi * n / 720 for n in range(720)]:
        u = (HEX[k][0] + math.cos(a), HEX[k][1] + math.sin(a))
        for k2 in range(6):
            if k2 == k: continue
            for v in circle_points_at_unit(u, k2):
                mx, my = (u[0]+v[0])/2, (u[1]+v[1])/2
                dx, dy = v[0]-u[0], v[1]-u[1]
                d = math.hypot(dx, dy)
                if d < 1e-9: continue
                hh = math.sqrt(max(0.0, 1.0 - (d/2)**2))
                for s in (1, -1):
                    w = (mx + s*hh*(-dy/d), my + s*hh*(dx/d))
                    for k3 in range(6):
                        if abs(math.hypot(w[0]-HEX[k3][0], w[1]-HEX[k3][1]) - 1.0) < 1e-6:
                            seeds += [u, v, w]; found += 1
print(f"  {found} triangle seeds found on the six circles   "
      f"[{time.time()-t0:.0f}s]", flush=True)
for cap in (60, 200, 600, 1500, 3000):
    pts, E = build(seeds, cap)
    ok, sizes = list_colourable(pts, E)
    print(f"  cap={cap:<5d} n={len(pts):<5d} edges={len(E):<6d} list sizes "
          f"{dict(sorted(sizes.items()))}  list-colourable: {ok}   "
          f"[{time.time()-t0:.0f}s]", flush=True)
    if not ok:
        print("  *** THE HEXAGON CANNOT BE TWO-COLOURED: RUNG ONE ***", flush=True)
        break
