#!/usr/bin/env python3
"""
Independent rigorous check of the three-point certificates data/threepoint/*.npz
(research/hadwiger-nelson, notes/local_colourings.md section 14).

This file does NOT import scripts/threepoint.py or scripts/threepoint_verify.py.  The programme is rebuilt
here from the definitions, over full n x n matrices (n = q^2), and the certificate is used only as a source
of numbers: dual multipliers, plus the labelling needed to know what each number multiplies.

------------------------------------------------------------------------------------------------ the plane
P = F_q^2 (q prime), Q(x, y) = x^2 + n0 y^2 mod q, and a ~ b iff Q(b - a) = 1.
  std  : n0 = 1, the form x^2 + y^2.
  inert: -n0 a non-square mod q, so Q(x, y) = N(x + y sqrt(-n0)) is the norm form of F_{q^2} = F_q(sqrt(-n0))
         and the graph is G_q = Cay(F_{q^2}, N_1).  Every choice of the non-square gives an isometric form,
         so the same graph.  n0 is read from the certificate; its property is CHECKED here.
O(Q) is enumerated by brute force: every 2x2 matrix over F_q that preserves Q.

------------------------------------------------------------------------------------------ the relaxation
Let S be an independent set, gamma a uniformly random isometry x -> R x + t (R in O(Q), t in P), S' = gamma S,
v the indicator vector of S', and x0 = v(0).  Put, for ALL ordered pairs (a, b) in P x P,
        z(a, b) = Pr[a in S' and b in S' | 0 in S'] = (n/|S|) E[x0 v_a v_b].
Facts (proved in the report):
  (O) z is constant on the orbits of ordered pairs under the group generated by O(Q) (acting diagonally)
      and the 6 relabellings of the triangle (0, a, b); z in [0, 1]; z(0, 0) = 1; z = 0 on every orbit
      having a unit side.  g(w) := z(0, w) = z(w, w) = z(w, 0) (the degenerate orbits are the circles).
  (F) |S| = sum_w z(0, w).
  (M1) [z(a, b)]_{a, b in P} = (n/|S|) E[x0 v v^T] is PSD.
  (M0) [z(0, b - a) - z(a, b)]_{a, b != 0} = (n/|S|) E[(1 - x0) v v^T] (restricted to a, b != 0) is PSD.
  (L) for every non-degenerate orbit t, representative (a, b), sides s1, s2, s3 = a, b, b - a:
      z(0, s_i) - z_t >= 0 and 1 - z(0, s_i) - z(0, s_j) + z_t >= 0.
  (D) Delsarte: sum_w z(0, w) cos(2 pi xi.w / q) >= 0 for every xi in F_q^2.
Weak duality: for PSD W1, W0 and lam, mu >= 0,
     L(z) = sum_w z(0,w) + <M1(z), W1> + <M0(z), W0> + sum lam (L) + sum mu (D)  >=  |S|,
and L(z) = c_0 + sum_t c_t z_t with z_t in [0, 1] on the free orbits (z fixed on the others), so
     |S| <= c_0 + sum_t max(0, c_t).

------------------------------------------------------------------------------------------ the certificate
Assumptions about the file format (each one is checked as far as possible; a wrong assumption can only make
the check FAIL or weaken the bound, never produce a false bound, because soundness uses only W1, W0 >= 0,
lam, mu >= 0 and the constraints rebuilt here):
  A1. meta (JSON) holds q, kind, n0, N (= number of unit vectors), m, sig (a rotation of order N), tau (a
      reflection), reps (one point per sig-orbit of P minus 0), partner, shift, options, K0.  Only
      certificates with all options false and K0 = null are handled (all eight stored ones).
  A2. z = [nv multipliers of "variable >= 0" (all zero)] + [6 nz multipliers of (L)] +
          [nch multipliers of (D)] + [svec of each dual psd block],
      nz = number of free non-degenerate orbits, nv = nz + number of free circles, nch = number of distinct
      Delsarte rows (below).  The total length is checked.
  A3. The (L) multipliers come 6 per orbit, orbits ordered by their smallest pair index a*n + b
      (point index = x*q + y); for the representative (a, b) = that smallest pair, the six are
      z <= g(a), z <= g(b), z <= g(b - a), then 1-g(a)-g(b)+z, 1-g(a)-g(b-a)+z, 1-g(b)-g(b-a)+z >= 0.
  A4. The (D) multipliers are indexed by the distinct rows of the character table, in order of first
      appearance over xi = 1 .. n-1, (xi_x, xi_y) = divmod(xi, q), rows compared after rounding to 6
      decimals (we replicate this enumeration only to learn WHICH xi each multiplier belongs to).
  A5. Dual blocks, in order: M1 at k = 0 .. N/2, then M0 at k = 0 .. N/2; svec = upper triangle column by
      column, off-diagonal entries times sqrt 2.  Block (M, k) pairs with the compression V_k^H M V_k, whose
      columns are, in order: [delta_0 for (M1, k=0)], then for each orbit a (in order, pairs once):
      u_a if a is unpaired, (u_a + u_b)/sqrt2 and i(u_a - u_b)/sqrt2 for a pair (a, b), where
      u_a(sig^j reps[a]) = exp(2 pi i k (j - shift[a]) / N) / sqrt N.
      The dual matrix on the full space is then  W = sum_k Re(V_k Y_k V_k^H) = sum_k A Y A^T + B Y B^T
      (V = A + iB), which is PSD whatever A, B are, as soon as every Y_k is PSD.

------------------------------------------------------------------------------------------ rigour
 * Y_k: clipped to its nonnegative eigenvalues, shifted by eps * lambda_max, rounded to integers / 2^E, and
   proved positive definite EXACTLY (Sylvester's criterion by fraction-free Bareiss elimination, Python ints).
 * A, B: numpy cosines/sines rounded to the grid 2^-52.  They need no accuracy guarantee: W is PSD for any
   A, B; their accuracy only decides whether the residuals cancel.
 * W's class sums are computed EXACTLY (python-flint fmpz_mat products of the integer matrices, Python ints).
 * Linear multipliers: floats taken as exact rationals (Fraction), negative ones replaced by 0.
 * Delsarte coefficients: cos(2 pi j / q) enclosed with mpmath.iv (128 bits), summed as Fraction intervals.
 * The final bound is an exact rational upper bound.
Trusted: numpy integer/bool indexing, python-flint (FLINT) integer matrix multiplication, mpmath interval
cos, Python's Fraction/int.

Results (26 Sep 2026; exact rational upper bounds, rounded up to 1e-6; all eight SHA256SUMS OK):
  inert13  42.632032  (alpha <= 42 < 169/4)     inert29 163.248262     std37 259.894435
  inert37 263.631529  std41 327.676352  inert41 300.724005  std43 347.788699  std47 371.414129
Tests: tests/test_threepoint_indep.py (the true z of actual independent sets satisfies every rebuilt
constraint; misreading a certificate's labelling destroys its bound; the stored certificates' bounds). The log
of a run on all eight certificates is certificates/threepoint_indep_checks.txt.

usage: nice -n 19 python3 scripts/threepoint_verify_indep.py path/to/cert.npz [--float-only] [--m1-only]
       [--chunk ROWS]
"""
import sys, os, json, time, math, argparse, itertools
from fractions import Fraction
import numpy as np

T0 = time.time()


def log(*a):
    print(f"[{time.time() - T0:7.1f}s]", *a, flush=True)


# ------------------------------------------------------------------------------------------ arithmetic
def is_prime(q):
    return q > 1 and all(q % d for d in range(2, int(q ** 0.5) + 1))


def is_square_mod(a, q):
    a %= q
    return a == 0 or pow(a, (q - 1) // 2, q) == 1


def pd_exact(M):
    """M: symmetric matrix of Python ints (list of lists).  True iff M is positive definite: every leading
    principal minor > 0 (Sylvester).  Fraction-free Bareiss elimination: the k-th pivot IS the k-th leading
    principal minor, and every division is exact."""
    A = [list(r) for r in M]
    s = len(A)
    for i in range(s):
        for j in range(s):
            assert A[i][j] == A[j][i]
    prev = 1
    for k in range(s):
        piv = A[k][k]
        if piv <= 0:
            return False
        Ak = A[k]
        for i in range(k + 1, s):
            Ai = A[i]
            aik = Ai[k]
            for j in range(k + 1, s):
                num = Ai[j] * piv - aik * Ak[j]
                qt, r = divmod(num, prev)
                assert r == 0
                Ai[j] = qt
        prev = piv
    return True


def raw_to_fraction(r):
    """mpmath raw mpf tuple (sign, man, exp, bc) -> exact Fraction"""
    sgn, man, exp, _ = r
    v = Fraction(int(man)) * (Fraction(2) ** int(exp))
    return -v if sgn else v


# ------------------------------------------------------------------------------------------ the plane
class Plane:
    def __init__(self, q, kind, n0):
        assert is_prime(q) and q > 2, q
        n0 %= q
        if kind == 'std':
            assert n0 == 1, "std must be x^2 + y^2"
        elif kind == 'inert':
            assert not is_square_mod(-n0, q), "inert: -n0 must be a non-square (norm form of F_{q^2})"
        else:
            raise ValueError(kind)
        self.q, self.kind, self.n0, self.n = q, kind, n0, q * q
        p = np.arange(self.n)
        self.X, self.Y = p // q, p % q                        # point index p = x*q + y
        self.Qv = (self.X * self.X + n0 * self.Y * self.Y) % q
        self.unit = self.Qv == 1
        self.N = int(self.unit.sum())
        niso = int((self.Qv == 0).sum()) - 1
        if kind == 'inert':
            assert niso == 0 and self.N == q + 1               # anisotropic: the finite plane G_q
        else:
            assert self.N == (q - 1 if q % 4 == 1 else q + 1)
        # O(Q): all [[a, b], [c, d]] with Q(a x + b y, c x + d y) = Q(x, y) identically, i.e.
        # a^2 + n0 c^2 = 1, b^2 + n0 d^2 = n0, a b + n0 c d = 0   (char != 2)
        e1 = [(a, c) for a in range(q) for c in range(q) if (a * a + n0 * c * c) % q == 1]
        e2 = [(b, d) for b in range(q) for d in range(q) if (b * b + n0 * d * d) % q == n0]
        self.OQ = [np.array([[a, b], [c, d]]) for (a, c) in e1 for (b, d) in e2 if (a * b + n0 * c * d) % q == 0]
        assert len(self.OQ) == 2 * self.N
        for R in self.OQ:                                       # brute-force check: bijective isometries
            img = self.image(R)
            assert np.all(self.Qv[img] == self.Qv) and len(np.unique(img)) == self.n

    def idx(self, x, y):
        q = self.q
        return (x % q) * q + (y % q)

    def diff(self, u, v):                                        # index of u - v
        return self.idx(self.X[u] - self.X[v], self.Y[u] - self.Y[v])

    def image(self, R):                                          # index of R p, for all p
        return self.idx(R[0, 0] * self.X + R[0, 1] * self.Y, R[1, 0] * self.X + R[1, 1] * self.Y)


def pair_classes(P):
    """orbits of ordered pairs (a, b) under O(Q) x S_3 (relabellings of the triangle (0, a, b)).
    Canonical key = smallest pair index a*n + b over the orbit, computed by running over the WHOLE group
    (6 * 2N elements), so it is exactly the orbit minimum.  Returns (uniq keys sorted, class id per pair)."""
    n = P.n
    pairs = np.arange(n * n, dtype=np.int64)
    A = (pairs // n).astype(np.int64)
    B = (pairs % n).astype(np.int64)
    Z = np.zeros_like(A)
    pts = (Z, A, B)
    imgs = [P.image(R).astype(np.int64) for R in P.OQ]
    canon = pairs.copy()
    for perm in itertools.permutations(range(3)):
        base = pts[perm[0]]
        d1 = P.diff(pts[perm[1]], base)
        d2 = P.diff(pts[perm[2]], base)
        for img in imgs:
            key = img[d1] * n + img[d2]
            np.minimum(canon, key, out=canon)
        del d1, d2
    del A, B, Z, pairs
    uniq, inv = np.unique(canon, return_inverse=True)
    return uniq, inv.astype(np.int64)



# ------------------------------------------------------------------------------------------ the check
class Check:
    """Rebuilds the programme for the plane of a certificate and evaluates the certificate on it."""

    def __init__(self, path, m1_only=False):
        self.m1_only = m1_only
        d = np.load(path, allow_pickle=False)
        self.meta = meta = json.loads(str(d['meta']))
        self.z = np.array(d['z'], dtype=np.float64)
        self.value = float(d['value'])
        self.status = str(d['status'])
        log(f"certificate {os.path.basename(path)}: status '{self.status}', solver value {self.value:.6f}, "
            f"len(z) = {len(self.z)}")
        opts = meta.get('options', {})
        assert not any(opts.values()) and meta.get('K0') is None, "only the plain programme is supported"
        q, kind, n0 = int(meta['q']), meta['kind'], int(meta['n0'])
        self.P = P = Plane(q, kind, n0)
        self.q, self.kind, self.n, self.N = q, kind, P.n, P.N
        assert P.N == meta['N'], (P.N, meta['N'])
        log(f"plane {kind}{q}: n = {P.n}, Q = x^2 + {P.n0} y^2, N = {P.N} unit vectors, |O(Q)| = {len(P.OQ)}")
        self._orbits()
        self._delsarte_rows()
        self._split()
        self._rotation_data()
        self._certify_blocks()
        self._linear_part()

    # ---------------------------------------------------------------- orbits of pairs (the variables)
    def _orbits(self):
        P, n = self.P, self.n
        uniq, inv = pair_classes(P)
        C = len(uniq)
        ra, rb = uniq // n, uniq % n                              # representative = smallest pair
        is_origin = uniq == 0
        degen = (ra == 0) | (rb == 0) | (ra == rb)
        unit_sided = P.unit[ra] | P.unit[rb] | P.unit[P.diff(rb, ra)]
        # degeneracy and unit sides are isometry invariants, so constant on orbits: check
        pa = np.arange(n * n, dtype=np.int64) // n
        pb = np.arange(n * n, dtype=np.int64) % n
        assert np.array_equal((pa == 0) | (pb == 0) | (pa == pb), degen[inv])
        assert np.array_equal(P.unit[pa] | P.unit[pb] | P.unit[P.diff(pb, pa)], unit_sided[inv])
        del pa, pb
        circ = inv[:n].copy()                                      # class of (0, w): the circle of w
        w_all = np.arange(n)
        assert np.array_equal(inv[w_all * n + w_all], circ) and np.array_equal(inv[w_all * n], circ)
        # the circles are exactly {0}, the level sets Q = r != 0, and the nonzero isotropic vectors
        for c in np.unique(circ):
            W_ = np.nonzero(circ == c)[0]
            if c == circ[0]:
                assert list(W_) == [0]
            else:
                r = set(P.Qv[W_].tolist())
                assert len(r) == 1
                r = r.pop()
                assert np.array_equal(W_, np.nonzero((P.Qv == r) & (w_all != 0))[0])
        self.free = free = ~is_origin & ~unit_sided
        self.tri = np.nonzero(free & ~degen)[0]                    # sorted by smallest pair index (A3)
        self.circles_free = np.nonzero(free & degen)[0]
        self.origin_cls = int(circ[0])
        assert self.origin_cls == 0 and is_origin[0]
        self.uniq, self.inv, self.C, self.ra, self.rb = uniq, inv, C, ra, rb
        self.degen, self.unit_sided, self.circ = degen, unit_sided, circ
        sizes_cls = np.bincount(inv, minlength=C)
        log(f"{C} orbits of ordered pairs: {len(self.tri)} free triangle orbits, {len(self.circles_free)} free "
            f"circles, {int(unit_sided.sum())} with a unit side; largest orbit {sizes_cls.max()} pairs")

    # ---------------------------------------------------------------- Delsarte rows in the file's order (A4)
    def _delsarte_rows(self):
        P, q, n = self.P, self.q, self.n
        filecls = np.where(P.Qv == 0, q, P.Qv)
        filecls[0] = 0
        seen = {}
        self.rows_xi = []
        for xi in range(1, n):
            a_, b_ = divmod(xi, q)
            ph = np.cos(2 * np.pi * ((a_ * P.X + b_ * P.Y) % q) / q)
            r = np.bincount(filecls, weights=ph, minlength=q + 1)
            key = tuple(np.round(r, 6))
            if key not in seen:
                seen[key] = xi
                self.rows_xi.append(xi)

    # ---------------------------------------------------------------- split z (A2, A5)
    def _split(self):
        meta, z, N = self.meta, self.z, self.N
        m = self.m = int(meta['m'])
        self.reps = [int(x) for x in meta['reps']]
        self.partner = [int(x) for x in meta['partner']]
        self.shift = [float(x) for x in meta['shift']]
        assert len(self.reps) == m == len(self.partner) == len(self.shift)
        self.blocks = [(1, k, m + (1 if k == 0 else 0)) for k in range(N // 2 + 1)] + \
                      [(0, k, m) for k in range(N // 2 + 1)]
        assert len(self.blocks) == meta['nrot']
        nz, ng, nch = len(self.tri), len(self.circles_free), len(self.rows_xi)
        nv, nlin = nz + ng, 6 * nz
        total = nv + nlin + nch + sum(s * (s + 1) // 2 for _, _, s in self.blocks)
        assert total == len(z), f"length mismatch: {total} from the rebuilt programme, {len(z)} in the file"
        log(f"z splits as {nv} (var >= 0) + {nlin} (triangle inequalities) + {nch} (Delsarte) + "
            f"{len(self.blocks)} psd blocks: length {total} matches")
        assert np.all(z[:nv] == 0), "multipliers of v >= 0 are not all zero"
        z_lin, z_del = z[nv:nv + nlin], z[nv + nlin:nv + nlin + nch]
        log(f"linear multipliers: min {z_lin.min():.3e}, {int((z_lin < 0).sum())} negative (set to 0); "
            f"Delsarte multipliers: min {z_del.min():.3e}, {int((z_del < 0).sum())} negative (set to 0)")
        self.z_lin, self.z_del = np.maximum(z_lin, 0.0), np.maximum(z_del, 0.0)
        if self.m1_only:                                       # keep only M1 >= 0 (and 0 <= z <= 1)
            self.z_lin, self.z_del = 0 * self.z_lin, 0 * self.z_del
            log("--m1-only: triangle and Delsarte multipliers and the M0 blocks set to zero")
        pos = nv + nlin + nch
        self.Yblocks = []
        for which, k, s in self.blocks:
            sv = z[pos:pos + s * (s + 1) // 2]
            pos += s * (s + 1) // 2
            Yf = np.zeros((s, s))
            t = 0
            for j in range(s):
                for i in range(j + 1):
                    Yf[i, j] = Yf[j, i] = sv[t] if i == j else sv[t] / np.sqrt(2)
                    t += 1
            self.Yblocks.append(Yf)
        assert pos == len(z)

    # ---------------------------------------------------------------- the rotation basis (A5)
    def _rotation_data(self):
        P, q, n, N, m, meta = self.P, self.q, self.n, self.N, self.m, self.meta
        sig, tau = np.array(meta['sig']) % q, np.array(meta['tau']) % q
        det = lambda R: int(R[0, 0] * R[1, 1] - R[0, 1] * R[1, 0]) % q
        inO = lambda R: any(np.array_equal(R, S) for S in P.OQ)
        assert inO(sig) and det(sig) == 1 and inO(tau) and det(tau) == q - 1
        simg, timg = P.image(sig), P.image(tau)
        orbit = np.zeros((m, N), dtype=np.int64)
        for a in range(m):
            p = self.reps[a]
            for i in range(N):
                orbit[a, i] = p
                p = simg[p]
            assert p == self.reps[a]
        assert np.array_equal(np.sort(orbit.ravel()), np.arange(1, n)), "sig-orbits do not partition P - 0"
        for a in range(m):                                          # J-reality data (for real blocks only)
            b = self.partner[a]
            if b < 0:
                t2 = int(round(2 * self.shift[a]))
                assert abs(2 * self.shift[a] - t2) < 1e-12 and timg[self.reps[a]] == orbit[a, t2 % N]
            else:
                assert self.partner[b] == a and self.shift[a] == 0 and timg[self.reps[a]] == self.reps[b]
        self.orbit = orbit
        log("rotation data checked: sig in SO(Q) of order N, its orbits partition P - 0; tau a reflection "
            "with tau(rep_a) = sig^(2 shift_a) rep_a, or = rep of the partner orbit")

    def basis(self, which, k):
        """[Re V, Im V] (dim x 2s) as a float array of exact integers; the basis is that array / 2^52"""
        n, N, m = self.n, self.N, self.m
        s = m + (1 if (which == 1 and k == 0) else 0)
        V = np.zeros((n, s), complex)
        col = 0
        if which == 1 and k == 0:
            V[0, 0] = 1.0
            col = 1
        jj = np.arange(N)

        def u(a):
            t2 = (2 * k * jj - int(round(2 * k * self.shift[a]))) % (2 * N)
            vec = np.zeros(n, complex)
            vec[self.orbit[a]] = (np.cos(np.pi * t2 / N) + 1j * np.sin(np.pi * t2 / N)) / np.sqrt(N)
            return vec
        done = set()
        for a in range(m):
            if a in done:
                continue
            b = self.partner[a]
            if b < 0:
                V[:, col] = u(a)
                col += 1
                done.add(a)
            else:
                ua, ub = u(a), u(b)
                V[:, col] = (ua + ub) / np.sqrt(2)
                V[:, col + 1] = 1j * (ua - ub) / np.sqrt(2)
                col += 2
                done.update((a, b))
        assert col == s
        T = np.rint(np.ldexp(np.hstack([V.real, V.imag]), 52))
        return T[1:] if which == 0 else T                          # M0 lives on P - {0}

    # ---------------------------------------------------------------- PSD blocks: exact certification
    def _certify_blocks(self):
        self.cert_blocks = []
        for (which, k, s), Yf in zip(self.blocks, self.Yblocks):
            if not np.any(Yf) or (self.m1_only and which == 0):
                self.cert_blocks.append(None)
                continue
            lam, U = np.linalg.eigh(Yf)
            lmax = float(lam.max())
            if lmax <= 0:
                self.cert_blocks.append(None)
                continue
            Yc = (U * np.maximum(lam, 0.0)) @ U.T
            ok = False
            for eps in (1e-12, 1e-11, 1e-10, 1e-9, 1e-8, 1e-7, 1e-6):
                Y2 = Yc + eps * lmax * np.eye(s)
                Y2 = (Y2 + Y2.T) / 2
                E = 51 - math.frexp(float(np.abs(Y2).max()))[1]   # max |Y2| 2^E < 2^51
                Yi = np.rint(np.ldexp(Y2, E))
                Yi = np.triu(Yi) + np.triu(Yi, 1).T
                M = [[int(Yi[i, j]) for j in range(s)] for i in range(s)]
                if pd_exact(M):
                    ok = True
                    break
            assert ok, ("block not certifiable", which, k)
            self.cert_blocks.append((M, E, eps, lmax, float(lam.min())))
        used = [c for c in self.cert_blocks if c is not None]
        self.Emax = max(c[1] for c in used)
        self.SCALE = 104 + self.Emax                                 # integer class sums = sums * 2^SCALE
        log(f"psd blocks: {len(used)} proved positive definite exactly (shift eps*lambda_max, eps up to "
            f"{max(c[2] for c in used):.0e}; worst raw lambda_min/lambda_max = "
            f"{min(c[4] / c[3] for c in used):.2e}), {len(self.cert_blocks) - len(used)} zero")

    def Yhat(self, i):
        """the certified dual block i, as an exact float matrix (None for zero)"""
        cb = self.cert_blocks[i]
        return None if cb is None else np.ldexp(np.array(cb[0], dtype=float), -cb[1])

    # ---------------------------------------------------------------- objective, (L), (D): exact
    def _linear_part(self):
        P, q, C, circ = self.P, self.q, self.C, self.circ
        coefF = [Fraction(0)] * C
        constF = Fraction(0)
        for c, cnt in zip(*np.unique(circ, return_counts=True)):     # objective sum_w z(0, w)
            coefF[int(c)] += int(cnt)
        self.lin_rows = []                                            # (multiplier, const, {class: coef})
        for i, t in enumerate(self.tri):                              # (L), A3
            a, b = int(self.ra[t]), int(self.rb[t])
            sides = [int(circ[a]), int(circ[b]), int(circ[P.diff(b, a)])]
            lv = [Fraction(float(x)) for x in self.z_lin[6 * i:6 * i + 6]]
            for j in range(3):                                        # z(0, s_j) - z_t >= 0
                self.lin_rows.append((lv[j], 0, {sides[j]: 1, int(t): -1}))
            for jj, (i1, i2) in enumerate([(0, 1), (0, 2), (1, 2)]):  # 1 - z(0,s_i1) - z(0,s_i2) + z_t >= 0
                d_ = {int(t): 1}
                d_[sides[i1]] = d_.get(sides[i1], 0) - 1
                d_[sides[i2]] = d_.get(sides[i2], 0) - 1
                self.lin_rows.append((lv[3 + jj], 1, d_))
        for lam, cst, d_ in self.lin_rows:
            if lam:
                constF += lam * cst
                for c, v in d_.items():
                    coefF[c] += lam * v
        from mpmath import iv                                         # (D), A4: intervals
        iv.prec = 128
        cosI = []
        for j in range(q):
            c_ = iv.cos(2 * iv.pi * j / q)
            cosI.append((raw_to_fraction(c_._mpi_[0]), raw_to_fraction(c_._mpi_[1])))
        self.cosI = cosI
        del_lo, del_hi = [Fraction(0)] * C, [Fraction(0)] * C
        for r, xi in enumerate(self.rows_xi):
            mu = Fraction(float(self.z_del[r]))
            if mu == 0:
                continue
            a_, b_ = divmod(xi, q)
            tph = (a_ * P.X + b_ * P.Y) % q
            for c in np.unique(circ):
                cnt = np.bincount(tph[circ == c], minlength=q)
                del_lo[int(c)] += mu * sum(int(cnt[j]) * cosI[j][0] for j in range(q) if cnt[j])
                del_hi[int(c)] += mu * sum(int(cnt[j]) * cosI[j][1] for j in range(q) if cnt[j])
        self.coefF, self.constF, self.del_lo, self.del_hi = coefF, constF, del_lo, del_hi

    # ---------------------------------------------------------------- the psd part
    def labels0(self, rows):
        """for rows (indices into P - {0}) of W0: classes of (0, y - x) [plus] and of (x, y) [minus]"""
        n = self.n
        xs = np.arange(1, n)
        xr = xs[rows]
        minus = self.inv[(xr[:, None] * n + xs[None, :]).ravel()]
        plus = self.circ[self.P.diff(np.broadcast_to(xs[None, :], (len(xr), n - 1)).ravel(), np.repeat(xr, n - 1))]
        return plus, minus

    def W_float(self, which):
        """W_which = sum_k A Y A^T + B Y B^T in floating point (for previews and tests)"""
        dim = self.n if which == 1 else self.n - 1
        W = np.zeros((dim, dim))
        for i, (wh, k, s) in enumerate(self.blocks):
            Yh = self.Yhat(i)
            if wh != which or Yh is None:
                continue
            T = np.ldexp(self.basis(which, k), -52)
            A_, B_ = T[:, :s], T[:, s:]
            W += (A_ @ Yh) @ A_.T + (B_ @ Yh) @ B_.T
        return W

    def psd_coef_float(self):
        coefW = np.zeros(self.C)
        W1 = self.W_float(1)
        coefW += np.bincount(self.inv, weights=W1.ravel(), minlength=self.C)
        del W1
        W0 = self.W_float(0)
        plus, minus = self.labels0(np.arange(self.n - 1))
        coefW += np.bincount(plus, weights=W0.ravel(), minlength=self.C)
        coefW -= np.bincount(minus, weights=W0.ravel(), minlength=self.C)
        return coefW

    def psd_coef_exact(self, chunk=500):
        """exact integer class sums of W1 and of the M0 pairing, at scale 2^SCALE"""
        from flint import fmpz_mat
        acc = [0] * self.C
        for which in (1, 0):
            dim = self.n if which == 1 else self.n - 1
            mats = []
            for i, (wh, k, s) in enumerate(self.blocks):
                cb = self.cert_blocks[i]
                if wh != which or cb is None:
                    continue
                M, E = cb[0], cb[1]
                T = self.basis(which, k).astype(np.int64)             # exact integers (|T| <= 2^52)
                TmT = fmpz_mat(dim, 2 * s, [int(v) for v in T.ravel()]).transpose()
                sc = 1 << (self.Emax - E)                            # common scale 2^Emax
                Yd = [[0] * (2 * s) for _ in range(2 * s)]           # diag(Y, Y)
                for a in range(s):
                    for b in range(s):
                        Yd[a][b] = Yd[s + a][s + b] = M[a][b] * sc
                mats.append((T, fmpz_mat(Yd), TmT))
            t1 = time.time()
            if not mats:
                log(f"M{which}: every dual block is zero, W{which} = 0")
                continue
            for r0 in range(0, dim, chunk):
                r1 = min(dim, r0 + chunk)
                Wc = None                                            # rows r0..r1-1 of W * 2^SCALE, exactly
                for T, Ym, TmT in mats:
                    Tr = fmpz_mat(r1 - r0, T.shape[1], [int(v) for v in T[r0:r1].ravel()])
                    prod = (Tr * Ym) * TmT
                    Wc = prod if Wc is None else Wc + prod
                vals = Wc.entries()
                del Wc
                if which == 1:
                    for l_, v_ in zip(self.inv[r0 * self.n:r1 * self.n].tolist(), vals):
                        acc[l_] += int(v_)
                else:
                    plus, minus = self.labels0(np.arange(r0, r1))
                    for lp, lm, v_ in zip(plus.tolist(), minus.tolist(), vals):
                        iv_ = int(v_)
                        acc[lp] += iv_
                        acc[lm] -= iv_
                del vals
            log(f"M{which}: exact class sums of W{which} done ({len(mats)} nonzero blocks, {time.time() - t1:.0f}s)")
        return acc

    # ---------------------------------------------------------------- the bound
    def bound_exact(self, acc):
        den = 1 << self.SCALE
        C, free_ids = self.C, np.nonzero(self.free)[0]
        hi = [Fraction(acc[t], den) + self.coefF[t] + self.del_hi[t] for t in range(C)]
        c0 = self.constF + hi[self.origin_cls]
        pen = sum((max(Fraction(0), hi[t]) for t in free_ids), Fraction(0))
        width = max(float(self.del_hi[t] - self.del_lo[t]) for t in range(C))
        worst = max(float(hi[t]) for t in free_ids)
        return c0 + pen, c0, pen, worst, width

    def bound_float(self, coefW):
        tot = np.array([float(self.coefF[t]) + float(self.del_hi[t]) for t in range(self.C)]) + coefW
        c0 = float(self.constF) + tot[self.origin_cls]
        pen = float(np.maximum(tot[self.free], 0).sum())
        return c0 + pen, c0, pen


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('cert')
    ap.add_argument('--float-only', action='store_true', help='numerical preview only (not rigorous)')
    ap.add_argument('--chunk', type=int, default=500, help='rows per exact product chunk')
    ap.add_argument('--m1-only', action='store_true', help='use only the M1 dual blocks (drop M0, (L), (D))')
    args = ap.parse_args()
    ch = Check(args.cert, m1_only=args.m1_only)
    n, kind, q = ch.n, ch.kind, ch.q
    if args.float_only:
        b, c0, pen = ch.bound_float(ch.psd_coef_float())
        log(f"FLOAT PREVIEW (not rigorous): c_0 = {c0:.6f}, positive residuals {pen:.3e}, bound {b:.6f} "
            f"(solver value {ch.value:.6f})")
        return
    acc = ch.psd_coef_exact(chunk=args.chunk)
    bound, c0, pen, worst, width = ch.bound_exact(acc)
    bf = math.ceil(float(bound) * 1e6) / 1e6
    while Fraction(bf) < bound:
        bf += 1e-6
    log(f"RIGOROUS: c_0 = {float(c0):.8f}, sum of positive residuals = {float(pen):.3e} "
        f"(largest {worst:.2e}; Delsarte interval width <= {width:.1e})")
    print(f"RESULT {kind}{q}: alpha <= {bf:.6f}  (exact rational upper bound; solver value {ch.value:.6f}; "
          f"n/5 = {n / 5:.1f}, n/4 = {n / 4:.2f})", flush=True)
    fl = int(math.floor(bound))
    if 5 * fl < n:
        print(f"         alpha <= {fl} < n/5 = {n / 5}: chi >= n/alpha > 5, so chi >= 6", flush=True)
    elif 4 * fl < n:
        print(f"         alpha <= {fl} < n/4 = {n / 4}: chi >= n/alpha > 4, so chi >= 5", flush=True)


if __name__ == '__main__':
    main()
