"""Two arithmetic conditions, at 3 and at 5, and the smallest field meeting both.

AT 5 -- blocking.  Every prime of F = K n R above 5 must have residue degree
at least 3, or a functional supported on the offending orbit gives a coset
5-colouring and chi <= 5.

AT 3 -- rigidity.  A rhombus 0, w, zeta_6 w, w(1+zeta_6) forces its tip to the
apex's colour, and chaining k of them closes into a 4-chromatic graph exactly
when |w_1 + .. + w_k|^2 = 1/3.  If a prime q above 3 is FIXED by conjugation
then qbar = q, so for every unit step v_q(u) + v_q(ubar) = 2 v_q(u) = 0 and
every unit step has v_q(u) = 0.  A sum of them has v_q >= 0, while 1/3 has
v_q = -e < 0.  So

    IF EVERY PRIME ABOVE 3 IS FIXED BY CONJUGATION, NO RHOMBUS CHAIN EVER
    CLOSES -- at any length k, over any such field.

This generalises the no-Eisenstein-spindle result from k = 2 to all k, and it
explains the Moser spindle: rho = (5 + sqrt-11)/6 has v = +1 at one prime
above 3 of Q(sqrt-11) and -1 at its conjugate, which is only possible because
3 SPLITS there.  So a chain needs some prime of F above 3 to split in K.

Both conditions are read off (Z/n)* for a cyclotomic field, so the smallest
one carrying triangles, a closing chain and the possibility of blocking is a
finite search.
"""
import sys
sys.path.insert(0, "/home/user/darwin-50/research/hadwiger-nelson")
from hn.homcol import cyclotomic_can_block


def order(a, m):
    f, x = 1, a % m
    while x != 1 % m:
        x = x * a % m
        f += 1
    return f


def three_splits(n):
    """Does some prime of F above 3 split in K = Q(zeta_n)?

    Conjugation moves a prime above 3 exactly when -1 lies outside its
    decomposition group, which for n = 3^a . m is generated by the inertia
    subgroup (the part acting on the 3-power component) and Frobenius.
    """
    m, a = n, 0
    while m % 3 == 0:
        m //= 3
        a += 1
    if m == 1:
        return False
    f = order(3, m)
    tail = {pow(3, k, m) for k in range(f)}
    # -1 in K lies in the decomposition group iff its prime-to-3 part is a
    # power of Frobenius; the 3-part is absorbed by inertia.
    return (m - 1) % m not in tail


print(f"{'n':>4} {'deg':>4} {'res deg over F at 5':>20} {'blocks':>7} "
      f"{'3 splits':>9}  verdict", flush=True)
best = None
for n in range(3, 130, 3):
    if n % 9 == 0 and n > 9:
        pass
    v = cyclotomic_can_block(n)
    if v.get("ramified"):
        continue
    sp = three_splits(n)
    ok = v["can_block"] and sp
    if ok and best is None:
        best = n
    if ok or n <= 45:
        deg = sum(1 for k in range(1, n) if __import__("math").gcd(k, n) == 1)
        print(f"{n:>4} {deg:>4} {v['residue_degree_over_F']:>20} "
              f"{str(v['can_block']):>7} {str(sp):>9}  "
              + ("BOTH" if ok else ""), flush=True)
print(f"\nsmallest cyclotomic field with triangles, a closing chain and "
      f"blocking: Q(zeta_{best})", flush=True)
