"""The graph, screened on its own edge vectors rather than on its steps.

Blocking is a property of the module generated by a graph's EDGE vectors, and
a ball built from a few steps generates less than the full norm-one group --
so the 63 blocking directions need not survive into it. The check that matters
is therefore run on the graph, not on the step list it came from:

  1. build a ball from steps chosen to block,
  2. take every exact unit-distance pair, which is a richer edge set than the
     steps alone,
  3. screen THAT for a coset 5-colouring,
  4. and only then ask a solver for an ordinary one.

Edges are found through a bucketed float pre-filter with exact confirmation,
because a quadratic scan over a degree-6 field is the slow part by far.
"""
import sys, time, itertools, collections, random
sys.path.insert(0, "/home/user/darwin-50/research/hadwiger-nelson")
from fractions import Fraction
from math import gcd
from hn.cyclotomic import CycloField
from hn.homcol import has_homomorphism

F = CycloField(7)
D = F.degree
one = F.rational(1)


def inverse(a):
    rows = []
    for i in range(D):
        e = [Fraction(0)] * D
        e[i] = Fraction(1)
        rows.append(list(F.mul(a, tuple(e))))
    M = [[rows[j][i] for j in range(D)] + [Fraction(1 if i == 0 else 0)]
         for i in range(D)]
    for c in range(D):
        p = next(r for r in range(c, D) if M[r][c])
        M[c], M[p] = M[p], M[c]
        inv = Fraction(1) / M[c][c]
        M[c] = [v * inv for v in M[c]]
        for r in range(D):
            if r != c and M[r][c]:
                f = M[r][c]
                M[r] = [x - f * y for x, y in zip(M[r], M[c])]
    return tuple(M[i][D] for i in range(D))


t0 = time.time()
steps, seen = [], set()
for coeffs in itertools.product(range(-2, 3), repeat=4):
    a = tuple(Fraction(c) for c in coeffs) + (Fraction(0), Fraction(0))
    if not any(a):
        continue
    try:
        u = F.mul(a, inverse(F.conj(a)))
    except (StopIteration, ZeroDivisionError):
        continue
    if F.norm2(u) != one or u in seen:
        continue
    seen.add(u)
    den = 1
    for x in u:
        den = den * x.denominator // gcd(den, x.denominator)
    if den % 5 == 0:
        continue
    steps.append((den, u))
steps.sort(key=lambda t: t[0])
print(f"{len(steps)} modulus-one steps, denominators "
      f"{sorted({d for d, _ in steps})[:6]}  [{time.time()-t0:.0f}s]",
      flush=True)

random.seed(11)
use = [u for _, u in steps[:14]]
pts = {F.zero()}
for rnd in range(4):
    new = set(pts)
    for p in pts:
        for s in use:
            new.add(F.add(p, s))
            new.add(F.sub(p, s))
    if len(new) > 2600:
        break
    pts = new
P = sorted(pts, key=lambda q: abs(F.to_complex(q)))
print(f"  ball: {len(P)} points  [{time.time()-t0:.0f}s]", flush=True)

zs = [F.to_complex(q) for q in P]
cells = collections.defaultdict(list)
for i, z in enumerate(zs):
    cells[(int(z.real // 1), int(z.imag // 1))].append(i)
edges = []
for i, z in enumerate(zs):
    cx, cy = int(z.real // 1), int(z.imag // 1)
    for dx in (-1, 0, 1):
        for dy in (-1, 0, 1):
            for j in cells.get((cx + dx, cy + dy), ()):
                if j <= i or abs(abs(zs[i] - zs[j]) - 1) > 1e-7:
                    continue
                if F.norm2(F.sub(P[i], P[j])) == one:
                    edges.append((i, j))
print(f"  graph: {len(P)} vertices, {len(edges)} edges  "
      f"[{time.time()-t0:.0f}s]", flush=True)

ev = set()
for i, j in edges:
    d = F.sub(P[j], P[i])
    ev.add(tuple(d))
den = 1
for v in ev:
    for x in v:
        den = den * x.denominator // gcd(den, x.denominator)
iv = {tuple(int(x * den) for x in v) for v in ev}
c = 0
for v in iv:
    for t in v:
        c = gcd(c, abs(t))
iv = sorted({tuple(t // c for t in v) for v in iv}) if c > 1 else sorted(iv)
print(f"  {len(iv)} distinct edge vectors  [{time.time()-t0:.0f}s]", flush=True)
phi, why = has_homomorphism(iv, 5)
print(f"  coset 5-colouring: " + ("EXISTS" if phi else f"NONE ({why})")
      + f"  [{time.time()-t0:.0f}s]", flush=True)

from pysat.solvers import Solver
for k in (4, 5):
    cls = [[1 + v * k + cc for cc in range(k)] for v in range(len(P))]
    for a, b in edges:
        for cc in range(k):
            cls.append([-(1 + a * k + cc), -(1 + b * k + cc)])
    with Solver(name="cd19", bootstrap_with=cls) as s:
        r = s.solve()
    print(f"  {k}-colourable: {r}"
          + ("" if r else f"   *** chi > {k} ***") + f"  [{time.time()-t0:.0f}s]",
          flush=True)
