"""An audit of the five formulas of the proof that alpha(G_13) <= 36 (notes/g13.md, section 3), read from their
DIMACS text alone.

G_13. The vertex v = 13x + y is the point (x, y) of F_13^2, read as x + y w in the field F_13[w], w^2 = 2 (2 is not
a square mod 13), where (a + b w)(c + d w) = (ac + 2bd) + (ad + bc) w and conj(x + y w) = x - y w. Two vertices are
adjacent when the difference d of their points has N(d) = d_x^2 - 2 d_y^2 = 1 (mod 13). The circle C_c is
{z : N(z) = c}, c = 1, ..., 12. The 4732 maps z -> l z + a and z -> l conj(z) + a, N(l) = 1, act on the vertices.
The audit rebuilds all of this from these definitions, without the code that wrote the formulas.

The proof. An independent set of 37 vertices lies in a maximal one S, which is independent and dominating (every
vertex is in S or adjacent to a point of S). A *rosette* is a point p together with its whole circle p + C_c, for a
circle for which this is an independent set: of the circles without a unit distance inside (c = 1, 6, 7, 9, 11) all
but C_1, whose points are the neighbours of p; so c = 6, 7, 9, 11. Case A_c: S contains a rosette with the circle
C_c; translated by -p, S satisfies formula E37_A_c. Case B: S contains no rosette; then the image of S under the maps
whose indicator, read on a fixed prefix of 25 vertices, is lex-greatest satisfies formula E37_B. All five formulas
are unsatisfiable (kissat, with proofs checked by drat-trim; E37_B by cube and conquer). For this to prove the claim,
each formula must be satisfiable whenever its configuration exists: every clause must hold in the intended model,
with the vertex variables (vertex v is the variable v + 1) as the set, the counter variables as counts, and the chain
variables as "equal so far". The audit checks this clause by clause, and fails on any clause that it cannot classify.

Formula E37_A_c must consist of exactly these clauses:
  - edge clauses -x_u | -x_v, with u, v adjacent (the set is independent);
  - domination clauses, positive, each on the closed neighbourhood of a vertex (the set is dominating);
  - the unit clauses x_v for the vertices v of {0} + C_c, each once, where {0} + C_c is a rosette (so C_c is
    independent, and {0} + C_c too);
  - a totalizer. The audit rebuilds its binary tree from the clauses. It checks that the leaves are the 169 vertex
    variables, each once, that the tree has 168 nodes, that every node carries exactly the clauses of the standard
    totalizer (its outputs o_1, ..., o_m, m = min(37, size), with the clauses o_{a+1}(L) | o_{b+1}(R) | -o_{a+b+1}
    for its children L and R, a literal o_{|L|+1}(L) or o_{|R|+1}(R), which does not exist, left out), and that o_37
    of the root is a unit clause. With o_j = [at least j of the leaves below are true], every clause holds as soon
    as 37 vertices are true.
Formula E37_B must consist of exactly these clauses:
  - edge clauses, domination clauses and a totalizer, as in E37_A_c;
  - no-rosette clauses: negative, each on a rosette {p} + (p + C_c) (the set contains no rosette);
  - lex-leader chains. A chain compares x_v with x_w, w = g(v), for a map g, at the positions v_0, v_1, ... in
    turn; its variable e_k says that its first k + 1 pairs agree. Its clauses are x_v0 | -x_w0 and, for k > 0,
    -e_{k-1} | x_vk | -x_wk; and for every pair but the last, x_vk | e_k and -x_wk | e_k, with -e_{k-1} added for
    k > 0. The chain variables come after the counters (a chain of one pair has none). The audit reads the chains
    off the clauses: the pairs of each, in their order. It checks that all chains visit their positions in one
    common order, the prefix, of at most 25 vertices; and that for each chain one of the 4732 maps sends every
    position the chain compares to the vertex it compares it with, and fixes every other position of the prefix.
    Then, with e_k = [the first k + 1 pairs agree], the chain holds exactly when the indicator of the set, read on
    the prefix, is lex-greater than or equal to that of g^-1(S): the positions that the chain skips compare equal.
    Each of the 4732 maps is z -> L(z) + a, a linear map L (one of 28) followed by a translation. The audit checks
    that the linear map and the translation of each chain's map each send the set of edge clauses, the set of
    domination clauses and the set of no-rosette clauses (as sets of vertex sets) onto itself; so the map does too.
    Why this is enough: let S be a solution of the clauses other than the chains, G the group generated by the maps
    of the chains, and T the image of S under G whose indicator on the prefix is lex-greatest. The maps in G send
    the solutions of those clauses to solutions (the totalizer counts all the vertices), so T is one; and for each
    chain, g^-1(T) is an image of S under G, so the chain holds for T. This does not need a chain for every map;
    the audit reports how many chains and how many distinct maps there are.
A clause that is missing (other than in the totalizer) only makes a formula easier to satisfy, so the audit does not
ask for every edge, domination or no-rosette clause to be present, as long as the maps of the chains send the sets
of them that are present onto themselves. It reports how many distinct ones there are. The first clauses of the
chains, x_v0 | -x_w0, are not distinct: there is one for each chain that starts with the pair (v0, w0).

usage: python3 scripts/g13/g13_audit.py [DIR]
Audits the formulas E37_A_c, for every circle C_c of a rosette, and E37_B, as scripts/g13/enum_cert.py writes them
(into a temporary directory), or, with DIR, the files DIR/E37_A6.cnf, ..., DIR/E37_B.cnf.
"""
import hashlib
import os
import subprocess
import sys
import tempfile
from collections import Counter, defaultdict

Q = 13
NV = Q * Q          # the vertex variables are 1, ..., 169
T = 37              # the formulas ask for an independent dominating set of at least T vertices
PREFIX = 25         # the chains compare the sets on a prefix of at most this many vertices


class AuditError(Exception):
    pass


def check(condition, message):
    if not condition:
        raise AuditError(message)


def point(v):
    return divmod(v, Q)


def vertex(x, y):
    return Q * (x % Q) + y % Q


def plus(u, v):
    (a, b), (c, d) = point(u), point(v)
    return vertex(a + c, b + d)


def minus(u, v):
    (a, b), (c, d) = point(u), point(v)
    return vertex(a - c, b - d)


def times(u, v):
    (a, b), (c, d) = point(u), point(v)
    return vertex(a * c + 2 * b * d, a * d + b * c)


def conj(v):
    x, y = point(v)
    return vertex(x, -y)


def norm(v):
    x, y = point(v)
    return (x * x - 2 * y * y) % Q


def adjacent(u, v):
    return norm(minus(u, v)) == 1


def independent(vs):
    return not any(adjacent(u, v) for u in vs for v in vs if u < v)


VERTICES = range(NV)
NEIGHBOURS = [[w for w in VERTICES if adjacent(v, w)] for v in VERTICES]
CIRCLES = {c: [v for v in VERTICES if norm(v) == c] for c in range(1, Q)}
INDEPENDENT = [c for c, cc in CIRCLES.items() if independent(cc)]
ROSETTE_CIRCLES = [c for c in INDEPENDENT if independent([0] + CIRCLES[c])]


def closed_neighbourhood(v):
    return frozenset([v] + NEIGHBOURS[v])


def rosette(p, c):
    """the point p with its whole circle p + C_c"""
    return frozenset([p] + [plus(p, q) for q in CIRCLES[c]])


CENTRE = {closed_neighbourhood(v): v for v in VERTICES}
AROUND = {rosette(p, c): (p, c) for c in CIRCLES for p in VERTICES}
LINEAR = [tuple(times(l, conj(z) if flip else z) for z in VERTICES) for flip in (False, True) for l in CIRCLES[1]]
TRANSLATIONS = [tuple(plus(z, a) for z in VERTICES) for a in VERTICES]
MAPS = [tuple(t[x] for x in m) for t in TRANSLATIONS for m in LINEAR]    # MAPS[i]: LINEAR[i % 28], then + (i // 28)
check(len(CENTRE) == NV and len(AROUND) == NV * len(CIRCLES), "two vertices with the same closed neighbourhood, "
      "or a point with its circle equal to another")
check(all(sorted(g) == list(VERTICES) for g in LINEAR + TRANSLATIONS) and len(set(MAPS)) == len(MAPS) == NV * 28,
      "the maps are not 4732 distinct permutations of the vertices")


def parse(text):
    """(the number of variables, the clauses) of a DIMACS text: the header 'p cnf V C', then one clause per line"""
    head, _, body = text.partition("\n")
    words = head.split()
    check(len(words) == 4 and words[:2] == ["p", "cnf"] and all(w.isdigit() for w in words[2:]),
          f"bad header {head!r}")
    nv, nc = int(words[2]), int(words[3])
    clauses = []
    for line in body.splitlines():
        try:
            lits = tuple(map(int, line.split()))
        except ValueError:
            lits = ()
        check(lits and lits[-1] == 0 and 0 not in lits[:-1], f"bad clause line {line!r}")
        check(max(map(abs, lits)) <= nv, f"a variable out of range in {line!r}")
        clauses.append(lits[:-1])
    check(len(clauses) == nc, f"{len(clauses)} clauses, the header says {nc}")
    return nv, clauses


def vertex_clause(c):
    """(kind, what) for a clause on vertex variables alone"""
    neg = [-l - 1 for l in c if l < 0]
    pos = [l - 1 for l in c if l > 0]
    if not pos and len(neg) == 2:
        check(adjacent(*neg), f"an edge clause on vertices {neg[0]} and {neg[1]}, which are not adjacent: {c}")
        return "edge", frozenset(neg)
    if not neg and len(pos) == 15:
        check(frozenset(pos) in CENTRE, f"a positive clause that is not the closed neighbourhood of a vertex: {c}")
        return "domination", frozenset(pos)
    if not pos and len(neg) == 15:
        s = frozenset(neg)
        check(s in AROUND, f"a negative clause of 15 vertices that is not a point with its whole circle: {c}")
        p, cc = AROUND[s]
        check(cc in ROSETTE_CIRCLES, f"a clause against the point {p} with its circle N = {cc}, which together are not "
              f"independent (a rosette has one of the circles {ROSETTE_CIRCLES}): {c}")
        return "no-rosette", s
    if not neg and len(pos) == 1:
        return "unit", pos[0]
    if len(pos) == 1 and len(neg) == 1:
        return "first comparison", (pos[0], neg[0])
    raise AuditError(f"a clause of no known kind: {c}")


def leaves_below(heads, leaves):
    """the leaves below each counter (heads: a counter -> the positive literals of its clauses); fails on a
    variable that is neither a leaf nor a counter, and on counters that depend on each other in a cycle"""
    below = {v: frozenset([v]) for v in leaves}
    for start in heads:
        stack, opened = [start], set()
        while stack:
            y = stack[-1]
            if y in below:
                stack.pop()
                continue
            check(y in heads, f"variable {y} is neither counted nor a counter")
            todo = [z for body in heads[y] for z in body if z not in below]
            if not todo:
                below[y] = frozenset().union(*(below[z] for body in heads[y] for z in body))
                stack.pop()
                continue
            check(y not in opened, f"the counters depend on each other in a cycle through {y}")
            opened.add(y)
            stack.extend(todo)
    return below


def audit_totalizer(clauses, leaves, threshold):
    """clauses: every clause of the totalizer (one negative literal, on a counter, and one or two positive ones; or
    the unit clause at the root); leaves: the variables it must count. Returns the number of nodes."""
    heads, units, leafset = defaultdict(list), [], set(leaves)
    for c in clauses:
        if len(c) == 1 and c[0] > 0:
            units.append(c[0])
            continue
        neg = [l for l in c if l < 0]
        check(len(neg) == 1 and -neg[0] not in leafset and 2 <= len(c) <= 3, f"not a totalizer clause: {c}")
        heads[-neg[0]].append(tuple(sorted(l for l in c if l > 0)))
    below = leaves_below(heads, leaves)
    nodes = defaultdict(list)                           # the leaves below a node -> its outputs
    for y in heads:
        nodes[below[y]].append(y)
    outputs = {frozenset([v]): [v] for v in leaves}     # the outputs o_1, o_2, ... of each node, in order
    level = {v: 1 for v in leaves}                      # the output o_j -> j
    for u in sorted(nodes, key=len):
        ys = nodes[u]
        kids = {below[z] for y in ys for body in heads[y] for z in body}
        check(len(kids) == 2, f"a node with {len(kids)} children (counters {sorted(ys)[:3]})")
        left, right = sorted(kids, key=min)
        check(not left & right and left | right == u and left in outputs and right in outputs,
              f"a node whose children do not split its leaves (counters {sorted(ys)[:3]})")
        lo, ro = outputs[left], outputs[right]
        lset, rset = set(lo), set(ro)
        for y in ys:
            js = set()
            for body in heads[y]:
                check(all(z in lset or z in rset for z in body) and sum(z in lset for z in body) <= 1
                      and sum(z in rset for z in body) <= 1, f"a clause of counter {y} with other literals: {body}")
                a = next((level[z] - 1 for z in body if z in lset), len(lo))
                b = next((level[z] - 1 for z in body if z in rset), len(ro))
                js.add(a + b + 1)
            check(len(js) == 1, f"counter {y} has clauses for two thresholds")
            level[y] = js.pop()
        byj = sorted(ys, key=level.get)
        m = min(threshold, len(u))
        check([level[y] for y in byj] == list(range(1, m + 1)), f"the outputs of a node are not o_1, ..., o_{m}")
        for j, y in enumerate(byj, 1):
            want = [tuple(sorted(([lo[a]] if a < len(lo) else []) + ([ro[j - 1 - a]] if j - 1 - a < len(ro) else [])))
                    for a in range(len(lo) + 1) if 0 <= j - 1 - a <= len(ro)]
            check(sorted(heads[y]) == sorted(want), f"the clauses of counter {y} are not those of o_{j}")
        outputs[u] = byj
    root = frozenset(leaves)
    # the nodes under the root split its leaves into single ones, so there are len(leaves) - 1 of them: no others
    check(root in outputs and len(nodes) == len(leaves) - 1, "the tree does not count every leaf exactly once")
    check(units == [outputs[root][threshold - 1]], f"the unit clauses {units} are not o_{threshold} of the root")
    return len(nodes)


def read_chains(clauses, firsts, nv_t):
    """clauses: the clauses with a chain variable (one above nv_t); firsts: the pairs (v, w) of the clauses
    x_v | -x_w. Returns the chains, each the list of the pairs (v, w) that it compares, in its order."""
    defined, compared = defaultdict(list), defaultdict(list)
    for c in clauses:
        e = [l for l in c if abs(l) > nv_t]
        x = [l for l in c if abs(l) <= NV]
        check(len(e) + len(x) == len(c), f"a chain clause with a counter: {c}")
        up, down = [l for l in e if l > 0], [-l for l in e if l < 0]
        if len(c) == 2 and len(up) == 1 and len(x) == 1:                    # x_v | e_0 or -x_w | e_0
            defined[up[0]].append((0, x[0]))
        elif len(c) == 3 and len(up) == 1 and len(down) == 1:               # -e_{k-1} | x_v | e_k or ... | -x_w | e_k
            defined[up[0]].append((down[0], x[0]))
        elif len(c) == 3 and len(down) == 1 and len(x) == 2 and x[0] * x[1] < 0:      # -e_{k-1} | x_v | -x_w
            compared[down[0]].append((max(x) - 1, -min(x) - 1))
        else:
            raise AuditError(f"not a chain clause: {c}")
    definition = {}                     # e_k -> (e_{k-1} or 0, v_k, w_k)
    for f, ds in defined.items():
        check(len(ds) == 2, f"chain variable {f} has {len(ds)} clauses that define it, not 2")
        (p, a), (q, b) = sorted(ds, key=lambda d: -d[1])
        check(p == q and a > 0 > b,
              f"the clauses that define chain variable {f} are not x_v | e and -x_w | e after the same variable")
        definition[f] = (p, a - 1, -b - 1)
    check(set(compared) == set(definition), "a chain variable without both its two clauses and its comparison")
    compare = {}
    for e, cs in compared.items():
        check(len(cs) == 1, f"chain variable {e} is followed by {len(cs)} comparisons")
        compare[e] = cs[0]
    successor = {}
    for f, (e, v, w) in definition.items():
        if e:
            check(e in definition, f"chain variable {f} continues variable {e}, which is not defined")
            check(e not in successor, f"chain variable {e} is continued twice")
            check(compare[e] == (v, w), f"chain variable {f} does not continue the comparison after {e}")
            successor[e] = f
    starts = Counter(firsts)
    chains, seen = [], set()
    for h in sorted(f for f, d in definition.items() if d[0] == 0):
        first = definition[h][1:]
        check(starts[first] > 0, f"the chain of variable {h} has no first comparison x_{first[0]} | -x_{first[1]}")
        starts[first] -= 1
        pairs, e = [first], h
        while True:
            check(e not in seen, f"chain variable {e} in two chains")
            seen.add(e)
            pairs.append(compare[e])
            if e not in successor:
                break
            e = successor[e]
        chains.append(pairs)
    check(seen == set(definition), "chain variables in a cycle, outside every chain")
    return chains + [[pair] for pair, n in sorted(starts.items()) for _ in range(n)]     # the chains of one pair


def common_order(chains):
    """one order of all the positions that the chains compare, in which every chain compares its positions; fails
    if there is none (if there are several, any one will do: the smallest vertex first)"""
    after, before, positions = defaultdict(set), Counter(), set()
    for k, pairs in enumerate(chains):
        vs = [v for v, _ in pairs]
        check(len(set(vs)) == len(vs), f"chain {k} compares a position twice: {vs}")
        positions.update(vs)
        for a, b in zip(vs, vs[1:]):
            if b not in after[a]:
                after[a].add(b)
                before[b] += 1
    order, ready = [], sorted(v for v in positions if not before[v])
    while ready:
        v = ready.pop(0)
        order.append(v)
        for w in after[v]:
            before[w] -= 1
            if not before[w]:
                ready.append(w)
        ready.sort()
    check(len(order) == len(positions), "the chains do not visit their positions in one common order")
    return order


def chain_maps(chains, prefix):
    """for each chain, the index in MAPS of a map that sends each position the chain compares to the vertex it is
    compared with, and fixes every other position of the prefix"""
    index = {}
    for i, g in enumerate(MAPS):
        index.setdefault(tuple(g[v] for v in prefix), i)
    found = []
    for k, pairs in enumerate(chains):
        check(all(v != w for v, w in pairs), f"chain {k} compares a position with itself: {pairs}")
        image = dict(pairs)
        i = index.get(tuple(image.get(v, v) for v in prefix))
        if i is None:
            for g in MAPS:
                if all(g[v] == w for v, w in pairs):
                    v = next(v for v in prefix if v not in image and g[v] != v)
                    raise AuditError(f"chain {k} skips position {v} of the prefix, which its map moves: {pairs}")
            raise AuditError(f"no map of the group sends the positions of chain {k} to the vertices it compares them "
                             f"with: {pairs}")
        found.append(i)
    return found


def describe(part, j):
    """part 0: the linear map LINEAR[j]; part 1: the translation TRANSLATIONS[j]"""
    if part:
        return f"the translation z -> z + {point(j)}"
    return f"the linear map z -> {point(CIRCLES[1][j % 14])} {'conj(z)' if j >= 14 else 'z'}"


def audit_symmetry(maps, families):
    """every map in maps (indices in MAPS) sends each family (a set of vertex sets) onto itself: the map is its
    linear map followed by its translation, and the audit checks both of these"""
    parts = sorted({(0, i % len(LINEAR)) for i in maps} | {(1, i // len(LINEAR)) for i in maps})
    for part, j in parts:
        g = (LINEAR, TRANSLATIONS)[part][j]
        for name, family in families.items():
            # g is a permutation of the vertices, so if it maps a family into itself, it maps it onto itself
            check(all(frozenset(map(g.__getitem__, s)) in family for s in family),
                  f"{describe(part, j)}, a part of a chain's map, does not send the {name} clauses onto themselves")


def audit_clauses_a(c, nv, clauses):
    """formula E37_A_c (its number of variables and its clauses). Returns what it found."""
    check(c in ROSETTE_CIRCLES, f"0 with the circle N = {c} is not an independent set, so it is not a rosette")
    edges, dominations, units, total = set(), set(), [], []
    for cl in clauses:
        check(cl, "an empty clause")
        if max(map(abs, cl)) > NV:
            total.append(cl)
            continue
        kind, what = vertex_clause(cl)
        if kind == "edge":
            edges.add(what)
        elif kind == "domination":
            dominations.add(what)
        elif kind == "unit":
            units.append(what)
        else:
            raise AuditError(f"a {kind} clause in formula E37_A_{c}: {cl}")
    check(sorted(units) == sorted([0] + CIRCLES[c]), f"the unit clauses are on {sorted(units)}, not on 0 and the "
          f"points of the circle N = {c}")
    nodes = audit_totalizer(total, list(range(1, NV + 1)), T)
    return {"clauses": len(clauses), "edge clauses": len(edges), "domination clauses": len(dominations),
            "unit clauses": len(units), "totalizer nodes": nodes}


def audit_clauses_b(nv, clauses):
    """formula E37_B (its number of variables and its clauses). Returns what it found."""
    # the chain variables come after the counters, and the first chain's e_0 is the first of them: it is in a clause
    # x_v | e_0, the only kind of clause with two literals, both positive
    heads = [l for c in clauses if len(c) == 2 and c[0] > 0 and c[1] > 0 for l in c if l > NV]
    nv_t = min(heads) - 1 if heads else nv
    edges, dominations, rosettes, firsts, total, chain = set(), set(), set(), [], [], []
    for cl in clauses:
        check(cl, "an empty clause")
        top = max(map(abs, cl))
        if top > nv_t:
            chain.append(cl)
        elif top > NV:
            total.append(cl)
        else:
            kind, what = vertex_clause(cl)
            if kind == "edge":
                edges.add(what)
            elif kind == "domination":
                dominations.add(what)
            elif kind == "no-rosette":
                rosettes.add(what)
            elif kind == "first comparison":
                firsts.append(what)
            else:
                raise AuditError(f"a {kind} clause in formula E37_B: {cl}")
    nodes = audit_totalizer(total, list(range(1, NV + 1)), T)
    chains = read_chains(chain, firsts, nv_t)
    prefix = common_order(chains)
    check(len(prefix) <= PREFIX, f"the chains compare the sets on {len(prefix)} positions, more than {PREFIX}")
    maps = chain_maps(chains, prefix)
    audit_symmetry(maps, {"edge": edges, "domination": dominations, "no-rosette": rosettes})
    return {"clauses": len(clauses), "edge clauses": len(edges), "domination clauses": len(dominations),
            "no-rosette clauses": len(rosettes), "totalizer nodes": nodes, "chains": len(chains),
            "comparisons": sum(map(len, chains)), "maps": len(set(maps)), "prefix": tuple(prefix)}


def audit_formula_a(c, text):
    """formula E37_A_c (its text). Returns what it found."""
    return audit_clauses_a(c, *parse(text))


def audit_formula_b(text):
    """formula E37_B (its text). Returns what it found."""
    return audit_clauses_b(*parse(text))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    print(f"the independent circles: {INDEPENDENT}; the circles of the rosettes: {ROSETTE_CIRCLES}")
    args = {f"E37_A{c}": ["--L", "0", "--rosette", str(c)] for c in ROSETTE_CIRCLES}
    args["E37_B"] = ["--norosette"]
    with tempfile.TemporaryDirectory() as tmp:
        folder = sys.argv[1] if len(sys.argv) > 1 else tmp
        for name, extra in args.items():
            path = os.path.join(folder, name + ".cnf")
            if len(sys.argv) == 1:
                subprocess.run([sys.executable, os.path.join(here, "enum_cert.py"), path, str(T)] + extra,
                               check=True, capture_output=True)
            with open(path, "rb") as fh:
                data = fh.read()
            text = data.decode()
            found = audit_formula_b(text) if name == "E37_B" else audit_formula_a(int(name[5:]), text)
            print(f"{name} (sha256 {hashlib.sha256(data).hexdigest()}): {found}", flush=True)
    print("every clause holds in the intended models")


if __name__ == "__main__":
    main()
