"""Theorem W (notes/winding_lemma.md): an abelian Cayley graph maps to the odd cycle C_{2k+1} if and only if some
character sends every generator into [k/(2k+1), (k+1)/(2k+1)]; for k = 1 this characterises 3-colourability.

Checked here: the theorem on random Cayley graphs of Z/m x Z/n (k = 1 and k = 2), the corollary for groups of
exponent 2 and 4, the distance-graph form against Zhu's list, and the exact certificates that no character of the
group generated by the unit vectors maps them into [1/3, 2/3] over Q(sqrt d) for d = 11, 83, 143, 203 (and, marked
slow, 107 and 167)."""
import copy
import gzip
import itertools
import json
import math
import os
import random
import sys
from fractions import Fraction as Fr

import pytest
from pysat.solvers import Solver

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WDIR = os.path.join(ROOT, "data", "quadratic_planes", "winding")
sys.path.insert(0, WDIR)
from check_w import CertificateError, check  # noqa: E402


def _hom_to_cycle(m, n, S, p):
    """does Cay(Z/m x Z/n, S) map to C_p (p odd >= 3)?  SAT, one-hot colours."""
    N = m * n
    v = lambda x, c: p * x + c + 1
    s = Solver(name="cadical195")
    for x in range(N):
        s.add_clause([v(x, c) for c in range(p)])
    for a in range(m):
        for b in range(n):
            x = a * n + b
            for (da, db) in S:
                y = ((a + da) % m) * n + (b + db) % n
                if x == y:
                    return False
                for c in range(p):
                    for c2 in range(p):
                        if (c2 - c) % p not in (1, p - 1):
                            s.add_clause([-v(x, c), -v(y, c2)])
    return s.solve()


def _character_exists(m, n, S, k):
    """is there a character (j/m, l/n) with xi(s) in [k/(2k+1), (k+1)/(2k+1)] for all s in S?"""
    p = 2 * k + 1
    for j in range(m):
        for l in range(n):
            if all(Fr(k, p) <= (Fr(j * da, m) + Fr(l * db, n)) % 1 <= Fr(k + 1, p) for (da, db) in S):
                return True
    return False


def _random_connection_sets(seed, count):
    rnd = random.Random(seed)
    out = []
    while len(out) < count:
        m = rnd.randint(3, 11); n = rnd.choice([1, 1, 2, 3, 4, 5])
        S = set()
        for _ in range(rnd.randint(1, 3)):
            a, b = rnd.randrange(m), rnd.randrange(n)
            if (a, b) != (0, 0):
                S.add((a, b)); S.add(((-a) % m, (-b) % n))
        if S:
            out.append((m, n, sorted(S)))
    return out


@pytest.mark.parametrize("k", [1, 2])
def test_theorem_w_on_random_cayley_graphs(k):
    p = 2 * k + 1
    agree = {True: 0, False: 0}
    for m, n, S in _random_connection_sets(100 + k, 250):
        a = _hom_to_cycle(m, n, S, p)
        assert a == _character_exists(m, n, S, k), (m, n, S, p)
        agree[a] += 1
    assert agree[True] > 20 and agree[False] > 20


def test_exponent_two_and_four_are_never_three_chromatic():
    """characters of a group of exponent 2 or 4 take values in (1/4)Z/Z, and only 1/2 lies in [1/3, 2/3]."""
    rnd = random.Random(7)
    for (m, n) in [(2, 2), (4, 2), (4, 4)]:
        for _ in range(60):
            S = set()
            for _ in range(rnd.randint(1, 3)):
                a, b = rnd.randrange(m), rnd.randrange(n)
                if (a, b) != (0, 0):
                    S.add((a, b)); S.add(((-a) % m, (-b) % n))
            if not S:
                continue
            S = sorted(S)
            if _hom_to_cycle(m, n, S, 3):
                # 3-colourable, hence bipartite: every generator has a character value 1/2
                assert _character_exists(m, n, S, 1)
                two = Solver(name="cadical195")
                N = m * n
                for a in range(m):
                    for b in range(n):
                        x = a * n + b
                        for (da, db) in S:
                            y = ((a + da) % m) * n + (b + db) % n
                            two.add_clause([x + 1, y + 1]); two.add_clause([-(x + 1), -(y + 1)])
                assert two.solve(), (m, n, S)


def _kappa_third(D):
    cands = {Fr(3 * j + r, 3 * d) for d in D for j in range(d) for r in (1, 2)}
    return any(all(Fr(1, 3) <= (a * d) % 1 <= Fr(2, 3) for d in D) for a in cands)


def _segment_3col(D, N):
    s = Solver(name="cadical195"); v = lambda x, c: 3 * x + c + 1
    for x in range(N):
        s.add_clause([v(x, c) for c in range(3)])
        for d in D:
            if x + d < N:
                for c in range(3):
                    s.add_clause([-v(x, c), -v(x + d, c)])
    return s.solve()


def test_distance_graphs_against_zhu():
    four = []
    for D in itertools.combinations(range(1, 13), 3):
        if math.gcd(math.gcd(D[0], D[1]), D[2]) != 1:
            continue
        k = _kappa_third(D)
        assert k == _segment_3col(D, 12 * max(D) + 60), D
        if not k:
            four.append(D)
    zhu = [D for D in itertools.combinations(range(1, 13), 3) if math.gcd(math.gcd(D[0], D[1]), D[2]) == 1
           and ((D[0], D[1]) == (1, 2) and D[2] % 3 == 0 or D[0] + D[1] == D[2] and (D[0] - D[1]) % 3)]
    assert four == zhu and len(four) > 10


@pytest.mark.parametrize("name, d", [("cert_11_30.json.gz", 11), ("cert_83_510_full.json.gz", 83),
                                     ("cert_143_1740.json.gz", 143), ("cert_203_1530.json.gz", 203)])
def test_certificates(name, d):
    out = check(os.path.join(WDIR, name))
    assert out.startswith(f"VERIFIED: d={d} ")


@pytest.mark.slow
@pytest.mark.parametrize("name, d", [("cert_107_1170.json.gz", 107), ("cert_167_1560.json.gz", 167)])
def test_certificates_slow(name, d):
    out = check(os.path.join(WDIR, name))
    assert out.startswith(f"VERIFIED: d={d} ")


def _first_leaf(t):
    stack = [t]
    while stack:
        x = stack.pop()
        if "leaf" in x:
            return x
        stack.extend(x["kids"].values())


def _mutations(C):
    m = copy.deepcopy(C); _first_leaf(m["tree"])["leaf"][0] = 0.5; yield "float in a leaf", m
    m = copy.deepcopy(C); m["D"] = 30.0; yield "float denominator", m
    m = copy.deepcopy(C); m["units"][0][0] += 1; yield "not a unit vector", m
    m = copy.deepcopy(C); m["relations"][0][0] += 1; yield "not a relation", m
    m = copy.deepcopy(C); m["tree"]["kids"].pop(next(iter(m["tree"]["kids"]))); yield "missing branch value", m
    m = copy.deepcopy(C); leaf = _first_leaf(m["tree"]); leaf["leaf"] = ["0"] * len(leaf["leaf"]); yield "zero leaf", m


def test_checker_rejects_bad_certificates(tmp_path):
    """check_w raises CertificateError (not AssertionError, so python -O checks the same) on each mutation."""
    with gzip.open(os.path.join(WDIR, "cert_11_30.json.gz"), "rt") as fh:
        C = json.load(fh)
    good = tmp_path / "good.json"; good.write_text(json.dumps(C))
    assert check(str(good)).startswith("VERIFIED: d=11 ")
    for name, m in _mutations(C):
        bad = tmp_path / "bad.json"; bad.write_text(json.dumps(m))
        with pytest.raises(CertificateError):
            check(str(bad))
