"""The scan of Theorem W over the real quadratic fields (data/quadratic_planes/winding/scan): for every squarefree
d = 11 (mod 12) below 2000 an exact certificate that no character of the group generated by a finite set of unit
vectors of Q(sqrt d)^2 maps them into [1/3, 2/3], so chi(Q(sqrt d)^2) >= 4; and the table of the certificates
between 2000 and 10000, which stay on the branches of the machines that wrote them (beyond2000.tsv). The three
smallest certificates are checked in the fast tests, all of them in the slow ones."""
import csv
import os
import sys

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WDIR = os.path.join(ROOT, "data", "quadratic_planes", "winding")
sys.path.insert(0, WDIR)
from check_w import check  # noqa: E402

SCAN = os.path.join(WDIR, "scan")


def _scan_certificates():
    if not os.path.isdir(SCAN):
        return []
    return sorted(f for f in os.listdir(SCAN) if f.startswith("cert_") and f.endswith(".json.gz"))


def _squarefree(n):
    k = 2
    while k * k <= n:
        if n % (k * k) == 0:
            return False
        k += 1
    return True


def _targets(lo, hi):
    return [d for d in range(lo, hi) if d % 12 == 11 and _squarefree(d)]


def test_scan_covers_every_d_below_2000_once():
    ds = [int(f.split("_")[1]) for f in _scan_certificates()]
    assert sorted(ds) == _targets(1, 2000)
    assert len(ds) == 155


def test_scan_certificates_small():
    """the three smallest certificates of the scan over d = 11 (mod 12) (the others are marked slow)."""
    files = sorted(_scan_certificates(), key=lambda f: os.path.getsize(os.path.join(SCAN, f)))[:3]
    assert files, "no scan certificates"
    for f in files:
        d = int(f.split("_")[1])
        assert check(os.path.join(SCAN, f)).startswith(f"VERIFIED: d={d} ")


@pytest.mark.slow
@pytest.mark.parametrize("name", _scan_certificates())
def test_scan_certificates_all(name):
    d = int(name.split("_")[1])
    assert check(os.path.join(SCAN, name)).startswith(f"VERIFIED: d={d} ")


def test_beyond_2000_table():
    """one row for every squarefree d = 11 (mod 12) with 2000 < d < 10000; a stored certificate is named after its d
    and D, has a blob id and a sha256, and was accepted by both checkers; the counts are those of the README."""
    with open(os.path.join(SCAN, "beyond2000.tsv"), newline="") as fh:
        rows = list(csv.DictReader(fh, delimiter="\t"))
    assert [int(r["d"]) for r in rows] == _targets(2000, 10000)
    stored = [r for r in rows if r["path"] != "-"]
    for r in stored:
        assert r["path"].endswith(f"/cert_{r['d']}_{r['D']}.json.gz")
        assert len(r["git_blob"]) == 40 and len(r["sha256"]) == 64
        assert r["check_w"] == "VERIFIED" and r["check_w_indep"].startswith("OK")
    once = [int(r["d"]) for r in rows if r["path"] == "-" and r["D"] != "-"]
    none = [int(r["d"]) for r in rows if r["D"] == "-"]
    assert (len(rows), len(stored), sorted(once), len(none)) == (611, 591, [5207, 7763], 18)
