"""Test the key step of Lemma 22 on random finite connection sets.

For Gamma = Z, Z^2, Z x Z/m and random finite S with 1/4 < kappa(S) < 1/2 (so 2 < chi_c < 4 by Theorem W+),
compute kappa exactly, all optimal vertices, and check that every optimal character (vertices, and midpoints /
centroids of optimal vertices that are still optimal) has a positive integer relation among its tight elements
T = {s : xi(s) = kappa}.  As a control, count non-optimal LP vertices whose 'tight set' {s : xi(s) = g} has no
positive relation (these exist, so the test is not vacuous).
"""
import random, sys, json
from fractions import Fraction as Fr
from itertools import combinations
from kappa_exact import (Group, symmetrize, half, kappa, tight_set, positive_relation, check_relation,
                         gval, frac_part)


def random_S(G, k, maxc, rng):
    while True:
        S_half = []
        for _ in range(k):
            x = [rng.randint(-maxc, maxc) for _ in range(G.r)]
            y = rng.randrange(G.m) if G.m > 1 else 0
            S_half.append(tuple(x) + (y,))
        S = symmetrize(G, S_half)
        if any(all(v == 0 for v in s[:G.r]) and s[G.r] % G.m == 0 for s in S):
            continue  # 0 in S
        # generation of Gamma: free parts must generate Z^r together with the torsion; check index via lattice
        if not generates(G, S):
            continue
        return S


def generates(G, S):
    # Gamma = Z^r x Z/m generated by S iff the integer matrix [x_s | y_s] together with (0,...,0,m) has
    # Smith form with all invariant factors 1 (r+1 rows).
    import sympy
    cols = [list(s[:G.r]) + [s[G.r]] for s in S]
    cols.append([0] * G.r + [G.m])
    M = sympy.Matrix(cols).T  # (r+1) x n
    # Gamma' = Z^{r+1} / <cols>; generation iff the lattice spanned by cols is all of Z^{r+1}
    from sympy.matrices.normalforms import smith_normal_form
    snf = smith_normal_form(M, domain=sympy.ZZ)
    d = [snf[i, i] for i in range(min(snf.shape))]
    return len(d) == G.r + 1 and all(abs(v) == 1 for v in d)


def main(seed=1, trials=200):
    rng = random.Random(seed)
    stats = dict(examples=0, opt_points=0, opt_with_rel=0, opt_without_rel=0, torsion_needed=0,
                 control_vertices=0, control_without_rel=0)
    bad = []
    examples = []
    configs = [(1, 1, 3, 9), (1, 1, 4, 12), (2, 1, 3, 3), (2, 1, 4, 2), (1, 2, 3, 6), (1, 3, 3, 6),
               (1, 4, 3, 5), (2, 2, 3, 2), (2, 3, 3, 2)]
    for trial in range(trials):
        r, m, k, maxc = configs[trial % len(configs)]
        G = Group(r, m)
        S = random_S(G, k, maxc, rng)
        kap, opt = kappa(G, S)
        if not (Fr(1, 4) < kap < Fr(1, 2)):
            continue
        stats['examples'] += 1
        Sh = half(G, S)
        pts = list(opt)
        # midpoints and centroids of optimal vertices with same b that remain optimal
        by_b = {}
        for (a, b) in opt:
            by_b.setdefault(b, []).append(a)
        for b, al in by_b.items():
            for a1, a2 in combinations(al, 2):
                mid = tuple(frac_part((x + y) / 2) for x, y in zip(a1, a2))
                if gval(G, Sh, mid, b) == kap:
                    pts.append((mid, b))
            for a1, a2, a3 in combinations(al[:8], 3):
                cen = tuple(frac_part((x + y + z) / 3) for x, y, z in zip(a1, a2, a3))
                if gval(G, Sh, cen, b) == kap:
                    pts.append((cen, b))
        ex = dict(r=r, m=m, S=[list(s) for s in Sh], kappa=str(kap), chi_c=str(1 / kap), n_opt_vertices=len(opt))
        for (a, b) in pts:
            stats['opt_points'] += 1
            T = tight_set(G, S, a, b, kap)
            rel = positive_relation(G, T)
            if rel is None:
                stats['opt_without_rel'] += 1
                bad.append(dict(S=Sh, alpha=[str(x) for x in a], b=b, kappa=str(kap), T=T))
            else:
                assert check_relation(G, rel)
                stats['opt_with_rel'] += 1
                # was torsion needed (free part relation not a relation in Gamma before scaling)?
                if m > 1:
                    tot = (0,) * r + (0,)
                    for t, n in rel.items():
                        for _ in range(n):
                            tot = G.add(tot, t)
                    # rel already scaled; check whether dividing by the torsion order would fail
                    from math import gcd
                    gg = 0
                    for n in rel.values():
                        gg = gcd(gg, n)
                    if gg > 1:
                        red = {t: n // gg for t, n in rel.items()}
                        if not check_relation(G, red):
                            stats['torsion_needed'] += 1
        ex['opt_example'] = dict(alpha=[str(x) for x in opt[0][0]], b=opt[0][1],
                                 T=[list(t) for t in tight_set(G, S, opt[0][0], opt[0][1], kap)])
        examples.append(ex)
        # control: random rational characters that are not optimal; tight set at their own min value
        for _ in range(20):
            den = rng.randint(2, 30)
            a = tuple(Fr(rng.randrange(den), den) for _ in range(r))
            b = rng.randrange(m)
            g = gval(G, Sh, a, b)
            if g == 0 or g >= kap:
                continue
            stats['control_vertices'] += 1
            T = tight_set(G, S, a, b, g)
            if positive_relation(G, T) is None:
                stats['control_without_rel'] += 1
    print(json.dumps(stats, indent=1))
    if bad:
        print('COUNTEREXAMPLES:', bad[:5])
    with open('kappa_examples.json', 'w') as f:
        json.dump(examples, f, indent=1)
    return stats, bad


if __name__ == '__main__':
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 1
    trials = int(sys.argv[2]) if len(sys.argv) > 2 else 200
    main(seed, trials)
