"""quarter_character.py [d D1 D2 ...]: the colouring with values in Z/4 at a place over 2 (exact, integers only).

Let F be a number field with a place v over 2 such that F_v is isomorphic to Q_2(sqrt3). Then K_w = F_v(i) is
Q_2(zeta), with zeta a primitive 12th root of unity; its ring of integers is O = Z_2[zeta], with zeta^4 = zeta^2 - 1;
and the conjugation of K_w over F_v maps zeta to zeta^{-1} = zeta - zeta^3 (here sqrt3 = zeta + zeta^{-1} =
2 zeta - zeta^3 and i = zeta^3). A unit vector (x, y) of F^2 gives z = x + iy in K_w with z zbar = 1. So z is a unit
of O, and its residue r modulo 4O satisfies r rbar = 1 in O/4O.

Part 1 (the finite step of the proof). The ring O/4O = (Z/4)[zeta]/(zeta^4 - zeta^2 + 1) has 256 elements. The script
lists the residues r with r rbar = 1 (there are 24: the 12 powers of zeta, and their products with one more residue)
and every additive map lambda(z_0 + z_1 zeta + z_2 zeta^2 + z_3 zeta^3) = l_0 z_0 + l_1 z_1 + l_2 z_2 + l_3 z_3
(mod 4) that is nonzero on all 24. There are 12, the maps z -> lambda_0(zeta^k z) for lambda_0 = (1, 1, 2, 3) and
k = 0, ..., 11. By Hilbert's Theorem 90 (every norm-one element is y/ybar, and y = pi^k u with pi = 1 - i, a
uniformizer, pi/pibar = -i, u a unit), the residues of the norm-one elements of K_w are those of u/ubar and of
-i u/ubar for the 192 units u of O/4O; the script checks that they are the same 24 residues, so none of them can be
left out.

So c(x, y) = lambda_0(x + iy) is a homomorphism, from the group of points (x, y) of F^2 with x + iy in O (which
contains the group generated by the unit vectors) to Z/4, with c(u) in {1, 2, 3} for every unit vector u.

Part 2 (examples; integers and fractions only). For F = Q(sqrt d) with d = 3 (mod 8), let s be the 2-adic square
root of d/3 with s = 1 (mod 4) (it is computed modulo 2^20). Then sqrt d -> s sqrt3 is an embedding of F into Q_2(sqrt3),
and for x = x1 + x2 sqrt d, y = y1 + y2 sqrt d,
    c(x, y) = x1 + 3 y1 + s (3 y2 - x2)  (mod 4),
which for d = 59 (s = 5 mod 8) is x1 - 5 x2 + 3 y1 + 15 y2 (mod 4). The script evaluates c on every unit vector
((a + b sqrt d)/D, (c + e sqrt d)/D) with the given denominators D (all of them, by brute force; check_theta.units) and
prints how often each value occurs; with no arguments it uses d = 59 and D = 210, 1050. With --q3_11 it evaluates
c on the 27 unit vectors of q3_11.py over Q(sqrt3, sqrt11) (sqrt11 -> t sqrt3 with t^2 = 11/3 in Z_2) and on the
edges of witness_q3_11 and witness_q3_11_cayley.

Part 3 (--q2_3). For Q(sqrt2, sqrt3) the completion at the place over 2 is Q_2(sqrt2, sqrt3), not Q_2(sqrt3): there
O = Z_2[zeta_24], O/4O has 65536 residues, 384 of them with r rbar = 1, and no additive map O/4O -> Z/4 is nonzero on
all of them (a few seconds).

Consequence (paper, the remark after Proposition [quarter character]): over such a field kappa(U) >= 1/4 for every
finite set U of unit vectors, since c/4 is a character of ZU at distance at least 1/4 from Z on U. With the certificate
cert59_1050_open_4.json.gz, kappa(U_1050) = 1/4 over Q(sqrt59)."""
import itertools, os, sys
from fractions import Fraction as Fr

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

# ---------- Part 1: O/4O ----------
M4 = 4


def mul(a, b, m):
    """product in Z[zeta]/(m), zeta^4 = zeta^2 - 1, elements as 4-tuples of coefficients"""
    c = [0] * 7
    for i in range(4):
        if a[i]:
            for j in range(4):
                c[i + j] += a[i] * b[j]
    for t in (6, 5, 4):
        v = c[t]
        c[t] = 0
        c[t - 2] += v
        c[t - 4] -= v
    return tuple(x % m for x in c[:4])


def zpow(k, m):
    r = (1, 0, 0, 0)
    for _ in range(k % 12):
        r = mul(r, (0, 1, 0, 0), m)
    return r


def bar(a, m):
    """the conjugation over Q_2(sqrt3): zeta^k -> zeta^{-k}"""
    r = [0, 0, 0, 0]
    for k in range(4):
        t = zpow(-k, m)
        r = [(x + a[k] * y) % m for x, y in zip(r, t)]
    return tuple(r)


def lam(l, z, m=M4):
    return sum(x * y for x, y in zip(l, z)) % m


L0 = (1, 1, 2, 3)


def part1():
    one = (1, 0, 0, 0)
    assert mul((0, 1, 0, 0), (0, 1, 0, M4 - 1), M4) == one            # zeta^{-1} = zeta - zeta^3
    assert zpow(12, 16) == one and zpow(6, 16) == (15, 0, 0, 0)        # zeta has order 12 (checked mod 16)
    assert mul((0, 2, 0, 15), (0, 2, 0, 15), 16) == (3, 0, 0, 0)       # (2 zeta - zeta^3)^2 = 3
    assert zpow(3, 16) == mul(zpow(3, 16), one, 16) and mul(zpow(3, 16), zpow(3, 16), 16) == (15, 0, 0, 0)  # i^2 = -1
    assert bar((0, 2, 0, 15), 16) == (0, 2, 0, 15) and bar(zpow(3, 16), 16) == zpow(9, 16)  # bar fixes sqrt3, i -> -i
    els = list(itertools.product(range(M4), repeat=4))
    N1 = sorted(r for r in els if mul(r, bar(r, M4), M4) == one)
    inv = {}
    for a in els:
        for b in els:
            if mul(a, b, M4) == one:
                inv[a] = b
    units = sorted(inv)
    mi = tuple((-x) % M4 for x in zpow(3, M4))
    R = set()
    for u in units:
        q = mul(u, inv[bar(u, M4)], M4)
        R.add(q)
        R.add(mul(mi, q, M4))
    mu = sorted({zpow(k, M4) for k in range(12)})
    chars = sorted(l for l in els if all(lam(l, r) for r in N1))
    rot = sorted({tuple(lam(L0, mul(zpow(k, M4), e, M4)) for e in ((1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0),
                                                                     (0, 0, 0, 1))) for k in range(12)})
    print(f'O/4O: {len(els)} residues, {len(units)} units; {len(N1)} residues r with r rbar = 1; the residues of '
          f'u/ubar and -i u/ubar (u a unit): {len(R)}, the same set: {R == set(N1)}; the 12 powers of zeta among '
          f'them: {set(mu) <= set(N1) and len(mu) == 12}')
    print(f'additive maps lambda: O/4O -> Z/4 nonzero on all {len(N1)}: {len(chars)}; they are the maps '
          f'z -> lambda_0(zeta^k z), lambda_0 = {L0}: {chars == rot}')
    one2i = (1, 0, 0, 2)                                     # 1 + 2i, i = zeta^3
    listed = {zpow(k, M4) for k in range(12)} | {mul(one2i, zpow(k, M4), M4) for k in range(12)}
    vals = [lam(L0, zpow(k, M4)) for k in range(12)]
    vals2 = [lam(L0, mul(one2i, zpow(k, M4), M4)) for k in range(12)]
    kernel_ok = listed == set(N1) and len(listed) == 24
    neg_ok = all((a + b) % 4 == 0 for a, b in zip(vals, vals2))
    print(f'the 24 residues are zeta^k and (1 + 2i) zeta^k, k = 0, ..., 11: {kernel_ok}')
    print(f'lambda_0(zeta^k), k = 0, ..., 11: {vals}; lambda_0((1 + 2i) zeta^k) = -lambda_0(zeta^k): {neg_ok}')
    return len(N1), len(units), R == set(N1), chars, chars == rot, kernel_ok and neg_ok


# ---------- Part 2: examples ----------
NP = 20
MOD = 2 ** NP


def sqrt2adic(q):
    """the square root s = 1 (mod 4) of q = 1 (mod 8) in Z_2, modulo 2^(NP - 1)"""
    assert q % 8 == 1
    s = 1
    for m in range(3, NP + 1):
        if (s * s - q) % (2 ** m):
            s += 2 ** (m - 2)
    assert (s * s - q) % (2 ** (NP - 1)) == 0
    if s % 4 == 3:
        s = MOD - s
    return s % MOD


def value(coords, den, sqrt_images):
    """c(x, y) for x = sum coords[0][j] w_j / den, y = sum coords[1][j] w_j / den, where w_j are basis elements of F
    with 2-adic images sqrt_images[j] (elements of O modulo 2^NP, in the basis 1, zeta, zeta^2, zeta^3)."""
    I = (0, 0, 0, 1)
    Dz = (0, 0, 0, 0)
    for j, w in enumerate(sqrt_images):
        Dz = tuple((p + q) % MOD for p, q in zip(Dz, tuple(coords[0][j] * t for t in w)))
        Dz = tuple((p + q) % MOD for p, q in zip(Dz, mul(I, tuple(coords[1][j] * t for t in w), MOD)))
    k = (den & -den).bit_length() - 1
    odd = den >> k
    Dz = tuple(x * pow(odd, -1, MOD) % MOD for x in Dz)
    assert all(x % 2 ** k == 0 for x in Dz), 'x + iy is not 2-integral'
    z = tuple((x >> k) % 4 for x in Dz)            # precision NP - 1 - k >= 2
    return lam(L0, z)


SQ3 = (0, 2, 0, MOD - 1)        # 2 zeta - zeta^3


def quad_images(d):
    assert d % 8 == 3
    s = sqrt2adic(d * pow(3, -1, MOD) % MOD)
    return [(1, 0, 0, 0), tuple(s * t % MOD for t in SQ3)], s


def part2_quadratic(d, Ds):
    from check_theta import units
    imgs, s = quad_images(d)
    out = {}
    for D in Ds:
        U = units(d, D)
        cnt = {0: 0, 1: 0, 2: 0, 3: 0}
        for a, b, c, e in U:
            v = value(((a, b), (c, e)), D, imgs)
            cnt[v] += 1
            # the closed formula c = x1 + 3 y1 + s (3 y2 - x2) mod 4, with s replaced by s mod 8
            num = a + 3 * c + (s % 8) * (3 * e - b)
            g = Fr(num, D)
            assert g.denominator % 2 == 1 and (g.numerator * pow(g.denominator, -1, 4)) % 4 == v
        out[D] = cnt
        print(f'Q(sqrt{d}), s = {s % 8} mod 8: the {len(U)} unit vectors with denominator {D}: c = 1, 2, 3 on '
              f'{cnt[1]}, {cnt[2]}, {cnt[3]} of them, c = 0 on {cnt[0]}')
    return out


def part2_q3_11():
    import gzip, json
    import q3_11
    t = sqrt2adic(11 * pow(3, -1, MOD) % MOD)
    S3 = SQ3
    S11 = tuple(t * x % MOD for x in SQ3)
    S33 = (3 * t % MOD, 0, 0, 0)            # sqrt3 sqrt11 = t sqrt3^2 = 3t
    imgs = [(1, 0, 0, 0), S3, S11, S33]
    res = {}
    cnt = {0: 0, 1: 0, 2: 0, 3: 0}
    for w in q3_11.units_311():
        cnt[value((tuple(w[:4]), tuple(w[4:])), q3_11.D, imgs)] += 1
    res['27'] = cnt
    print(f'Q(sqrt3, sqrt11), t = {t % 8} mod 8: the 27 unit vectors of q3_11.py: c = 1, 2, 3 on {cnt[1]}, '
          f'{cnt[2]}, {cnt[3]} of them, c = 0 on {cnt[0]}')
    for name in ('witness_q3_11', 'witness_q3_11_cayley'):
        fw = os.path.join(HERE, '..', 'finite_witness', name + '.json.gz')
        if not os.path.exists(fw):
            continue
        with gzip.open(fw, 'rt') as fh:
            W = json.load(fh)
        D = W['denominator']
        P = W['points']
        cnt = {0: 0, 1: 0, 2: 0, 3: 0}
        for i, j in W['edges']:
            dx = [p - q for p, q in zip(P[j], P[i])]
            cnt[value((tuple(dx[:4]), tuple(dx[4:])), D, imgs)] += 1
        res[name] = cnt
        print(f'Q(sqrt3, sqrt11): the {len(W["edges"])} edges of {name} (y - x for each edge x y): c = 1, 2, 3 '
              f'on {cnt[1]}, {cnt[2]}, {cnt[3]}, c = 0 on {cnt[0]}')
    return res


def part3_q2_3():
    """F_v = Q_2(sqrt2, sqrt3) (the field Q(sqrt2, sqrt3)): K_w = Q_2(zeta_24), O = Z_2[zeta_24], zeta^8 = zeta^4 - 1,
    conjugation zeta -> zeta^{-1}. Counts the residues r of O/4O with r rbar = 1 and the additive maps O/4O -> Z/4 that
    are nonzero on all of them (none: the proposition has no analogue at this place, at level 4)."""
    n = 8

    def red(c):
        c = list(c)
        for t in range(len(c) - 1, n - 1, -1):
            v = c[t]
            c[t] = 0
            c[t - 4] += v
            c[t - 8] -= v
        return tuple(x % 4 for x in c[:n])

    def mul8(a, b):
        c = [0] * (2 * n - 1)
        for i in range(n):
            if a[i]:
                for j in range(n):
                    c[i + j] += a[i] * b[j]
        return red(c)

    def zp(k):
        c = [0] * 24
        c[k % 24] = 1
        return red(c)
    bars = [zp(-k) for k in range(n)]

    def bar8(a):
        r = [0] * n
        for k in range(n):
            if a[k]:
                r = [(x + a[k] * y) % 4 for x, y in zip(r, bars[k])]
        return tuple(r)
    assert zp(12) == (3, 0, 0, 0, 0, 0, 0, 0) and mul8(zp(5), zp(19)) == (1, 0, 0, 0, 0, 0, 0, 0)
    one = (1,) + (0,) * (n - 1)
    N1 = [r for r in itertools.product(range(4), repeat=n) if mul8(r, bar8(r)) == one]
    good = 0
    for l in itertools.product(range(4), repeat=n):
        if all(sum(x * y for x, y in zip(l, r)) % 4 for r in N1):
            good += 1
    print(f'Q_2(sqrt2, sqrt3): O/4O has {4 ** n} residues, {len(N1)} with r rbar = 1; additive maps O/4O -> Z/4 '
          f'nonzero on all of them: {good}')
    return len(N1), good


if __name__ == '__main__':
    part1()
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    if '--q3_11' in sys.argv:
        part2_q3_11()
    elif '--q2_3' in sys.argv:
        part3_q2_3()
    elif args:
        part2_quadratic(int(args[0]), [int(x) for x in args[1:]])
    else:
        part2_quadratic(59, [210, 1050])
