"""The plane over Q(sqrt3, sqrt5) has no proper 3-colouring, so 4 <= chi(Q(sqrt3, sqrt5)^2) <= 5.

tau = (2 + i sqrt5)/3 is a unit vector, so 1/3 = tau + conj(tau) - 1 is a sum of unit vectors, and
with w = e^{i pi/3}
    (1 + w)/3 = tau + conj(tau) - 1 + w tau + w conj(tau) - w,
of squared length 1/3. A unit rhombus whose long diagonal is sqrt3 u forces its two tips to share a
colour in every 3-colouring. Chaining the six rhombi with diagonals sqrt3 times these unit vectors
joins the origin to sqrt3 (1 + w)/3 = e^{i pi/6}, a unit vector: data/chain35.json, 19 vertices.

The upper bound: 3 and 5 are squares modulo 11, so 11 splits completely in Q(sqrt3, sqrt5); a place
over 11 has residue field F_11 with 11 = 3 (mod 4), and reduction there gives chi <= chi(F_11^2) = 5
(Madore, Cor. 3.4). Whether the plane is 5-chromatic is open: it is the smallest case left of
Voronov's question (Polymath16, 2021) on fields generated by two square roots of primes.
"""
import sys, os, json
from fractions import Fraction as Fr
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from pysat.solvers import Solver

from hn.certify import exact_edges
from hn.field import Field
from hn.geometry import Point

F = Field((3, 5))
r = F.rational
S3, S5 = F.sqrt(3), F.sqrt(5)
DATA = os.path.join(os.path.dirname(__file__), "..", "data", "chain35.json")


def mul(a, b):
    return Point(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x)


def colourable(n, edges, k):
    X = lambda v, c: 1 + v * k + c
    s = Solver(name="cd19")
    for v in range(n):
        s.add_clause([X(v, c) for c in range(k)])
    for a, b in edges:
        for c in range(k):
            s.add_clause([-X(a, c), -X(b, c)])
    res = s.solve()
    s.delete()
    return res


def test_one_third_is_a_sum_of_six_unit_vectors_of_squared_length_one_third():
    tau = Point(r(Fr(2, 3)), S5 * r(Fr(1, 3)))
    taub = Point(tau.x, -tau.y)
    w = Point(r(Fr(1, 2)), S3 * r(Fr(1, 2)))
    one = Point(r(1), r(0))
    us = [tau, taub, Point(-one.x, -one.y), mul(w, tau), mul(w, taub), Point(-w.x, -w.y)]
    for u in us:
        assert u.x * u.x + u.y * u.y == F.one()
    total = Point(sum((u.x for u in us), F.zero()), sum((u.y for u in us), F.zero()))
    assert total == Point(r(Fr(1, 2)), S3 * r(Fr(1, 6)))          # (1 + w)/3
    end = Point(S3 * total.x, S3 * total.y)
    assert end.x * end.x + end.y * end.y == F.one()                # sqrt3 (1 + w)/3 is a unit vector


def test_the_chain_has_no_proper_3_colouring():
    d = json.load(open(DATA))
    assert d["field_generators"] == [3, 5]
    pts = [Point(F.element([Fr(a, b) for a, b in xy[0]]), F.element([Fr(a, b) for a, b in xy[1]]))
           for xy in d["points"]]
    assert len(pts) == len(set(pts)) == 19
    edges = exact_edges(pts)
    assert len(edges) == 31
    assert not colourable(len(pts), edges, 3)
    assert colourable(len(pts), edges, 4)


def test_eleven_splits_completely():
    assert pow(3, 5, 11) == 1 and pow(5, 5, 11) == 1                # 3 and 5 are squares mod 11
    assert 11 % 4 == 3                                              # -1 is not a square in F_11
