"""The 2-adic 4-colouring of the Moser field.

Every point of the plane with complex coordinate in K = Q(sqrt-3, sqrt-11) is coloured through the
place of K above 2 where sqrt33 is a 2-adic integer s (s^2 = 33, s = 1 mod 4; the other root gives the
other place and works as well): with omega = (1 + sqrt-3)/2,

    z = a + b sqrt33 + c sqrt-3 + d sqrt-11   maps to   alpha + beta omega in Q_2(omega),
    colour(z) = floor(4 * frac_2((alpha + 2 beta)/4)),

frac_2 the 2-adic fractional part.  (A configuration drawn in i K, as Exoo and Ismailescu's is, is
coloured through -i z; a quarter turn keeps every distance.)  For a unit vector u (u ubar = 1), u is a norm-one element of the
unramified extension Q_2(omega), and phi(u) = frac_2((alpha + 2 beta)/4) lies in {1/4, 1/2, 3/4}: a
unit step always changes the colour.  This script checks that claim on every unit vector of the
given module files and on the edges of their graphs, in exact rational arithmetic.

usage: python3 moser2adic.py <file.json> ...   (fields generated by 3 and 11)"""
import sys, os, json
from fractions import Fraction as Fr
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
exec(open(os.path.join(HERE, "gate.py")).read().split("def gate(g, label):")[0])
from hn.adelic import moser_phi
tot_u = tot_e = 0
for path in sys.argv[1:]:
    dd = json.load(open(path)); F = Field(tuple(dd["field_generators"]))
    assert set(F.gens) <= {3, 11}, "the Moser field only"
    mk = lambda xy: Point(F.element([Fr(p, q) for p, q in xy[0]]), F.element([Fr(p, q) for p, q in xy[1]]))
    units = [mk(xy) for xy in dd.get("units", [])]
    P = [mk(xy) for xy in dd.get("points", [])]
    E = list(build_graph(P).edges()) if len(P) > 1 else []
    for sgn in (1, -1):
        vals = {moser_phi(u, sgn) for u in units}
        assert vals <= {Fr(1, 4), Fr(1, 2), Fr(3, 4)}, (path, vals)
        col = [int(4 * moser_phi(p, sgn)) for p in P]
        bad = sum(1 for i, j in E if col[i] == col[j])
        assert bad == 0, (path, bad)
    tot_u += len(units); tot_e += len(E)
    print(f"{os.path.basename(path)}: {len(units)} unit vectors, phi in {sorted(str(v) for v in vals)}; {len(P)} points, {len(E)} edges, 0 monochromatic (both places above 2)")
print(f"all checked: {tot_u} unit vectors, {tot_e} edges")
