"""Unit vectors generated by rotations of a field, written as a module file for the circular gates.

Units: R . u0 for every word R = omega^a sigma^b lambda^c rho7^d (exponents in the given ranges),
u0 = (1, 0), exact arithmetic in the multiquadratic field of the coordinates.  In the field
Q(sqrt3, sqrt11) every such module has rank at most 4 (x + iy lies in Q(sqrt-3, sqrt-11)).

usage: python3 rotunits.py <gens e.g. 3,11> <sigma range> <lambda range> <rho7 range> <kappa range> [<tau range>] <out.json>

tau = (119 + 3 sqrt-247)/128, the rotation of the sqrt247 spindle (needs 247 among the generators);
with it the modules live in Q(sqrt-3, sqrt-11, sqrt-247) and have rank at most 8."""
import sys, json, os, itertools
from fractions import Fraction as Fr
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
exec(open(os.path.join(HERE, "gate.py")).read().split("def gate(g, label):")[0])
gens = tuple(int(x) for x in sys.argv[1].split(",")); F = Field(gens)
rs, rl, rr, rk = (int(x) for x in sys.argv[2:6])
rt = int(sys.argv[6]) if len(sys.argv) > 7 else 0; OUT = sys.argv[-1]
def el(rad):
    c = [Fr(0)] * F.dim
    for m in range(F.dim):
        if F._prod[m] in rad: c[m] = Fr(rad[F._prod[m]])
    return F.element(c)
def rot(cos_c, sin_rad):
    cth = F.rational(cos_c); sth = el(sin_rad)
    return lambda p: Point(p.x * cth - p.y * sth, p.x * sth + p.y * cth)
inv = lambda cos_c, sin_rad: rot(cos_c, {q: -a for q, a in sin_rad.items()})
R = {"omega": (Fr(1, 2), {3: Fr(1, 2)}), "sigma": (Fr(5, 6), {11: Fr(1, 6)}),
     "lambda": (Fr(49, 50), {11: Fr(3, 50)}), "rho7": (Fr(1, 7), {3: Fr(4, 7)}), "kappa": (Fr(-11, 14), {3: Fr(5, 14)}),
     "tau": (Fr(119, 128), {247: Fr(3, 128)})}
def power(name, k, p):
    c, s = R[name]; f = rot(c, s) if k >= 0 else inv(c, s)
    for _ in range(abs(k)): p = f(p)
    return p
u0 = Point(F.rational(1), F.rational(0))
key = lambda p: (round(p.fx, 9), round(p.fy, 9))
U = {}
for b, c, d, e, f in itertools.product(range(-rs, rs + 1), range(-rl, rl + 1), range(-rr, rr + 1), range(-rk, rk + 1), range(-rt, rt + 1)):
    p = power("sigma", b, u0); p = power("lambda", c, p); p = power("rho7", d, p); p = power("kappa", e, p)
    if f: p = power("tau", f, p)
    for a in range(6):
        U.setdefault(key(p), p); p = rot(*R["omega"])(p)
    for q in list(U.values())[-6:]:
        mq = Point(-q.x, -q.y); U.setdefault(key(mq), mq)
enc = lambda u: [[[x.numerator, x.denominator] for x in u.x.c], [[x.numerator, x.denominator] for x in u.y.c]]
json.dump({"field_generators": list(gens), "units": [enc(u) for u in U.values()], "points": [enc(Point(F.rational(0), F.rational(0)))],
           "A": 0, "B": 0, "note": f"rotation units sigma {rs} lambda {rl} rho7 {rr} kappa {rk} tau {rt}"}, open(OUT, "w"))
print(f"{len(U)} unit vectors written to {OUT}")
