"""de Grey's 1581-vertex 5-chromatic graph, rebuilt from the published recipe.

Source: Aubrey D.N.J. de Grey, "The chromatic number of the plane is at least 5",
arXiv:1804.02385 / Geombinatorics 28 (2018).  The construction there is:

    S    39 explicit points (section 5.1 of the paper, transcribed below)
    Sa   every image of S under the 12-element group generated by the
         60-degree rotation and reflection in the x-axis
    Sb   Sa rotated anticlockwise about the origin by 2*arcsin(1/4)
    Y    Sa u Sb, with the two vertices (1/3, 0) and (-1/3, 0) deleted
    Ya   Y rotated anticlockwise about (-2, 0) by pi/2 + arcsin(1/8)
    Yb   Y rotated anticlockwise about (-2, 0) by pi/2 - arcsin(1/8)
    G    Ya u Yb        -- 1581 vertices, and not 4-colourable

S itself lies in Q(sqrt3, sqrt11).  The rotation by 2*arcsin(1/4) has sine
sqrt(15)/8 and the two about (-2,0) have sine 3*sqrt(7)/8, so G needs
Q(sqrt3, sqrt5, sqrt7, sqrt11) -- which is why searching inside Q(sqrt3,
sqrt11) could never have found it.

Nothing here is taken on faith: `hn.certify` re-derives every edge from these
coordinates in O(n^2) and drat-trim checks the proof that no 4-colouring
exists.  Transcription errors would show up as a wrong vertex count or a
graph that turns out to be 4-colourable.
"""

from __future__ import annotations

from fractions import Fraction as Fr
from typing import Dict, List, Sequence

from .field import Field
from .geometry import DEGREY_FIELD, Point, Rotation, _rot60
from .graph import UnitDistanceGraph, build_graph

__all__ = ["S_POINTS", "build_S", "build_Sa", "build_Sb", "build_Y", "build_G"]


# Each coordinate is written as {radicand: rational coefficient}, so that
# {1: Fr(13,12), 33: Fr(1,12)} means (13 + sqrt(33))/12.  Note 1/sqrt(12) is
# sqrt(3)/6 and 1/sqrt(3) is sqrt(3)/3.
S_POINTS: List[tuple] = [
    ({}, {}),                                                     # (0, 0)
    ({1: Fr(1, 3)}, {}),                                          # (1/3, 0)
    ({1: Fr(1)}, {}),                                             # (1, 0)
    ({1: Fr(2)}, {}),                                             # (2, 0)
    ({33: Fr(1, 6), 1: Fr(-1, 2)}, {}),                           # ((r33-3)/6, 0)
    ({1: Fr(1, 2)}, {3: Fr(1, 6)}),                               # (1/2, 1/r12)
    ({1: Fr(1)}, {3: Fr(1, 3)}),                                  # (1, 1/r3)
    ({1: Fr(3, 2)}, {3: Fr(1, 2)}),                               # (3/2, r3/2)
    ({1: Fr(7, 6)}, {11: Fr(1, 6)}),                              # (7/6, r11/6)
    ({1: Fr(1, 6)}, {3: Fr(1, 3), 11: Fr(-1, 6)}),                # (1/6, (r12-r11)/6)
    ({1: Fr(5, 6)}, {3: Fr(1, 3), 11: Fr(-1, 6)}),                # (5/6, (r12-r11)/6)
    ({1: Fr(2, 3)}, {11: Fr(1, 6), 3: Fr(-1, 6)}),                # (2/3, (r11-r3)/6)
    ({1: Fr(2, 3)}, {3: Fr(1, 2), 11: Fr(-1, 6)}),                # (2/3, (3r3-r11)/6)
    ({33: Fr(1, 6)}, {3: Fr(1, 6)}),                              # (r33/6, 1/r12)
    ({33: Fr(1, 6), 1: Fr(1, 2)}, {3: Fr(1, 3)}),                 # ((r33+3)/6, 1/r3)
    ({33: Fr(1, 6), 1: Fr(1, 6)}, {3: Fr(1, 2), 11: Fr(-1, 6)}),
    ({33: Fr(1, 6), 1: Fr(-1, 6)}, {3: Fr(1, 2), 11: Fr(-1, 6)}),
    ({33: Fr(1, 6), 1: Fr(1, 6)}, {11: Fr(1, 6), 3: Fr(-1, 6)}),
    ({33: Fr(1, 6), 1: Fr(-1, 6)}, {11: Fr(1, 6), 3: Fr(-1, 6)}),
    ({33: Fr(1, 6), 1: Fr(-1, 3)}, {3: Fr(1, 3), 11: Fr(-1, 6)}),
    ({33: Fr(1, 6), 1: Fr(-2, 3)}, {3: Fr(1, 3), 11: Fr(-1, 6)}),
    ({33: Fr(1, 12), 1: Fr(13, 12)}, {11: Fr(1, 12), 3: Fr(-1, 12)}),
    ({33: Fr(1, 12), 1: Fr(11, 12)}, {3: Fr(1, 12), 11: Fr(1, 12)}),
    ({33: Fr(1, 12), 1: Fr(3, 4)}, {11: Fr(1, 4), 3: Fr(-1, 4)}),
    ({33: Fr(1, 12), 1: Fr(3, 4)}, {3: Fr(1, 4), 11: Fr(1, 12)}),
    ({33: Fr(1, 12), 1: Fr(7, 12)}, {3: Fr(1, 12), 11: Fr(1, 12)}),
    ({33: Fr(1, 12), 1: Fr(7, 12)}, {3: Fr(1, 4), 11: Fr(-1, 12)}),
    ({33: Fr(1, 12), 1: Fr(5, 12)}, {3: Fr(5, 12), 11: Fr(-1, 12)}),
    ({33: Fr(1, 12), 1: Fr(5, 12)}, {11: Fr(1, 12), 3: Fr(-1, 12)}),
    ({33: Fr(1, 12), 1: Fr(1, 4)}, {11: Fr(1, 4), 3: Fr(-5, 12)}),
    ({33: Fr(1, 12), 1: Fr(1, 4)}, {3: Fr(1, 12), 11: Fr(1, 12)}),
    ({33: Fr(1, 12), 1: Fr(1, 4)}, {3: Fr(1, 4), 11: Fr(-1, 12)}),
    ({33: Fr(1, 12), 1: Fr(1, 12)}, {11: Fr(1, 12), 3: Fr(-1, 12)}),
    ({33: Fr(1, 12), 1: Fr(-1, 12)}, {3: Fr(1, 4), 11: Fr(-1, 12)}),
    ({33: Fr(1, 12), 1: Fr(-1, 4)}, {11: Fr(1, 12), 3: Fr(-1, 12)}),
    ({1: Fr(5, 4), 33: Fr(-1, 12)}, {11: Fr(1, 4), 3: Fr(-1, 4)}),
    ({1: Fr(5, 4), 33: Fr(-1, 12)}, {3: Fr(7, 12), 11: Fr(-1, 4)}),
    ({1: Fr(13, 12), 33: Fr(-1, 12)}, {3: Fr(1, 4), 11: Fr(-1, 12)}),
    ({1: Fr(11, 12), 33: Fr(-1, 12)}, {11: Fr(1, 12), 3: Fr(-1, 12)}),
]


def _coord(spec: Dict[int, Fr], field: Field):
    out = field.zero()
    for radicand, coeff in spec.items():
        term = field.rational(coeff) if radicand == 1 else field.sqrt(radicand) * field.rational(coeff)
        out = out + term
    return out


def build_S(field: Field = DEGREY_FIELD) -> List[Point]:
    return [Point(_coord(x, field), _coord(y, field)) for x, y in S_POINTS]


def build_Sa(field: Field = DEGREY_FIELD) -> List[Point]:
    """Every image of S under the 60-degree rotation and reflection in y."""
    rot60 = _rot60(field)
    seen, out = set(), []
    for p in build_S(field):
        for base in (p, Point(p.x, -p.y)):
            q = base
            for _ in range(6):
                if q not in seen:
                    seen.add(q)
                    out.append(q)
                q = rot60(q)
    return out


def _rot_2asin_quarter(field: Field) -> Rotation:
    """2*arcsin(1/4): cos 7/8, sin sqrt(15)/8."""
    return Rotation(field.rational(Fr(7, 8)), field.sqrt(15) * field.rational(Fr(1, 8)))


def _rot_half_pi_pm(field: Field, sign: int) -> Rotation:
    """pi/2 +- arcsin(1/8): cos -+1/8, sin 3*sqrt(7)/8."""
    return Rotation(field.rational(Fr(-sign, 8)), field.sqrt(7) * field.rational(Fr(3, 8)))


def build_Sb(field: Field = DEGREY_FIELD) -> List[Point]:
    rot = _rot_2asin_quarter(field)
    return [rot(p) for p in build_Sa(field)]


def build_Y(field: Field = DEGREY_FIELD) -> List[Point]:
    """Sa u Sb, less the two vertices (1/3, 0) and (-1/3, 0)."""
    drop = {
        Point(field.rational(Fr(1, 3)), field.zero()),
        Point(field.rational(Fr(-1, 3)), field.zero()),
    }
    seen, out = set(), []
    for p in build_Sa(field) + build_Sb(field):
        if p in drop or p in seen:
            continue
        seen.add(p)
        out.append(p)
    return out


def build_G(field: Field = DEGREY_FIELD, as_graph: bool = True):
    """Ya u Yb: the 1581-vertex graph."""
    pivot = Point(field.rational(-2), field.zero())
    Y = build_Y(field)
    pts, seen = [], set()
    for sign in (+1, -1):
        turn = _rot_half_pi_pm(field, sign).about(pivot)
        for p in Y:
            q = turn(p)
            if q not in seen:
                seen.add(q)
                pts.append(q)
    return build_graph(pts) if as_graph else pts
