"""Homomorphism colourings: the most structural colouring a graph can have.

Let M be the Z-module generated by a unit-distance graph's EDGE vectors. A
group homomorphism

    phi : M -> Z/n   with   phi(d) != 0 for every edge vector d

is itself a proper n-colouring, c(p) = phi(p): adjacent points differ by an
edge vector, so their colours differ. It is constant on cosets of ker phi, so
it is as regular as a colouring gets -- the opposite of the rigidity that a
small rainbow-forcing set needs.

Two things follow, and both are useful.

A NECESSARY CONDITION. If such a phi exists for n = 5, every subset of M is
5-colourable and no graph built from those steps can ever be 6-chromatic. So
a candidate can be screened in seconds, before any colouring search.

AN EXPLANATION. de Grey's G, his Sa, and the whole three-hexagon gadget family
all admit one at n = 5 -- found by SAT in under a second each. Their
5-colourings are coset colourings, which is why every rigidity measurement in
this package came back flat: a coset colouring can be composed with the
automorphisms of Z/n and with any translation of the module, so the colour
classes move freely and the forcing sets are enormous.

WHERE TO LOOK. phi must avoid every edge vector, so writing D for their images
in M/5M, a phi exists unless the hyperplanes d-perp for d in D cover the whole
dual. Covering needs D to meet every hyperplane -- a blocking set -- and the
smallest is a projective line, q + 1 = SIX points. So six unit vectors whose
reductions represent the six points of a projective line over Z/5 rule out
every homomorphism at once. That is a finite, checkable design target.

ONE CAVEAT, stated because it bounds what the tool proves. The search embeds
M in Z^d by clearing a common denominator and looks for phi defined on that
Z^d. Every phi it FINDS is genuine, since restriction is a homomorphism. A
"none found" is only a statement about that embedding unless M is a direct
summand, so this module screens IN rather than screens OUT.
"""

from __future__ import annotations

from fractions import Fraction
from math import gcd
from typing import List, Optional, Sequence, Tuple

__all__ = ["edge_vectors", "has_homomorphism", "screen", "minimum_blocking_set"]


def _coords(e) -> Tuple[Fraction, ...]:
    """Full rational coordinates, including a real extension's radical part.

    `.c` on a RealExtElement returns only its base component, so using it here
    silently truncated the edge vectors of anything living over sqrt(v) and
    reported a homomorphism search on the wrong module. Both halves are needed.
    """
    a = getattr(e, "a", None)
    b = getattr(e, "b", None)
    if a is not None and b is not None:
        return tuple(a.c) + tuple(b.c)
    return tuple(e.c)


def edge_vectors(graph) -> List[Tuple[int, ...]]:
    """Distinct edge vectors as integer tuples, over a common denominator."""
    out = set()
    for a, b in graph.edges():
        d = (graph.vertices[b].x - graph.vertices[a].x,
             graph.vertices[b].y - graph.vertices[a].y)
        out.add(_coords(d[0]) + _coords(d[1]))
    den = 1
    for v in out:
        for q in v:
            den = den * Fraction(q).denominator // gcd(den,
                                                       Fraction(q).denominator)
    ints = {tuple(int(Fraction(q) * den) for q in v) for v in out}
    # Divide out the common content. Clearing denominators multiplies every
    # vector by the same integer, and if that integer shares a factor with n
    # the whole set looks divisible by n -- a scaling artefact, not an
    # obstruction. Reported as one until this line existed.
    content = 0
    for v in ints:
        for x in v:
            content = gcd(content, abs(x))
    if content > 1:
        ints = {tuple(x // content for x in v) for v in ints}
    return sorted(ints)


def has_homomorphism(vecs: Sequence[Sequence[int]], n: int
                     ) -> Tuple[Optional[Tuple[int, ...]], str]:
    """A phi in (Z/n)^dim nonzero on every vector, by SAT. Dimension-free."""
    from pysat.formula import IDPool
    from pysat.solvers import Solver

    vecs = [tuple(v) for v in vecs]
    dim = len(vecs[0])
    pool = IDPool()
    cls = []

    def phi(i, val):
        return pool.id(("phi", i, val))

    for i in range(dim):
        cls.append([phi(i, v) for v in range(n)])
        for a in range(n):
            for b in range(a + 1, n):
                cls.append([-phi(i, a), -phi(i, b)])

    for t, d in enumerate(vecs):
        idx = [i for i in range(dim) if d[i] % n]
        if not idx:
            return None, f"an edge vector is divisible by {n}"

        def s(j, val):
            return pool.id(("s", t, j, val))

        for val in range(n):
            cls.append([-phi(idx[0], val), s(0, (val * d[idx[0]]) % n)])
        for j in range(1, len(idx)):
            for prev in range(n):
                for val in range(n):
                    cls.append([-s(j - 1, prev), -phi(idx[j], val),
                                s(j, (prev + val * d[idx[j]]) % n)])
        cls.append([-s(len(idx) - 1, 0)])

    with Solver(name="cd19", bootstrap_with=cls) as sv:
        if not sv.solve():
            return None, "no homomorphism in this embedding"
        m = set(sv.get_model())
        return tuple(next(v for v in range(n) if phi(i, v) in m)
                     for i in range(dim)), "found"


def screen(graph, n: int = 5) -> dict:
    """Can this graph ever be (n+1)-chromatic? A homomorphism says no."""
    vecs = edge_vectors(graph)
    phi, why = has_homomorphism(vecs, n)
    return {
        "edge_vectors": len(vecs),
        "dimension": len(vecs[0]),
        "homomorphism": phi,
        "verdict": (f"{n}-colourable by cosets, so never {n+1}-chromatic"
                    if phi else f"no coset {n}-colouring in this embedding"),
    }


# -- where a coset colouring can and cannot be blocked --------------------
#
# phi must avoid every edge vector, so writing D for their images in M/5M, a
# phi exists unless the hyperplanes d-perp for d in D cover the whole dual.
# Two facts bound where that can happen, and the first is a theorem.
#
# RANK 2 NEVER BLOCKS. If the edge vectors span only rank 2 mod 5 then M is a
# plane lattice, every unit vector has the same norm N, and the value of the
# quadratic form on a projective point is well defined up to squares -- so all
# of them land in one square class, which is three of the six points of the
# projective line. Three hyperplanes cover 13 of the 25 points of (Z/5)^2, so
# a phi always survives. Measured on the Eisenstein lattice at norms 1, 3, 7,
# 13, 21, 49 and 91: every one gives exactly THREE classes, and which three is
# decided by whether N is a square mod 5 -- {(0,1),(1,0),(1,1)} when it is,
# {(1,2),(1,3),(1,4)} when it is not. Even 24 unit vectors, at norm 91, give
# three.
#
# RANK 3 FAILS TOO, for the same kind of reason: the unit vectors lie on a
# conic of PG(2,5), and a conic has exterior lines -- 10 of them -- so a phi
# again survives. From rank 4 upward Chevalley-Warning makes every hyperplane
# carry vectors of the right norm, so blocking becomes possible in principle.
#
# COUNTING IS NOT ENOUGH. A random phi survives m hyperplanes with probability
# (4/5)^m, so coverage needs roughly m > 7.2 r. That predicts the three-hexagon
# gadget (r = 4, m = 18, threshold 29) correctly and de Grey's G (r = 16,
# m = 133, threshold 115) wrongly -- G clears the count and still admits a phi.
# The unit vectors are confined to the quadric Q = N, and being few points of
# it is what matters, not being many points overall. Every root-of-unity step
# set up to n = 105 admits one: Z[zeta_n] has n distinct directions against
# rank phi(n), a ratio that never exceeds about 3.5.

RANK_TWO_NEVER_BLOCKS = (
    "a plane lattice's unit vectors all share one norm, so their projective "
    "classes mod 5 lie in one square class: three of six, never a blocking set"
)


# -- and the cheapest blocking set is unreachable -------------------------
#
# Blocking a coset colouring means the hyperplanes d-perp cover the dual, which
# asks the directions D to meet every hyperplane -- a blocking set. In
# PG(r-1,5) the smallest one is a projective LINE, six points. So the cheapest
# possible route is six unit vectors whose directions are the six points of a
# line. It does not exist.
#
# THEOREM. No projective line over F_5 has all six of its points carrying a
# quadratic form value in one square class. Hence the directions of unit
# vectors -- which all satisfy Q(d) = N for one N -- never contain a complete
# line.
#
# Checked exhaustively over every binary form (a, b, c) over F_5 and every
# target N: the maximum is FIVE of the six points, reached only when the form
# degenerates to rank one. The cases are easy to see by hand too. Anisotropic
# gives three of six, the two square classes splitting the line evenly;
# hyperbolic gives two, because two of the points are isotropic and carry
# Q = 0; rank one gives five, the sixth point being the radical.
#
# So the minimum blocking set is out of reach, and blocking would need a
# larger one. Measured across pairs of imaginary quadratic fields -- the only
# source here of infinitely many unit vectors at fixed rank, since the
# modulus-one elements of Q(sqrt-d1, sqrt-d2) are exactly the products of one
# from each factor -- the direction sets reach 25 at rank 4 and contain ZERO
# complete lines, on every pair tried.
#
# One trap, and it produced a false positive before it was found. Some of
# those generators have denominators divisible by 5, for instance
# (1 + 3 sqrt-11)/10. The module then stops being 5-integral, clearing
# denominators makes EVERY vector divisible by 5, and the search dutifully
# reports "no homomorphism" -- for reasons of arithmetic bookkeeping and
# nothing else. Generators must be filtered to denominators coprime to 5.

UNIT_DIRECTIONS_MISS_A_LINE = (
    "unit vectors all have one norm N, and no projective line over F_5 has "
    "all six points with Q in one square class -- at most five, and only for "
    "a degenerate form -- so they never contain the minimum blocking set"
)


# -- and where a blocking set finally exists ------------------------------
#
# The multiquadratic families fail for a reason that is quantitative and
# final. The projective direction count of the modulus-one group mod 5 is a
# product of small factors -- 3 where 5 is inert in a quadratic factor, 2
# where it splits -- so Q(sqrt-d1,...,sqrt-dt) of degree 2t gives at most 3^t
# directions against PG(2t-1,5)'s (5^2t - 1)/4 points. Measured: 6 at (7,11),
# 9 at (7,23), and 27 at (7,23,43) against 97656. The ratio (3/25)^t
# collapses, and more generators do not help, because the group is finite and
# already exhausted.
#
# The cause is the splitting. In a multiquadratic field the Galois group is
# (Z/2)^t and the decomposition group at 5 is cyclic, so the residue degree is
# at most 2 and O/5 breaks into many tiny fields. A LARGE norm-one group needs
# the decomposition group to be everything -- a CYCLIC Galois group with 5
# inert, which means Q(zeta_n) with 5 a primitive root mod n.
#
# n = 7 qualifies: 5 has order 6 in (Z/7)^*. Then O/5 = F_5^6 and the norm-one
# subgroup has (5^6 - 1)/(5^3 - 1) = 126 elements. Modulus-one elements come
# free from Hilbert 90 -- u = alpha/conj(alpha) has modulus one for every
# alpha, with denominator a norm, which only has to stay coprime to 5.
#
# RESULT. Sixty-three of those directions, at full rank 6, admit NO
# homomorphism to Z/5. Verified by brute force over all 5^6 = 15625 maps, not
# on the solver's word: zero survive. It is the first step set in this package
# with no coset 5-colouring at all.
#
# What that is and is not. It removes the structural colouring, which every
# other graph here had; it does not make any particular graph 6-chromatic,
# since an unstructured 5-colouring may still exist and only a solver can say.
# It is a necessary condition, met for the first time.

CYCLOTOMIC_BLOCKING = {
    "field": "Q(zeta_7), where 5 is a primitive root mod 7 and so inert",
    "norm_one_subgroup": (5 ** 6 - 1) // (5 ** 3 - 1),
    "directions": 63,
    "rank": 6,
    "projective_points": (5 ** 6 - 1) // 4,
    "homomorphisms_surviving": 0,
    "verified": "brute force over all 5^6 = 15625 maps",
}


# -- blocking and folding are both monotone, and that is the way out ------
#
# A first reading of the measurements below suggests the two demands fight:
# every graph in this package has a LOW-rank edge module and admits a coset
# colouring, while blocking wants directions spread through a high-rank one.
#
#   graph               n     m   |S|  rank  corank  chi  blocked
#   Moser spindle       7    11     7     4       3    4    no
#   triangular patch  121   320     3     2       1    3    no
#   de Grey S          39    18     8     4       4    3    no
#   de Grey Sa        397  1974    15     4      11    4    no
#   de Grey Sb        397  1974    15     4      11    4    no
#   de Grey Y         791  3938    33     8      25    4    no
#
# The reading is wrong, and saying why matters more than the table. Folding
# needs RELATIONS among the steps -- Z-independent steps build a tree, and a
# tree is bipartite -- so it is governed by the corank |S| - rank. Blocking
# needs the hyperplanes d-perp to cover PG(rank-1,5). BOTH are monotone
# increasing in the step set: adding a step adds a hyperplane to the cover and
# can only add relations. They therefore never trade against each other, and
# the right construction is the UNION of a folding set and a blocking one.
# The graphs above fail to block because their step sets are SMALL, not
# because their corank is large.

FOLDING_VERSUS_BLOCKING = (
    "blocking and folding are both monotone in the step set, so they never "
    "trade off; the known graphs miss blocking for want of steps, not for "
    "want of rank"
)


# -- where the blocking steps actually live -------------------------------
#
# Modulus-one elements of Q(zeta_7) come by Hilbert 90 as u = alpha/conj(alpha),
# and grouping them by denominator locates the obstruction exactly. Measured
# over a box of 1028 such elements, taking all those of denominator at most d:
#
#     d <= 1      14 elements     7 directions   no block
#     d <= 2      30             21              no block
#     d <= 4      40             31              no block
#     d <= 8      42             33              no block
#     d <= 11     44             35              no block
#     d <= 16     46             37              no block
#     d <= 29    106             87              BLOCKS
#
# Nothing below 29 suffices however many elements are collected, and 29 is the
# smallest rational prime that splits completely in Q(zeta_7) -- 29 = 4*7 + 1,
# so 29 = 1 mod 7. Splitting is what supplies many independent modulus-one
# elements of the same small denominator, which is exactly what covering
# PG(5,5) needs. The next denominators to appear, 43, 71, 113 and 127, are the
# following primes congruent to 1 mod 7, as the same reasoning predicts.

BLOCKING_DENOMINATOR = {
    "field": "Q(zeta_7)",
    "threshold": 29,
    "why": "the least rational prime splitting completely, 29 = 4*7 + 1",
    "directions_at_threshold": 87,
    "directions_below": 37,
    "later_denominators": [43, 71, 113, 127],
}


def minimum_blocking_set(vecs: Sequence[Sequence[int]], n: int = 5
                         ) -> List[Tuple[int, ...]]:
    """The fewest of these directions whose hyperplanes still cover the dual.

    Blocking is a covering problem: a direction d rules out the maps with
    phi(d) = 0, which is the hyperplane d-perp, so a set blocks exactly when
    its hyperplanes cover every projective point. Minimising the number of
    directions under that condition is unweighted MaxSAT, and worth solving
    exactly -- greedy covering carries a ln(points) factor and overshoots
    badly, so its answer says little about how small a construction could be.

    Returns [] when these directions do not cover at all.
    """
    import itertools

    from pysat.examples.rc2 import RC2
    from pysat.formula import WCNF

    vecs = [tuple(v) for v in vecs]
    dim = len(vecs[0])
    pts = [p for p in itertools.product(range(n), repeat=dim)
           if any(p) and next(x for x in p if x) == 1]
    w = WCNF()
    for p in pts:
        cl = [j + 1 for j, d in enumerate(vecs)
              if sum(a * b for a, b in zip(d, p)) % n == 0]
        if not cl:
            return []
        w.append(cl)
    for j in range(len(vecs)):
        w.append([-(j + 1)], weight=1)
    with RC2(w) as rc2:
        model = rc2.compute()
    return [vecs[j] for j in range(len(vecs)) if model[j] > 0]


# -- the first blocked graph, and why it is only 3-chromatic --------------
#
# Taking every modulus-one element of Q(zeta_7) of denominator at most 29 as a
# step and walking two rounds gives 15313 points and 30276 edges, realising
# all 87 blocking directions. It is the first graph in this package with NO
# coset 5-colouring: the structural colouring that every other construction
# here admitted is gone.
#
# It is nevertheless 3-COLOURABLE, and the reason is a theorem, not bad luck.
#
# THEOREM. A unit-distance graph over a field K contains a triangle if and
# only if zeta_6 lies in K.
#
# A triangle is three mutually unit-apart points, hence equilateral, hence one
# vertex is another rotated by 60 degrees about the third -- multiplication by
# a primitive sixth root of unity, which must therefore lie in K. Conversely
# zeta_6 in K builds one outright. The roots of unity of Q(zeta_7) are exactly
# mu_14, and 6 does not divide 14, so NO graph over Q(zeta_7) has a single
# triangle however large it grows. Clique number 2, and every high-chromatic
# unit-distance graph known leans on triangles throughout.
#
# So the field must supply both, and the two demands name it. Triangles need
# zeta_6, which needs 3 | n; blocking needs a rational prime splitting
# completely, which is where many independent modulus-one elements of one
# small denominator come from. The smallest cyclotomic field with both is
#
#     Q(zeta_21) = Q(zeta_3, zeta_7),   degree phi(21) = 12,
#
# which contains the whole Eisenstein lattice and its triangles, and inherits
# Q(zeta_7)'s split primes. In it 5 has order 6 in (Z/21)*, so 5 splits into
# two primes of residue degree 6 rather than staying inert.

TRIANGLE_NEEDS_ZETA6 = (
    "a unit-distance triangle is equilateral, so it is a rotation by 60 "
    "degrees: a graph over K has a triangle iff zeta_6 is in K, and the roots "
    "of unity of Q(zeta_7) are mu_14, so graphs there are triangle-free"
)

FIRST_BLOCKED_GRAPH = {
    "field": "Q(zeta_7)",
    "steps": "modulus-one elements of denominator <= 29",
    "n": 15313,
    "m": 30276,
    "edge_directions": 87,
    "coset_5_colourings": 0,
    "chromatic_number": 3,
    "why_low": "triangle-free: zeta_6 is not in Q(zeta_7)",
    "next_field": "Q(zeta_21), the smallest with both zeta_6 and the split primes",
}


# -- and the caveat that bounds all of it ---------------------------------
#
# Blocking is necessary and very far from sufficient, and it is worth being
# blunt about how far. Attaching a PENDANT edge in a blocking direction -- a
# single new vertex of degree one -- puts that direction into the edge module
# and so helps cover the dual, while changing the chromatic number by nothing
# at all: a degree-one vertex extends any colouring of the rest greedily. So
# any graph whatever can be made blocked without becoming one colour harder.
#
# What blocking buys is therefore not a bound but a MEASUREMENT that means
# something. A coset colouring composes with every automorphism of Z/n and
# every translation of the module, so while one exists the colour classes
# slide and every rigidity statistic reads flat -- which is exactly what
# happened to every forcing search in this package. Removing it is a
# precondition for the forcing machinery to have anything to detect. The
# chromatic number still has to be established by a solver, on a graph that is
# blocked AND rigid, and only the second half is hard.

BLOCKING_IS_NOT_SUFFICIENT = (
    "a pendant edge in a blocking direction blocks the graph and changes its "
    "chromatic number by nothing, so blocking is a precondition for rigidity "
    "to be measurable, never a bound on its own"
)


# -- why density and blocking really are at odds --------------------------
#
# Adding steps never hurts either property, but it does dilute a ball: at
# radius 2 over 178 steps only about one step-application in ninety lands back
# inside, so the graph has 16015 vertices and average degree 4.1. Density
# wants FEW, highly related steps -- a lattice, where every translate lands on
# a point. And there the obstruction is absolute.
#
# THEOREM. A unit-distance graph whose edge vectors generate a DISCRETE
# subgroup of R^2 can never block.
#
# A discrete subgroup of R^2 is isomorphic to Z^r with r <= 2, so the module
# has rank at most 2 and the dual is PG(1,5) -- six points, whose hyperplanes
# are single points, so covering needs SIX directions. But the unit circle
# meets a plane lattice in at most six points, the hexagonal case, giving at
# most THREE directions. Three against six: never. (And the bound is tight in
# the wrong direction -- the triangular lattice attains three and is exactly
# the classical coset 3-colouring.)
#
# So a blocked graph cannot live in a lattice, and must live in a module that
# is dense in the plane, where "every point of a region" is not a finite
# construction and a ball's boundary dominates its interior. That is the real
# reason the blocked graphs here come out sparse, and it is structural.

DISCRETE_NEVER_BLOCKS = (
    "a discrete subgroup of R^2 has rank <= 2, its unit circle holds at most "
    "six points hence three directions, and covering PG(1,5) needs six -- so "
    "no lattice graph ever blocks, and a blocked graph must be non-discrete"
)


# -- degree efficiency: what the tension actually costs -------------------
#
# Blocking and folding are both monotone in the step set, so they do not trade
# off directly. Density per VERTEX does, and one statistic shows it:
#
#     efficiency = average degree / unit vectors available in the module.
#
# A rank-2 module is discrete, so a patch of it is CLOSED -- nearly every
# point has all its neighbours present. A module of rank 3 or more is dense in
# the plane, so no bounded region contains a closed piece, every ball is
# boundary, and most available steps land outside it. Measured:
#
#     graph                  n      m  steps  avg deg  efficiency  blocked
#     triangular patch     121    320      6     5.29     88.2%      no
#     de Grey S             39     18     16     0.92      5.8%      no
#     de Grey Sa           397   1974     30     9.94     33.1%      no
#     de Grey Y            791   3938     66     9.96     15.1%      no
#     de Grey G           1581   7877    134     9.96      7.4%      no
#     Q(zeta_7) ball     15313  30276    174     3.95      2.3%     YES
#     Q(zeta_21) ball    16015  32722    178     4.09      2.3%     YES
#
# Efficiency falls monotonically as the structures get richer, and blocking
# appears only at the bottom. Note what does NOT fall: de Grey's three sizes
# all sit at average degree 9.96, unchanged. What collapses is the fraction of
# the available density a finite construction manages to collect.
#
# So the cost of blocking is not fewer neighbours -- it is needing forty times
# as many steps to get the same ten.

DEGREE_EFFICIENCY = {
    "triangular patch": 0.882, "de Grey Sa": 0.331, "de Grey Y": 0.151,
    "de Grey G": 0.074, "Q(zeta_7) ball": 0.023, "Q(zeta_21) ball": 0.023,
    "blocked_at": ["Q(zeta_7) ball", "Q(zeta_21) ball"],
    "de_grey_average_degree": 9.96,
}


# -- blocking needs the whole module, which is why it costs what it does --
#
# The cheapest cover, a pencil of six hyperplanes, needs its six directions to
# lie in one 2-dimensional subspace -- and there they would have to hit all
# six points of a PG(1,5) while sharing one norm, which no square class
# allows. So a blocking set of unit vectors is never minimal, and the question
# becomes how much rank it takes.
#
# Constructed rather than sampled, since random subsets of Q(zeta_7)'s steps
# have full rank almost always: span a submodule, then collect every unit step
# inside it -- the whole unit circle of that submodule, which is what a graph
# built there would have.
#
#     rank 3   2 submodules with 6+ unit steps   richest 12 directions   no
#     rank 4  34 submodules                      richest  4 directions   no
#     rank 5 159 submodules                      richest  5 directions   no
#     rank 6  the whole module                           87 directions  YES
#
# Proper submodules simply do not contain enough unit vectors: six to fourteen
# where covering PG(r-1,5) needs far more. So blocking requires the FULL rank,
# and the full rank is exactly what makes the module densest in the plane and
# a ball's interior vanish against its boundary. That closes the loop with the
# efficiency table: blocking costs 2.3 per cent not by accident but because
# nothing short of the whole module blocks at all.

BLOCKING_NEEDS_FULL_RANK = {
    "field": "Q(zeta_7), rank 6",
    "submodule_ranks_tested": [3, 4, 5],
    "unit_directions_found": {3: 12, 4: 4, 5: 5},
    "blocks_at": 6,
    "why": "proper submodules hold six to fourteen unit vectors where "
           "covering needs far more, so nothing short of the whole module "
           "blocks -- and the whole module is the densest in the plane",
}


# -- no Eisenstein spindle exists over Q(zeta_21), and that is provable --
#
# Every union built over Q(zeta_21) came back 3-chromatic, however many
# rotated copies were stacked -- 241 points, 630 edges, chi 3. The reason is a
# theorem rather than bad luck.
#
# A spindle needs two points forced to the SAME colour at k colours, at some
# distance d, and a rotation rho with |1 - rho| = 1/d. In the Eisenstein
# lattice at three colours the forcing is exact, the lattice being uniquely
# 3-colourable: p and q share a colour precisely when p - q lies in the
# index-3 sublattice, so d^2 = N(p-q) is divisible by 3. Write d^2 = 3m. Then
#
#     |1 - rho|^2 = 2 - 2 Re(rho) = 1/(3m)   =>   Re(rho) = (6m-1)/(6m),
#     rho = ( (6m-1) +- sqrt(-(12m-1)) ) / (6m).
#
# So rho lies in the field exactly when sqrt(-(12m-1)) does. The imaginary
# quadratic subfields of Q(zeta_21) are only Q(sqrt-3) and Q(sqrt-7), so the
# condition is 12m - 1 = 3t^2 or 7t^2 -- and modulo 12 that is impossible:
# 12m - 1 is 11, while 3t^2 takes only 0 and 3, and 7t^2 only 0, 3, 4 and 7.
# Checked directly for the first thousand m as well: none.
#
# m = 1 is the classical case, 12 - 1 = 11, the Moser rotation's sqrt(-11) --
# exactly the subfield Q(zeta_21) does not have.
#
# WHICH NAMES THE FIELD. Triangles need zeta_6, blocking needs zeta_7, and the
# spindle needs sqrt(-11). Q(zeta_21, sqrt-11), degree 24, is the smallest
# field with all three.

NO_EISENSTEIN_SPINDLE_OVER_ZETA21 = {
    "condition": "12m - 1 must be 3t^2 or 7t^2",
    "obstruction": "12m - 1 = 11 mod 12, while 3t^2 takes 0 and 3 and 7t^2 "
                   "takes 0, 3, 4 and 7",
    "checked_to": 1000,
    "solutions": 0,
    "classical_case": "m = 1 gives 11 -- the Moser rotation's sqrt(-11)",
    "field_that_works": "Q(zeta_21, sqrt-11), degree 24: zeta_6 for triangles, "
                        "zeta_7 for blocking, sqrt-11 for the spindle",
}
