"""Homomorphism colourings: the most structural colouring a graph can have.

Let M be the Z-module generated by a unit-distance graph's EDGE vectors. A
group homomorphism

    phi : M -> Z/n   with   phi(d) != 0 for every edge vector d

is itself a proper n-colouring, c(p) = phi(p): adjacent points differ by an
edge vector, so their colours differ. It is constant on cosets of ker phi, so
it is as regular as a colouring gets -- the opposite of the rigidity that a
small rainbow-forcing set needs.

Two things follow, and both are useful.

A NECESSARY CONDITION. If such a phi exists for n = 5, every subset of M is
5-colourable and no graph built from those steps can ever be 6-chromatic. So
a candidate can be screened in seconds, before any colouring search.

AN EXPLANATION. de Grey's G, his Sa, and the whole three-hexagon gadget family
all admit one at n = 5 -- found by SAT in under a second each. Their
5-colourings are coset colourings, which is why every rigidity measurement in
this package came back flat: a coset colouring can be composed with the
automorphisms of Z/n and with any translation of the module, so the colour
classes move freely and the forcing sets are enormous.

WHERE TO LOOK. phi must avoid every edge vector, so writing D for their images
in M/5M, a phi exists unless the hyperplanes d-perp for d in D cover the whole
dual. Covering needs D to meet every hyperplane -- a blocking set -- and the
smallest is a projective line, q + 1 = SIX points. So six unit vectors whose
reductions represent the six points of a projective line over Z/5 rule out
every homomorphism at once. That is a finite, checkable design target.

ONE CAVEAT, stated because it bounds what the tool proves. The search embeds
M in Z^d by clearing a common denominator and looks for phi defined on that
Z^d. Every phi it FINDS is genuine, since restriction is a homomorphism. A
"none found" is only a statement about that embedding unless M is a direct
summand, so this module screens IN rather than screens OUT.
"""

from __future__ import annotations

import itertools
from fractions import Fraction
from math import gcd
from typing import List, Optional, Sequence, Tuple

__all__ = ["edge_vectors", "has_homomorphism", "screen", "minimum_blocking_set",
           "cyclotomic_can_block", "orbit_can_block", "periodic_screen",
           "rotation_field_degree",
           "cayley_chromatic",
           "cyclotomic_chain_closes",
           "denominator_29_directions"]


def _coords(e) -> Tuple[Fraction, ...]:
    """Full rational coordinates, including a real extension's radical part.

    `.c` on a RealExtElement returns only its base component, so using it here
    silently truncated the edge vectors of anything living over sqrt(v) and
    reported a homomorphism search on the wrong module. Both halves are needed.
    """
    a = getattr(e, "a", None)
    b = getattr(e, "b", None)
    if a is not None and b is not None:
        return tuple(a.c) + tuple(b.c)
    return tuple(e.c)


def edge_vectors(graph) -> List[Tuple[int, ...]]:
    """Distinct edge vectors as integer tuples, over a common denominator."""
    out = set()
    for a, b in graph.edges():
        d = (graph.vertices[b].x - graph.vertices[a].x,
             graph.vertices[b].y - graph.vertices[a].y)
        out.add(_coords(d[0]) + _coords(d[1]))
    den = 1
    for v in out:
        for q in v:
            den = den * Fraction(q).denominator // gcd(den,
                                                       Fraction(q).denominator)
    ints = {tuple(int(Fraction(q) * den) for q in v) for v in out}
    # Divide out the common content. Clearing denominators multiplies every
    # vector by the same integer, and if that integer shares a factor with n
    # the whole set looks divisible by n -- a scaling artefact, not an
    # obstruction. Reported as one until this line existed.
    content = 0
    for v in ints:
        for x in v:
            content = gcd(content, abs(x))
    if content > 1:
        ints = {tuple(x // content for x in v) for v in ints}
    return sorted(ints)


def has_homomorphism(vecs: Sequence[Sequence[int]], n: int
                     ) -> Tuple[Optional[Tuple[int, ...]], str]:
    """A phi in (Z/n)^dim nonzero on every vector, by SAT. Dimension-free."""
    from pysat.formula import IDPool
    from pysat.solvers import Solver

    vecs = [tuple(v) for v in vecs]
    dim = len(vecs[0])
    pool = IDPool()
    cls = []

    def phi(i, val):
        return pool.id(("phi", i, val))

    for i in range(dim):
        cls.append([phi(i, v) for v in range(n)])
        for a in range(n):
            for b in range(a + 1, n):
                cls.append([-phi(i, a), -phi(i, b)])

    for t, d in enumerate(vecs):
        idx = [i for i in range(dim) if d[i] % n]
        if not idx:
            return None, f"an edge vector is divisible by {n}"

        def s(j, val):
            return pool.id(("s", t, j, val))

        for val in range(n):
            cls.append([-phi(idx[0], val), s(0, (val * d[idx[0]]) % n)])
        for j in range(1, len(idx)):
            for prev in range(n):
                for val in range(n):
                    cls.append([-s(j - 1, prev), -phi(idx[j], val),
                                s(j, (prev + val * d[idx[j]]) % n)])
        cls.append([-s(len(idx) - 1, 0)])

    with Solver(name="cd19", bootstrap_with=cls) as sv:
        if not sv.solve():
            return None, "no homomorphism in this embedding"
        m = set(sv.get_model())
        return tuple(next(v for v in range(n) if phi(i, v) in m)
                     for i in range(dim)), "found"


def screen(graph, n: int = 5) -> dict:
    """Can this graph ever be (n+1)-chromatic? A homomorphism says no."""
    vecs = edge_vectors(graph)
    phi, why = has_homomorphism(vecs, n)
    return {
        "edge_vectors": len(vecs),
        "dimension": len(vecs[0]),
        "homomorphism": phi,
        "verdict": (f"{n}-colourable by cosets, so never {n+1}-chromatic"
                    if phi else f"no coset {n}-colouring in this embedding"),
    }


# -- where a coset colouring can and cannot be blocked --------------------
#
# phi must avoid every edge vector, so writing D for their images in M/5M, a
# phi exists unless the hyperplanes d-perp for d in D cover the whole dual.
# Two facts bound where that can happen, and the first is a theorem.
#
# RANK 2 NEVER BLOCKS. If the edge vectors span only rank 2 mod 5 then M is a
# plane lattice, every unit vector has the same norm N, and the value of the
# quadratic form on a projective point is well defined up to squares -- so all
# of them land in one square class, which is three of the six points of the
# projective line. Three hyperplanes cover 13 of the 25 points of (Z/5)^2, so
# a phi always survives. Measured on the Eisenstein lattice at norms 1, 3, 7,
# 13, 21, 49 and 91: every one gives exactly THREE classes, and which three is
# decided by whether N is a square mod 5 -- {(0,1),(1,0),(1,1)} when it is,
# {(1,2),(1,3),(1,4)} when it is not. Even 24 unit vectors, at norm 91, give
# three.
#
# RANK 3 FAILS TOO, for the same kind of reason: the unit vectors lie on a
# conic of PG(2,5), and a conic has exterior lines -- 10 of them -- so a phi
# again survives. From rank 4 upward Chevalley-Warning makes every hyperplane
# carry vectors of the right norm, so blocking becomes possible in principle.
#
# COUNTING IS NOT ENOUGH. A random phi survives m hyperplanes with probability
# (4/5)^m, so coverage needs roughly m > 7.2 r. That predicts the three-hexagon
# gadget (r = 4, m = 18, threshold 29) correctly and de Grey's G (r = 16,
# m = 133, threshold 115) wrongly -- G clears the count and still admits a phi.
# The unit vectors are confined to the quadric Q = N, and being few points of
# it is what matters, not being many points overall. Every root-of-unity step
# set up to n = 105 admits one: Z[zeta_n] has n distinct directions against
# rank phi(n), a ratio that never exceeds about 3.5.

RANK_TWO_NEVER_BLOCKS = (
    "a plane lattice's unit vectors all share one norm, so their projective "
    "classes mod 5 lie in one square class: three of six, never a blocking set"
)


# -- and the cheapest blocking set is unreachable -------------------------
#
# Blocking a coset colouring means the hyperplanes d-perp cover the dual, which
# asks the directions D to meet every hyperplane -- a blocking set. In
# PG(r-1,5) the smallest one is a projective LINE, six points. So the cheapest
# possible route is six unit vectors whose directions are the six points of a
# line. It does not exist.
#
# THEOREM. No projective line over F_5 has all six of its points carrying a
# quadratic form value in one square class. Hence the directions of unit
# vectors -- which all satisfy Q(d) = N for one N -- never contain a complete
# line.
#
# Checked exhaustively over every binary form (a, b, c) over F_5 and every
# target N: the maximum is FIVE of the six points, reached only when the form
# degenerates to rank one. The cases are easy to see by hand too. Anisotropic
# gives three of six, the two square classes splitting the line evenly;
# hyperbolic gives two, because two of the points are isotropic and carry
# Q = 0; rank one gives five, the sixth point being the radical.
#
# So the minimum blocking set is out of reach, and blocking would need a
# larger one. Measured across pairs of imaginary quadratic fields -- the only
# source here of infinitely many unit vectors at fixed rank, since the
# modulus-one elements of Q(sqrt-d1, sqrt-d2) are exactly the products of one
# from each factor -- the direction sets reach 25 at rank 4 and contain ZERO
# complete lines, on every pair tried.
#
# One trap, and it produced a false positive before it was found. Some of
# those generators have denominators divisible by 5, for instance
# (1 + 3 sqrt-11)/10. The module then stops being 5-integral, clearing
# denominators makes EVERY vector divisible by 5, and the search dutifully
# reports "no homomorphism" -- for reasons of arithmetic bookkeeping and
# nothing else. Generators must be filtered to denominators coprime to 5.

UNIT_DIRECTIONS_MISS_A_LINE = (
    "unit vectors all have one norm N, and no projective line over F_5 has "
    "all six points with Q in one square class -- at most five, and only for "
    "a degenerate form -- so they never contain the minimum blocking set"
)


# -- and where a blocking set finally exists ------------------------------
#
# The multiquadratic families fail for a reason that is quantitative and
# final. The projective direction count of the modulus-one group mod 5 is a
# product of small factors -- 3 where 5 is inert in a quadratic factor, 2
# where it splits -- so Q(sqrt-d1,...,sqrt-dt) of degree 2t gives at most 3^t
# directions against PG(2t-1,5)'s (5^2t - 1)/4 points. Measured: 6 at (7,11),
# 9 at (7,23), and 27 at (7,23,43) against 97656. The ratio (3/25)^t
# collapses, and more generators do not help, because the group is finite and
# already exhausted.
#
# The cause is the splitting. In a multiquadratic field the Galois group is
# (Z/2)^t and the decomposition group at 5 is cyclic, so the residue degree is
# at most 2 and O/5 breaks into many tiny fields. A LARGE norm-one group needs
# the decomposition group to be everything -- a CYCLIC Galois group with 5
# inert, which means Q(zeta_n) with 5 a primitive root mod n.
#
# n = 7 qualifies: 5 has order 6 in (Z/7)^*. Then O/5 = F_5^6 and the norm-one
# subgroup has (5^6 - 1)/(5^3 - 1) = 126 elements. Modulus-one elements come
# free from Hilbert 90 -- u = alpha/conj(alpha) has modulus one for every
# alpha, with denominator a norm, which only has to stay coprime to 5.
#
# RESULT. Sixty-three of those directions, at full rank 6, admit NO
# homomorphism to Z/5. Verified by brute force over all 5^6 = 15625 maps, not
# on the solver's word: zero survive. It is the first step set in this package
# with no coset 5-colouring at all.
#
# What that is and is not. It removes the structural colouring, which every
# other graph here had; it does not make any particular graph 6-chromatic,
# since an unstructured 5-colouring may still exist and only a solver can say.
# It is a necessary condition, met for the first time.

CYCLOTOMIC_BLOCKING = {
    "field": "Q(zeta_7), where 5 is a primitive root mod 7 and so inert",
    "norm_one_subgroup": (5 ** 6 - 1) // (5 ** 3 - 1),
    "directions": 63,
    "rank": 6,
    "projective_points": (5 ** 6 - 1) // 4,
    "homomorphisms_surviving": 0,
    "verified": "brute force over all 5^6 = 15625 maps",
}


# -- blocking and folding are both monotone, and that is the way out ------
#
# A first reading of the measurements below suggests the two demands fight:
# every graph in this package has a LOW-rank edge module and admits a coset
# colouring, while blocking wants directions spread through a high-rank one.
#
#   graph               n     m   |S|  rank  corank  chi  blocked
#   Moser spindle       7    11     7     4       3    4    no
#   triangular patch  121   320     3     2       1    3    no
#   de Grey S          39    18     8     4       4    3    no
#   de Grey Sa        397  1974    15     4      11    4    no
#   de Grey Sb        397  1974    15     4      11    4    no
#   de Grey Y         791  3938    33     8      25    4    no
#
# The reading is wrong, and saying why matters more than the table. Folding
# needs RELATIONS among the steps -- Z-independent steps build a tree, and a
# tree is bipartite -- so it is governed by the corank |S| - rank. Blocking
# needs the hyperplanes d-perp to cover PG(rank-1,5). BOTH are monotone
# increasing in the step set: adding a step adds a hyperplane to the cover and
# can only add relations. They therefore never trade against each other, and
# the right construction is the UNION of a folding set and a blocking one.
# The graphs above fail to block because their step sets are SMALL, not
# because their corank is large.

FOLDING_VERSUS_BLOCKING = (
    "blocking and folding are both monotone in the step set, so they never "
    "trade off; the known graphs miss blocking for want of steps, not for "
    "want of rank"
)


# -- where the blocking steps actually live -------------------------------
#
# Modulus-one elements of Q(zeta_7) come by Hilbert 90 as u = alpha/conj(alpha),
# and grouping them by denominator locates the obstruction exactly. Measured
# over a box of 1028 such elements, taking all those of denominator at most d:
#
#     d <= 1      14 elements     7 directions   no block
#     d <= 2      30             21              no block
#     d <= 4      40             31              no block
#     d <= 8      42             33              no block
#     d <= 11     44             35              no block
#     d <= 16     46             37              no block
#     d <= 29    106             87              BLOCKS
#
# Nothing below 29 suffices however many elements are collected, and 29 is the
# smallest rational prime that splits completely in Q(zeta_7) -- 29 = 4*7 + 1,
# so 29 = 1 mod 7. Splitting is what supplies many independent modulus-one
# elements of the same small denominator, which is exactly what covering
# PG(5,5) needs. The next denominators to appear, 43, 71, 113 and 127, are the
# following primes congruent to 1 mod 7, as the same reasoning predicts.

BLOCKING_DENOMINATOR = {
    "field": "Q(zeta_7)",
    "threshold": 29,
    "why": "the least rational prime splitting completely, 29 = 4*7 + 1",
    "directions_at_threshold": 87,
    "directions_below": 37,
    "later_denominators": [43, 71, 113, 127],
}


def minimum_blocking_set(vecs: Sequence[Sequence[int]], n: int = 5
                         ) -> List[Tuple[int, ...]]:
    """The fewest of these directions whose hyperplanes still cover the dual.

    Blocking is a covering problem: a direction d rules out the maps with
    phi(d) = 0, which is the hyperplane d-perp, so a set blocks exactly when
    its hyperplanes cover every projective point. Minimising the number of
    directions under that condition is unweighted MaxSAT, and worth solving
    exactly -- greedy covering carries a ln(points) factor and overshoots
    badly, so its answer says little about how small a construction could be.

    Returns [] when these directions do not cover at all.
    """
    import itertools

    from pysat.examples.rc2 import RC2
    from pysat.formula import WCNF

    vecs = [tuple(v) for v in vecs]
    dim = len(vecs[0])
    pts = [p for p in itertools.product(range(n), repeat=dim)
           if any(p) and next(x for x in p if x) == 1]
    w = WCNF()
    for p in pts:
        cl = [j + 1 for j, d in enumerate(vecs)
              if sum(a * b for a, b in zip(d, p)) % n == 0]
        if not cl:
            return []
        w.append(cl)
    for j in range(len(vecs)):
        w.append([-(j + 1)], weight=1)
    with RC2(w) as rc2:
        model = rc2.compute()
    return [vecs[j] for j in range(len(vecs)) if model[j] > 0]


# -- the first blocked graph, and why it is only 3-chromatic --------------
#
# Taking every modulus-one element of Q(zeta_7) of denominator at most 29 as a
# step and walking two rounds gives 15313 points and 30276 edges, realising
# all 87 blocking directions. It is the first graph in this package with NO
# coset 5-colouring: the structural colouring that every other construction
# here admitted is gone.
#
# It is nevertheless 3-COLOURABLE, and the reason is a theorem, not bad luck.
#
# THEOREM. A unit-distance graph over a field K contains a triangle if and
# only if zeta_6 lies in K.
#
# A triangle is three mutually unit-apart points, hence equilateral, hence one
# vertex is another rotated by 60 degrees about the third -- multiplication by
# a primitive sixth root of unity, which must therefore lie in K. Conversely
# zeta_6 in K builds one outright. The roots of unity of Q(zeta_7) are exactly
# mu_14, and 6 does not divide 14, so NO graph over Q(zeta_7) has a single
# triangle however large it grows. Clique number 2, and every high-chromatic
# unit-distance graph known leans on triangles throughout.
#
# So the field must supply both, and the two demands name it. Triangles need
# zeta_6, which needs 3 | n; blocking needs a rational prime splitting
# completely, which is where many independent modulus-one elements of one
# small denominator come from. The smallest cyclotomic field with both is
#
#     Q(zeta_21) = Q(zeta_3, zeta_7),   degree phi(21) = 12,
#
# which contains the whole Eisenstein lattice and its triangles, and inherits
# Q(zeta_7)'s split primes. In it 5 has order 6 in (Z/21)*, so 5 splits into
# two primes of residue degree 6 rather than staying inert.

TRIANGLE_NEEDS_ZETA6 = (
    "a unit-distance triangle is equilateral, so it is a rotation by 60 "
    "degrees: a graph over K has a triangle iff zeta_6 is in K, and the roots "
    "of unity of Q(zeta_7) are mu_14, so graphs there are triangle-free"
)

FIRST_BLOCKED_GRAPH = {
    "field": "Q(zeta_7)",
    "steps": "modulus-one elements of denominator <= 29",
    "n": 15313,
    "m": 30276,
    "edge_directions": 87,
    "coset_5_colourings": 0,
    "chromatic_number": 3,
    "why_low": "triangle-free: zeta_6 is not in Q(zeta_7)",
    "next_field": "Q(zeta_21), the smallest with both zeta_6 and the split primes",
}


# -- and the caveat that bounds all of it ---------------------------------
#
# Blocking is necessary and very far from sufficient, and it is worth being
# blunt about how far. Attaching a PENDANT edge in a blocking direction -- a
# single new vertex of degree one -- puts that direction into the edge module
# and so helps cover the dual, while changing the chromatic number by nothing
# at all: a degree-one vertex extends any colouring of the rest greedily. So
# any graph whatever can be made blocked without becoming one colour harder.
#
# What blocking buys is therefore not a bound but a MEASUREMENT that means
# something. A coset colouring composes with every automorphism of Z/n and
# every translation of the module, so while one exists the colour classes
# slide and every rigidity statistic reads flat -- which is exactly what
# happened to every forcing search in this package. Removing it is a
# precondition for the forcing machinery to have anything to detect. The
# chromatic number still has to be established by a solver, on a graph that is
# blocked AND rigid, and only the second half is hard.

BLOCKING_IS_NOT_SUFFICIENT = (
    "a pendant edge in a blocking direction blocks the graph and changes its "
    "chromatic number by nothing, so blocking is a precondition for rigidity "
    "to be measurable, never a bound on its own"
)


# -- why density and blocking really are at odds --------------------------
#
# Adding steps never hurts either property, but it does dilute a ball: at
# radius 2 over 178 steps only about one step-application in ninety lands back
# inside, so the graph has 16015 vertices and average degree 4.1. Density
# wants FEW, highly related steps -- a lattice, where every translate lands on
# a point. And there the obstruction is absolute.
#
# THEOREM. A unit-distance graph whose edge vectors generate a DISCRETE
# subgroup of R^2 can never block.
#
# A discrete subgroup of R^2 is isomorphic to Z^r with r <= 2, so the module
# has rank at most 2 and the dual is PG(1,5) -- six points, whose hyperplanes
# are single points, so covering needs SIX directions. But the unit circle
# meets a plane lattice in at most six points, the hexagonal case, giving at
# most THREE directions. Three against six: never. (And the bound is tight in
# the wrong direction -- the triangular lattice attains three and is exactly
# the classical coset 3-colouring.)
#
# So a blocked graph cannot live in a lattice, and must live in a module that
# is dense in the plane, where "every point of a region" is not a finite
# construction and a ball's boundary dominates its interior. That is the real
# reason the blocked graphs here come out sparse, and it is structural.

DISCRETE_NEVER_BLOCKS = (
    "a discrete subgroup of R^2 has rank <= 2, its unit circle holds at most "
    "six points hence three directions, and covering PG(1,5) needs six -- so "
    "no lattice graph ever blocks, and a blocked graph must be non-discrete"
)


# -- degree efficiency: what the tension actually costs -------------------
#
# Blocking and folding are both monotone in the step set, so they do not trade
# off directly. Density per VERTEX does, and one statistic shows it:
#
#     efficiency = average degree / unit vectors available in the module.
#
# A rank-2 module is discrete, so a patch of it is CLOSED -- nearly every
# point has all its neighbours present. A module of rank 3 or more is dense in
# the plane, so no bounded region contains a closed piece, every ball is
# boundary, and most available steps land outside it. Measured:
#
#     graph                  n      m  steps  avg deg  efficiency  blocked
#     triangular patch     121    320      6     5.29     88.2%      no
#     de Grey S             39     18     16     0.92      5.8%      no
#     de Grey Sa           397   1974     30     9.94     33.1%      no
#     de Grey Y            791   3938     66     9.96     15.1%      no
#     de Grey G           1581   7877    134     9.96      7.4%      no
#     Q(zeta_7) ball     15313  30276    174     3.95      2.3%     YES
#     Q(zeta_21) ball    16015  32722    178     4.09      2.3%     YES
#
# Efficiency falls monotonically as the structures get richer, and blocking
# appears only at the bottom. Note what does NOT fall: de Grey's three sizes
# all sit at average degree 9.96, unchanged. What collapses is the fraction of
# the available density a finite construction manages to collect.
#
# So the cost of blocking is not fewer neighbours -- it is needing forty times
# as many steps to get the same ten.

DEGREE_EFFICIENCY = {
    "triangular patch": 0.882, "de Grey Sa": 0.331, "de Grey Y": 0.151,
    "de Grey G": 0.074, "Q(zeta_7) ball": 0.023, "Q(zeta_21) ball": 0.023,
    "blocked_at": ["Q(zeta_7) ball", "Q(zeta_21) ball"],
    "de_grey_average_degree": 9.96,
}


# -- blocking needs the whole module, which is why it costs what it does --
#
# The cheapest cover, a pencil of six hyperplanes, needs its six directions to
# lie in one 2-dimensional subspace -- and there they would have to hit all
# six points of a PG(1,5) while sharing one norm, which no square class
# allows. So a blocking set of unit vectors is never minimal, and the question
# becomes how much rank it takes.
#
# Constructed rather than sampled, since random subsets of Q(zeta_7)'s steps
# have full rank almost always: span a submodule, then collect every unit step
# inside it -- the whole unit circle of that submodule, which is what a graph
# built there would have.
#
#     rank 3   2 submodules with 6+ unit steps   richest 12 directions   no
#     rank 4  34 submodules                      richest  4 directions   no
#     rank 5 159 submodules                      richest  5 directions   no
#     rank 6  the whole module                           87 directions  YES
#
# Proper submodules simply do not contain enough unit vectors: six to fourteen
# where covering PG(r-1,5) needs far more. So blocking requires the FULL rank,
# and the full rank is exactly what makes the module densest in the plane and
# a ball's interior vanish against its boundary. That closes the loop with the
# efficiency table: blocking costs 2.3 per cent not by accident but because
# nothing short of the whole module blocks at all.

BLOCKING_NEEDS_FULL_RANK = {
    "field": "Q(zeta_7), rank 6",
    "submodule_ranks_tested": [3, 4, 5],
    "unit_directions_found": {3: 12, 4: 4, 5: 5},
    "blocks_at": 6,
    "why": "proper submodules hold six to fourteen unit vectors where "
           "covering needs far more, so nothing short of the whole module "
           "blocks -- and the whole module is the densest in the plane",
}


# -- no Eisenstein spindle exists over Q(zeta_21), and that is provable --
#
# Every union built over Q(zeta_21) came back 3-chromatic, however many
# rotated copies were stacked -- 241 points, 630 edges, chi 3. The reason is a
# theorem rather than bad luck.
#
# A spindle needs two points forced to the SAME colour at k colours, at some
# distance d, and a rotation rho with |1 - rho| = 1/d. In the Eisenstein
# lattice at three colours the forcing is exact, the lattice being uniquely
# 3-colourable: p and q share a colour precisely when p - q lies in the
# index-3 sublattice, so d^2 = N(p-q) is divisible by 3. Write d^2 = 3m. Then
#
#     |1 - rho|^2 = 2 - 2 Re(rho) = 1/(3m)   =>   Re(rho) = (6m-1)/(6m),
#     rho = ( (6m-1) +- sqrt(-(12m-1)) ) / (6m).
#
# So rho lies in the field exactly when sqrt(-(12m-1)) does. The imaginary
# quadratic subfields of Q(zeta_21) are only Q(sqrt-3) and Q(sqrt-7), so the
# condition is 12m - 1 = 3t^2 or 7t^2 -- and modulo 12 that is impossible:
# 12m - 1 is 11, while 3t^2 takes only 0 and 3, and 7t^2 only 0, 3, 4 and 7.
# Checked directly for the first thousand m as well: none.
#
# m = 1 is the classical case, 12 - 1 = 11, the Moser rotation's sqrt(-11) --
# exactly the subfield Q(zeta_21) does not have.
#
# WHICH NAMES THE FIELD. Triangles need zeta_6, blocking needs zeta_7, and the
# spindle needs sqrt(-11). Q(zeta_21, sqrt-11), degree 24, is the smallest
# field with all three.

NO_EISENSTEIN_SPINDLE_OVER_ZETA21 = {
    "condition": "12m - 1 must be 3t^2 or 7t^2",
    "obstruction": "12m - 1 = 11 mod 12, while 3t^2 takes 0 and 3 and 7t^2 "
                   "takes 0, 3, 4 and 7",
    "checked_to": 1000,
    "solutions": 0,
    "classical_case": "m = 1 gives 11 -- the Moser rotation's sqrt(-11)",
    "field_that_works": "Q(zeta_21, sqrt-11), degree 24: zeta_6 for triangles, "
                        "zeta_7 for blocking, sqrt-11 for the spindle",
}


# -- the field works, and here is the first graph with both properties ---
#
# Q(zeta_21, sqrt-11), degree 24, built as a quadratic extension of the
# cyclotomic field: elements a + b s with s^2 = -11, complex conjugation
# sending zeta to its inverse and negating s. Verified in it:
#
#     |rho|^2 = 1 and |1 - rho|^2 = 1/3 for rho = (5 + sqrt-11)/6
#     the Moser spindle: 7 points, 11 edges, chi = 4
#
# So the field carries the spindle that Q(zeta_21) provably cannot, and it
# contains Q(zeta_7), whose denominator-29 steps block every homomorphism to
# Z/5. Building from both gives 107 points, 111 edges, 107 edge directions:
#
#     coset 5-colouring: NONE       3-colourable: no       chi = 4
#
# The first graph here with a chromatic number above 3 AND no coset colouring.
# Everything blocked before was 3-chromatic, and everything with a chromatic
# number admitted a coset colouring.
#
# STATED FOR WHAT IT IS. The blocking comes from pendant vertices hung off a
# single spindle point -- all 144 steps, since forty of them left a coset
# colouring intact and the inheritance needs every direction of the Q(zeta_7)
# submodule. By the caveat recorded above, a pendant in a blocking direction
# blocks the graph and changes the chromatic number by nothing. So this object
# demonstrates that the field carries both properties at once; it does not
# demonstrate that the blocking is doing any work.
#
# What would: the same two properties where the blocking steps are load
# bearing, and at five colours rather than four.

FIRST_BLOCKED_AND_CHROMATIC = {
    "field": "Q(zeta_21, sqrt-11), degree 24",
    "spindle": {"points": 7, "edges": 11, "chi": 4},
    "graph": {"points": 107, "edges": 111, "directions": 107},
    "coset_colourings": 0,
    "chi": 4,
    "honest": "the blocking is carried by pendant vertices, which change no "
              "chromatic number; the object shows the field works, not that "
              "the blocking is load bearing",
    "needed_forty_vs": 144,
}


# -- the gate: every 6-chromatic unit-distance graph is blocked -------------
#
# This is what makes blocking worth anything, and it is one line. A coset
# colouring is a homomorphism phi from the edge module M to Z/n that is
# nonzero on every edge vector. The vertices of a connected unit-distance
# graph all lie in v0 + M, so colouring v by phi(v - v0) is well defined, and
# adjacent u, v get phi(u - v) != 0, hence different colours. So
#
#     a coset colouring with n colours is an n-colouring, and chi <= n.
#
# Contrapositive at n = 5:
#
#     EVERY 6-CHROMATIC UNIT-DISTANCE GRAPH IS BLOCKED.
#
# Blocking is therefore not a curiosity running alongside the chromatic
# number, it is the FIRST NECESSARY CONDITION on the way to chi >= 6 -- a gate
# every candidate has to pass before any colouring argument starts.
#
# And the only 5-chromatic graph anyone has fails it outright. de Grey's G
# lives over Q(sqrt3, sqrt5, sqrt7, sqrt11), and a multiquadratic field never
# blocks (recorded above). Not "has not been shown to block": cannot.

SIX_CHROMATIC_MUST_BLOCK = {
    "statement": "a coset colouring with n colours is an n-colouring, so "
                 "chi >= n+1 forces the edge module to admit no homomorphism "
                 "to Z/n that is nonzero on every edge vector",
    "at_n": 5,
    "consequence": "every 6-chromatic unit-distance graph is blocked",
    "why_it_bites": "de Grey's G is multiquadratic, and a multiquadratic "
                    "field provably never blocks, so the only known "
                    "5-chromatic graph fails the gate",
}


# -- blocking is invariant under a global rotation --------------------------
#
# If u is a unit of the field then multiplication by u carries the module M
# isomorphically onto uM, and phi -> phi . u is a bijection between the
# homomorphisms out of uM and those out of M carrying nonzero to nonzero. So
#
#     a rotated copy of a graph blocks exactly when the graph does.
#
# Small, but it does real work twice below: it turns one measurement on the
# Moser spindle into a statement about every 7-vertex 4-critical graph, and it
# lets the blocking of U be read off a set of directions with the outer
# rotation divided out.

BLOCKING_IS_ROTATION_INVARIANT = {
    "statement": "phi -> phi . u is a bijection between the homomorphisms out "
                 "of uM and those out of M, preserving which vectors are sent "
                 "to zero",
    "consequence": "blocking is a property of a graph up to isometry, so a "
                   "single measurement settles a whole rotation class",
}


# -- every triangle of unit steps is a 60-degree pair ------------------------
#
# Three points at mutual distance 1: |u| = |v| = |u - v| = 1 expands to
# 2 - u.vbar - ubar.v = 1, so u.vbar + ubar.v = 1. Put t = u.vbar; then
# |t| = 1 and t + tbar = 1, which forces t to be a primitive sixth root of
# unity. Hence
#
#     u = zeta_6^{+-1} v for every triangle of unit steps,
#
# and a step set closed under zeta_6 carries triangles no matter what its
# denominators are. This matters because zeta_6 is a unit at 29, so the
# denominator-29 steps are closed under it: the blocking directions are not
# some rigidity-free fringe, they support the same triangles the cheap steps
# do. Measured: the 300 denominator-29 steps carry 300 such pairs.
#
# It also pins the rhombus. Its tip is u + v with v = zeta_6 u, so
# |u + v|^2 = 2 + (u.vbar + ubar.v) = 3 -- ALWAYS sqrt3, whatever u is.

TRIANGLES_ARE_SIXTY_DEGREE_PAIRS = {
    "statement": "|u| = |v| = |u-v| = 1 forces u.vbar + ubar.v = 1, hence "
                 "u/v is a primitive sixth root of unity",
    "consequence": "any zeta_6-closed step set carries triangles, the "
                   "denominator-29 set included",
    "rhombus_tip": "|u + zeta_6 u|^2 = 3 for every unit u",
    "measured_triangles_among_300": 300,
}


# -- the spindle rotation is forced, and the spindle does not block ----------
#
# A Moser spindle is two rhombi sharing an apex, tips at distance sqrt3 from
# it by the identity above, joined by a unit edge. If the arms are the rhombi
# on u and on v then the closing edge has length |u - v| sqrt3, so
#
#     |u - v|^2 = 1/3,  u.vbar + ubar.v = 5/3,  v = rho^{+-1} u
#     with rho = (5 +- sqrt-11)/6.
#
# No freedom at all: the arm rotation is a single algebraic number, and the
# spindle is unique up to isometry. Combined with rotation invariance, ONE
# measurement settles the whole class -- and the measurement says the spindle
# admits a coset 5-colouring. Its 14 projective directions are not enough.
#
#     NO 7-VERTEX 4-CRITICAL UNIT-DISTANCE GRAPH BLOCKS.
#
# Which is why the blocking keeps dying in the critical core: every
# construction here whose 4-chromaticity comes from a spindle has a core that
# is a spindle, and a spindle cannot block.

SPINDLE_ROTATION_IS_FORCED = {
    "derivation": "closing edge |u-v| sqrt3 = 1 gives u.vbar + ubar.v = 5/3",
    "rotation": "(5 +- sqrt-11)/6, the only solution",
    "spindle_directions": 14,
    "blocks": False,
    "consequence": "no 7-vertex 4-critical unit-distance graph blocks, since "
                   "the spindle is unique up to isometry and blocking is "
                   "rotation invariant",
}


# -- how few directions can block -------------------------------------------
#
# Blocking at n = 5 is covering the points of PG(r-1,5) by the hyperplanes
# d-perp. The cheapest cover of a projective space over F_q by hyperplanes is
# a pencil: fix a codimension-2 subspace, take the q+1 hyperplanes through it,
# and every point is caught. So
#
#     a blocked graph has at least 6 distinct edge directions,
#
# and six suffice only when their reductions mod 5 span a rank-2 space and
# occupy all six points of that PG(1,5). The bound is weak but it is the right
# shape: blocking is a statement about how the directions sit mod 5, not about
# how many there are. The spindle has 14 and fails; the denominator-29 set has
# 300 and succeeds.

BLOCKING_NEEDS_SIX_DIRECTIONS = {
    "bound": 6,
    "reason": "a pencil of q+1 hyperplanes through a fixed codimension-2 "
              "subspace is the cheapest cover of PG(r-1,q)",
    "tight_when": "the six directions span rank 2 mod 5 and occupy all six "
                  "points of that projective line",
}


def denominator_29_directions(box: int = 3) -> List[Tuple[int, ...]]:
    """The unit steps of Q(zeta_7) of denominator exactly 29, zeta_6-closed.

    29 is the least rational prime that splits completely in Q(zeta_7), which
    is what makes denominator-29 steps the cheapest blocking ones. Each is
    produced by Hilbert 90 as a/conj(a) over a box of coefficients, then
    multiplied through by the powers of zeta_6 -- legitimate because zeta_6 is
    a unit at 29, so the denominator survives, and necessary because triangles
    only exist between 60-degree pairs.

    Returned as primitive integer vectors in the Q(zeta_21) basis, ready for
    `has_homomorphism`. With the default box: 50 generators, 300 directions,
    all projectively distinct, and they block.
    """
    from .cyclotomic import CycloField

    K = CycloField(21)
    d = K.degree

    def inv(a):
        rows = [list(K.mul(a, tuple(Fraction(1 if j == i else 0)
                                    for j in range(d)))) for i in range(d)]
        M = [[rows[j][i] for j in range(d)] + [Fraction(1 if i == 0 else 0)]
             for i in range(d)]
        for c in range(d):
            p = next(r for r in range(c, d) if M[r][c])
            M[c], M[p] = M[p], M[c]
            s = Fraction(1) / M[c][c]
            M[c] = [v * s for v in M[c]]
            for r in range(d):
                if r != c and M[r][c]:
                    f = M[r][c]
                    M[r] = [x - f * y for x, y in zip(M[r], M[c])]
        return tuple(M[i][d] for i in range(d))

    def den(t):
        out = 1
        for x in t:
            out = out * x.denominator // gcd(out, x.denominator)
        return out

    z6 = K.neg(K.mul(K.zeta(7), K.zeta(7)))
    steps = set()
    for coeffs in itertools.product(range(-box, box + 1), repeat=4):
        if not any(coeffs):
            continue
        a, p = K.zero(), K.rational(1)
        for c in coeffs:
            a = K.add(a, tuple(Fraction(c) * x for x in p))
            p = K.mul(p, K.zeta(3))
        try:
            u = K.mul(a, inv(K.conj(a)))
        except (StopIteration, ZeroDivisionError):
            continue
        if K.norm2(u) != K.rational(1) or den(u) != 29:
            continue
        v = u
        for _ in range(6):
            steps.add(v)
            v = K.mul(v, z6)

    scale = 1
    for v in steps:
        scale = scale * den(v) // gcd(scale, den(v))
    out = []
    for v in sorted(steps):
        w = tuple(int(x * scale) for x in v)
        g = 0
        for t in w:
            g = gcd(g, abs(t))
        w = tuple(t // g for t in w) if g > 1 else w
        if w not in out:
            out.append(w)
    return out


# -- the first 5-chromatic blocked unit-distance graph ----------------------
#
# Let w run over the denominator-29 unit steps and set
#
#     U = G u {w.G},   each w.G the rotation of G about the origin by w.
#
# chi(U) >= 5 because U contains G. For the blocking, two levers: it is
# monotone in the direction set, so a blocking SUBSET is enough, and it is
# rotation invariant, so a global factor divides out.
#
# G contains a rotated copy r.Y of Y, and Y keeps all six hexagonal unit edges
# at the origin -- de Grey deletes only (1/3, 0) and (-1/3, 0), and the origin
# is measured here to have 60 neighbours, among them (+-1, 0) and
# (+-1/2, +-sqrt3/2). So U's directions contain r.{w . zeta_6^k}, which blocks
# exactly when {w . zeta_6^k} does, and that set is the 300 above. Hence
#
#     U IS 5-CHROMATIC AND BLOCKED -- the first graph that is both.
#
# STATED FOR WHAT IT IS, again. U passes the gate of SIX_CHROMATIC_MUST_BLOCK;
# it is not 6-chromatic, and nothing here says it is. What it settles is that
# the gate is passable at five colours at all, which no previously known
# object did.
#
# And the blocking is still not load bearing. Strip a rotated construction to
# a 4-critical subgraph and the copies do not hold each other up: measured on
# the 367-point spindle union, the core is 7 points, 11 edges, 7 directions --
# one spindle, which by SPINDLE_ROTATION_IS_FORCED cannot block. The copies
# are each 4-chromatic alone, so the core is free to pick one and drop the
# rest. That is the obstruction to beat, and it is now a sharp question:
#
#     CAN A CRITICAL UNIT-DISTANCE GRAPH BLOCK?

FIRST_FIVE_CHROMATIC_BLOCKED = {
    "graph": "U = G u {w.G : w a denominator-29 unit step of Q(zeta_7)}",
    "chi": ">= 5, since U contains de Grey's G",
    "blocked": True,
    "via": "directions contain r.{w.zeta_6^k}; blocking is monotone in the "
           "direction set and invariant under the global rotation r",
    "y_origin_neighbours": 60,
    "blocking_subset": 300,
    "honest": "U passes the necessary gate for chi >= 6; it is not claimed to "
              "be 6-chromatic",
    "blocks_at_every_modulus_to_five": True,
    "why": "its directions contain r.{w.zeta_6^k}, which is the "
           "denominator-29 set up to a global rotation, and that set blocks "
           "at n = 2, 3, 4 and 5; rotation preserves blocking at every n",
    "standing": "the only object here that is 5-chromatic AND meets every "
                "necessary condition known for a sixth colour: blocked at "
                "2, 3, 4, 5, and surviving the Cayley screen at every modulus "
                "from 5 to 20",
}

CRITICAL_CORE_COLLAPSES = {
    "construction": "Moser spindle plus its images under 144 blocking steps",
    "union": {"points": 367, "edges": 671, "directions": 427, "chi": 4,
              "blocked": True},
    "four_critical_core": {"points": 7, "edges": 11, "directions": 7,
                           "blocked": False},
    "why": "each rotated copy is 4-chromatic on its own, so the core keeps one "
           "and discards the rest",
    "open": "can a critical unit-distance graph block?",
}


# -- blocking is decided by the field, before any graph is drawn ------------
#
# Reduce mod 5. A coset 5-colouring of a graph with edge module M is an
# F_5-linear functional on M/5M nonzero on every edge vector, and when M is
# 5-maximal (M tensor Z_5 = O tensor Z_5) that is a functional on the algebra
#
#     A = O/5 = prod_i F_{5^{f_i}},      sum f_i = [K:Q],
#
# K the field generated by the edge vectors, sigma its complex conjugation.
# Edge vectors are unit steps, u.sigma(u) = 1, so their reductions land in
#
#     N = { x in A : x.sigma(x) = 1 },
#
# and by Hilbert 90 every element of N lifts, so N is exactly the set of
# reductions available. Scaling the whole graph by lambda multiplies every
# direction by it, which is a linear automorphism of A permuting hyperplanes,
# so the question is scale-free. A graph blocks only if its directions meet
# every hyperplane of A, hence only if N does.
#
# THE ORBIT-WISE REDUCTION. sigma permutes the factors of A, and x.sigma(x)=1
# is componentwise, so N factors along the sigma-ORBITS: N = prod_orbits N_i.
# A functional supported on one orbit and zero elsewhere takes the value that
# orbit's functional takes. Therefore
#
#     IF ONE ORBIT ADMITS A FUNCTIONAL NONZERO ON ALL OF ITS N_i,
#     THE WHOLE FIELD ADMITS ONE, AND NO GRAPH OVER K BLOCKS.
#
# Blocking needs EVERY orbit to block alone, and an orbit is one number: the
# residue degree f, with sigma either fixing the prime (f even, sigma the
# unique involution Frob^{f/2}) or swapping a pair. Every type of degree 2, 4
# and 6 was decided by exhaustion over A:
#
#     fixed f=2   |N| = 6      3 hyperplanes miss       no
#     fixed f=4   |N| = 26    13 hyperplanes miss       no
#     fixed f=6   |N| = 126   none miss                 YES
#     swapped f=1 |N| = 4      4 hyperplanes miss       no
#     swapped f=2 |N| = 24    12 hyperplanes miss       no
#     swapped f=3 |N| = 124   none miss                 YES
#
# The two that block are exactly the two with RESIDUE DEGREE 3 OVER THE REAL
# SUBFIELD F = K n R: a sigma-fixed prime of degree f lies over a prime of F
# of degree f/2, a swapped pair over one of degree f. So:
#
#     THEOREM. Let Gamma be a unit-distance graph whose edge module is
#     5-maximal and whose edge vectors are integral at 5. If EITHER K/F
#     ramifies at some prime above 5, OR some prime of F = K n R above 5 has
#     residue degree at most 2, then Gamma has a coset 5-colouring, hence
#     chi(Gamma) <= 5.
#
#     COROLLARY. A 6-chromatic unit-distance graph has K/F unramified above 5
#     AND residue degree at least 3 at every prime of F above 5.
#
# THE HYPOTHESIS CAN BE REMOVED, and replaced by a second condition that is
# itself necessary. Suppose K/F RAMIFIES at a prime p above 5. Then the
# residue extension k(p)/k(p n F) is trivial, so sigma -- which generates
# Gal(K/F) -- acts trivially on O/p. For a unit step, x.sigma(x) = 1 reduces
# to xbar^2 = 1, hence
#
#     N mod p is contained in {+1, -1},
#
# two elements. Take any F_5-functional psi on the residue field with
# psi(1) != 0 and compose it with A -> O/p: the result sends every element of
# N to +-psi(1), never to 0. A coset colouring exists. So
#
#     IF K/F RAMIFIES ABOVE 5, NO GRAPH OVER K BLOCKS.
#
# When K/F is unramified above 5 the residue extension is trivial or degree 2
# and the analysis is exactly the orbit classification above, at the residue
# degree f of p over F. Ramification of 5 in F/Q by itself changes nothing --
# only the residue degree does. Verified by exhaustion in three cases where 5
# ramifies in K: Q(zeta_5) (11 of 156 hyperplanes miss N), Q(zeta_15) (3 of
# 97656) and Q(zeta_20) (4 of 97656). In each, K/F is ramified above 5, so
# each was predicted unable to block before it was computed.
#
#     COROLLARY. Every 6-chromatic unit-distance graph has residue degree at
#     least 3 at every prime of F above 5 -- every residue field of F at 5 has
#     at least 125 elements.
#
# The integrality hypothesis is automatic when every prime above 5 is
# sigma-fixed: then 2 v_p(u) = v_p(u.sigma(u)) = 0 for every unit step.
#
# This subsumes the multiquadratic result recorded above. A multiquadratic
# field has elementary abelian Galois group, so every decomposition group is
# cyclic of order at most 2, so f <= 2 and the residue degree over F is 1 --
# below the bound, every time. de Grey's G was never going to block.
#
# And it agrees with every measurement here:
#
#     Q(zeta_3), Q(zeta_3, sqrt-m) for m = 1,2,5,6,7,10,11,13,15   degree <= 4
#         -> cannot block; measured, each admits a coset colouring
#     Q(zeta_7), Q(zeta_9), Q(zeta_21)   ord(5) = 6 and -1 in <5>, so one
#         sigma-fixed prime of degree 6, residue degree 3 over F
#         -> can block; measured, the 300 denominator-29 directions do
#
# Q(zeta_7) is the smallest cyclotomic field that can block: 3 and 4 give
# degree 2, 5 ramifies, and 7 is next. That is the same 7 that put 29 --
# the least prime splitting completely in Q(zeta_7) -- at the bottom of the
# blocking denominators, arrived at from the opposite direction.

RESIDUE_DEGREE_THREE = {
    "theorem": "if some prime of F = K n R above 5 has residue degree <= 2, "
               "the graph has a coset 5-colouring, so chi <= 5",
    "corollary": "every 6-chromatic unit-distance graph has K/F unramified "
                 "above 5 and residue degree >= 3 at every prime of its real "
                 "subfield above 5",
    "ramified_case": "if K/F ramifies above 5 the residue extension is "
                     "trivial, so sigma acts trivially there and N mod p "
                     "collapses to {+1,-1}; a functional through the residue "
                     "field misses it, so no graph over K blocks",
    "verified_ramified": {"Q(zeta_5)": "11 of 156 hyperplanes miss N",
                          "Q(zeta_15)": "3 of 97656",
                          "Q(zeta_20)": "4 of 97656"},
    "hypotheses": ["the edge module is 5-maximal",
                   "the edge vectors are integral at 5, automatic when every "
                   "prime above 5 is fixed by complex conjugation"],
    "orbit_reduction": "N factors along the sigma-orbits, so a functional "
                       "supported on one orbit decides the whole field",
    "decided_by_exhaustion": {"fixed": {2: False, 4: False, 6: True},
                              "swapped": {1: False, 2: False, 3: True}},
    "subsumes": "multiquadratic fields have f <= 2, hence residue degree 1 "
                "over F -- de Grey's G could never have blocked",
    "smallest_cyclotomic": 7,
}


def cyclotomic_can_block(n: int) -> dict:
    """Decide `RESIDUE_DEGREE_THREE` for Q(zeta_n) from the arithmetic of 5.

    Write n = 5^a m with 5 not dividing m. The inertia group at 5 is
    (Z/5^a)* x {1} and the decomposition group is that times the subgroup
    generated by Frobenius, 5 mod m. Complex conjugation is (-1, -1), so

        K/F ramifies above 5  <=>  conjugation lies in inertia  <=>  m | 2,

    and in that case the residue extension is trivial, N mod p collapses to
    {+1,-1}, and no graph over K blocks. Otherwise the residue degree is
    f = ord(5 mod m), conjugation fixes the primes exactly when -1 is a power
    of 5 mod m, and the residue degree over F is f/2 when fixed and f when
    swapped.

    An earlier version returned "cannot block" for every n divisible by 5, on
    the grounds that 5 ramifies. That is wrong: ramification of 5 in K/Q is
    not ramification of K/F. Q(zeta_35) has f = ord(5 mod 7) = 6 with the
    primes sigma-fixed, hence residue degree 3 over F, and the blanket verdict
    called it unable to block.

    When a > 0 the local ring is O_p/p^{e} rather than a field, so the orbit
    classification -- which is about residue fields -- only rules out the
    functionals that factor through O/p. A verdict of True there means "not
    obstructed by the residue field", flagged as `residue_field_only`.
    """
    a, m = 0, n
    while m % 5 == 0:
        m //= 5
        a += 1
    if m <= 2:
        return {"n": n, "ramified_over_F": True, "can_block": False,
                "reason": "K/F ramifies above 5, so N mod p lies in {+1,-1}"}
    f, x = 1, 5 % m
    while x != 1 % m:
        x = x * 5 % m
        f += 1
    grp = {pow(5, k, m) for k in range(f)}
    fixed = (m - 1) % m in grp
    over_real = f // 2 if fixed else f
    out = {"n": n, "degree": f, "conjugation_fixes_primes": fixed,
           "residue_degree_over_F": over_real,
           "ramified_over_F": False,
           "can_block": over_real >= 3}
    if a:
        out["residue_field_only"] = True
        out["note"] = ("5 ramifies in K/Q but not in K/F, so only the "
                       "functionals through the residue field are decided")
    return out


def _finite_field(f: int):
    """Multiplication, one and powering on F_{5^f}, basis 1, t, .., t^{f-1}."""
    poly = None
    for tail in itertools.product(range(5), repeat=f):
        cand = list(tail) + [1]
        free = True
        for g in range(1, f // 2 + 1):
            for t2 in itertools.product(range(5), repeat=g):
                div = list(t2) + [1]
                r = cand[:]
                for i in range(len(r) - 1, g - 1, -1):
                    c = r[i]
                    if c:
                        for j in range(g + 1):
                            r[i - g + j] = (r[i - g + j] - c * div[j]) % 5
                if not any(r[:g]):
                    free = False
                    break
            if not free:
                break
        if free:
            poly = cand
            break
    if poly is None:
        raise RuntimeError(f"no irreducible of degree {f}")

    def mul(a, b):
        r = [0] * (2 * f - 1)
        for i, x in enumerate(a):
            if x:
                for j, y in enumerate(b):
                    if y:
                        r[i + j] = (r[i + j] + x * y) % 5
        for i in range(2 * f - 2, f - 1, -1):
            c = r[i]
            if c:
                for j in range(f + 1):
                    r[i - f + j] = (r[i - f + j] - c * poly[j]) % 5
        return tuple(r[:f])

    one = tuple([1] + [0] * (f - 1))

    def power(a, e):
        out, base = one, a
        while e:
            if e & 1:
                out = mul(out, base)
            base = mul(base, base)
            e >>= 1
        return out

    return mul, one, power


def orbit_can_block(kind: str, f: int) -> bool:
    """Decide one sigma-orbit of primes above 5 by exhaustion over its algebra.

    `kind` is "fixed" (one prime of even residue degree f, conjugation acting
    as Frob^{f/2}) or "swapped" (a conjugate pair, each of residue degree f).
    The orbit blocks when every F_5-hyperplane of its part of A = O/5 meets its
    norm-one set. By the orbit-wise reduction a field blocks only if every one
    of its orbits does, so this decides fields wholesale.

    Cost is 5^d with d the orbit's degree, so keep d at 6 or below in tests.
    """
    if kind == "fixed" and f % 2:
        raise ValueError("a sigma-fixed prime has even residue degree")
    d = f if kind == "fixed" else 2 * f
    mul, one, power = _finite_field(f)
    if kind == "fixed":
        q = 5 ** (f // 2)
        N = [a for a in itertools.product(range(5), repeat=f)
             if mul(a, power(a, q)) == one]
    else:
        N = []
        for a in itertools.product(range(5), repeat=f):
            if not any(a):
                continue
            for b in itertools.product(range(5), repeat=f):
                if mul(a, b) == one:
                    N.append(tuple(a) + tuple(b))
                    break
    seen = set()
    for c in itertools.product(range(5), repeat=d):
        if not any(c) or c in seen:
            continue
        for k in range(1, 5):
            seen.add(tuple((k * x) % 5 for x in c))
        if not any(sum(x * y for x, y in zip(c, u)) % 5 == 0 for u in N):
            return False
    return True


# -- the condition at 3: when a rhombus chain can close --------------------
#
# A rhombus 0, w, zeta_6 w, w(1 + zeta_6) forces its tip to the apex's colour
# at three colours, and |1 + zeta_6| = sqrt3 whatever w is. Chain k of them in
# directions w_1, .., w_k and every partial sum is forced to the origin's
# colour; the chain CLOSES into a 4-chromatic graph when the last one is also
# adjacent to the origin, which is
#
#     | w_1 + .. + w_k |^2 = 1/3.
#
# Now let q be a prime above 3 with qbar = q. Every unit step has
# v_q(u) + v_q(ubar) = v_q(1) = 0, and v_q(ubar) = v_q~(u) = v_q(u), so
# v_q(u) = 0. A sum of such has v_q >= 0, while 1/3 has v_q = -e < 0. Hence
#
#     IF EVERY PRIME ABOVE 3 IS FIXED BY CONJUGATION, NO RHOMBUS CHAIN EVER
#     CLOSES -- at any length k, over any such field.
#
# This generalises the no-Eisenstein-spindle result from k = 2 to every k, and
# it explains the Moser spindle rather than merely permitting it:
# rho = (5 + sqrt-11)/6 has valuation +1 at one prime above 3 of Q(sqrt-11)
# and -1 at its conjugate, which is possible only because 3 SPLITS there. A
# chain needs some prime of F above 3 to split in K.
#
# Stated for what it is: this closes the rhombus-chain mechanism, which is how
# the Moser spindle and every spindle-type construction here works. It does
# not claim that no 4-chromatic unit-distance graph exists over such a field
# by some other route.
#
# The two conditions pull in different directions. Q(zeta_21) blocks -- one
# sigma-fixed prime above 5 of residue degree 6 -- but 3 is totally ramified
# with a single prime, so no chain closes there. Sweeping the cyclotomic
# fields that carry zeta_3 at all:
#
#     Q(zeta_9), Q(zeta_18), Q(zeta_21), Q(zeta_27), Q(zeta_42)  block, no chain
#     Q(zeta_24), Q(zeta_48)                                      chain, no block
#     Q(zeta_33), degree 20                                       BOTH, and least
#
# Q(zeta_33) = Q(zeta_3, zeta_11) carries zeta_3 for the triangles and
# sqrt-11 for the Moser rotation, has residue degree 10 over F at 5, and has
# its two primes above 3 swapped by conjugation. It is the smallest
# cyclotomic field where a chain construction and a blocked one can be the
# same object.

CHAIN_NEEDS_THREE_TO_SPLIT = {
    "closing_condition": "|w_1 + .. + w_k|^2 = 1/3",
    "theorem": "if every prime above 3 is fixed by complex conjugation then "
               "every unit step has v_q = 0, so any sum has v_q >= 0 while "
               "1/3 has v_q < 0 -- no chain closes, at any length",
    "generalises": "the no-Eisenstein-spindle result, from k = 2 to every k",
    "why_moser_works": "rho = (5 + sqrt-11)/6 has valuation +1 and -1 at the "
                       "two primes above 3 of Q(sqrt-11), which split",
    "scope": "closes the rhombus-chain mechanism, not every possible route to "
             "a 4-chromatic graph",
}

SMALLEST_FIELD_FOR_BOTH = {
    "field": "Q(zeta_33) = Q(zeta_3, zeta_11), degree 20",
    "residue_degree_over_F_at_5": 10,
    "three_splits": True,
    "carries": ["zeta_3 for triangles", "sqrt-11 for the Moser rotation"],
    "blocks_but_no_chain": [9, 18, 21, 27, 42],
    "chain_but_no_block": [24, 48],
}


def cyclotomic_chain_closes(n: int) -> bool:
    """Whether a rhombus chain can close over Q(zeta_n).

    True exactly when some prime above 3 is moved by complex conjugation.
    Writing n = 3^a m with m prime to 3, the decomposition group at 3 is
    (Z/3^a)* times the group generated by Frobenius = 3 mod m, so conjugation
    lies in it iff -1 is a power of 3 mod m.
    """
    m, a = n, 0
    while m % 3 == 0:
        m //= 3
        a += 1
    if a == 0:
        raise ValueError("Q(zeta_n) needs zeta_3 to carry a rhombus at all")
    if m == 1:
        return False
    f, x = 1, 3 % m
    while x != 1 % m:
        x = x * 3 % m
        f += 1
    return (m - 1) % m not in {pow(3, k, m) for k in range(f)}


# -- chains of three exist, and are still not enough ------------------------
#
# Over Q(zeta_33) the closing condition |1 + a + b|^2 = 1/3, equivalently
#
#     Re(a) + Re(b) + Re(a.bbar) = -2/3,
#
# has solutions. Two were built: 10 points, 19 edges, chi = 4 -- genuinely new
# 4-chromatic unit-distance graphs, three chained rhombi rather than two
# paired ones, and not a spindle. The k = 2 control returns exactly the two
# rotations (5 +- sqrt-11)/6, as it must.
#
# And they still do not block. Their 14 directions have module rank 4: the
# steps landed inside Q(zeta_3, sqrt-11), the spindle's own field, which by
# the residue-degree theorem can never block whatever is built over it. The
# graph is new; the arithmetic it sits on is not.
#
# Recorded as the sharp form of what is missing. A chain whose steps stay in
# the spindle subfield is a different graph over the same dead field. What is
# needed is one whose steps LEAVE it -- 964 of the 986 steps enumerated here
# do lie outside, so the search is not vacuous.

THREE_CHAINS_EXIST_OVER_ZETA33 = {
    "field": "Q(zeta_33), degree 20",
    "condition": "Re(a) + Re(b) + Re(a.bbar) = -2/3",
    "k2_control": "2 rotations, exactly (5 +- sqrt-11)/6",
    "graphs": {"points": 10, "edges": 19, "chi": 4, "directions": 14,
               "module_rank": 4},
    "blocks": False,
    "why": "the steps fell inside Q(zeta_3, sqrt-11), which the residue-degree "
           "theorem closes permanently",
    "steps_outside_that_subfield": "964 of 986",
}


# -- rotating about a shared point gives a bouquet, not a structure ---------
#
# The 367-point union of the spindle with its images under 144 blocking steps
# is 4-chromatic and blocked, and its 4-critical core is one spindle. The
# obvious repair is to delete a hitting set for the spindles, so no copy is
# 4-chromatic alone and any surviving core has to span copies.
#
# The hitting set has size ONE. All 145 copies are rotations about the origin,
# so they share exactly that vertex, and deleting it leaves 366 points that
# are 3-colourable. The union was never an interlocking structure -- it is a
# bouquet of spindles tied at a point, and its whole chromatic number lives at
# the knot.
#
# Which says what any repair has to do: rotate about a point the copies do NOT
# share, so they overlap in many vertices, the way de Grey's G is two copies
# of Y rotated about (-2, 0) rather than about a vertex of Y.

ROTATION_ABOUT_A_SHARED_POINT_IS_A_BOUQUET = {
    "union": {"points": 367, "edges": 671, "chi": 4, "blocked": True},
    "hitting_set_for_all_145_spindles": 1,
    "after_deleting_it": {"points": 366, "three_colourable": True},
    "reading": "the copies share only the centre of rotation, so the union is "
               "a bouquet tied at one vertex, not an interlocking structure",
    "repair": "rotate about a point the copies do not share, as de Grey does "
              "with (-2, 0)",
}


# -- the three-rhombus chain, parametrised -----------------------------------
#
# The chain closes when |1 + a + b|^2 = 1/3 for unit steps a, b. Expanding,
# with c = 1 + a and m0 = |c|^2 = 2 + r where r = a + abar, the closing
# quadratic cbar.b^2 - T.b + c = 0 has T = -2/3 - m0 and discriminant
#
#     Delta = T^2 - 4 m0 = r^2 + (4/3) r - 8/9,
#
# which depends ONLY on the real part of a. K = F(sqrt-3), so Delta -- negative
# at every real place -- is a square in K exactly when 3(8 - 12r - 9r^2) is a
# square in F; and a itself exists as a unit step with a + abar = r exactly
# when 3(4 - r^2) is. So the whole question is a curve:
#
#     y1^2 = 3(4 - r^2),     y2^2 = 3(8 - 12 r - 9 r^2).
#
# The first conic carries the rational point (r, y1) = (1, 3), so it is
# rationally parametrised, and substituting collapses the pair to ONE quartic:
#
#     r = (m^2 - 6m - 3)/(m^2 + 3),   y1 = 3 + m(r - 1),
#     V(m) = -39 m^4 + 540 m^3 - 666 m^2 - 324 m + 297,   y2 = sqrt(V)/(m^2+3),
#     a = (r + y1.sqrt-3/3)/2,   b = (-8/3 - r + y2.sqrt-3/9)/(2(1 + abar)).
#
# Two conditions then come for free. r + 2 = 3(m-1)^2/(m^2+3) and
# 2 - r = (m+3)^2/(m^2+3) are both non-negative, so |r| <= 2 at EVERY real
# embedding and the unit step a always exists. And a closing chain forces some
# prime above 3 to be moved by conjugation, so building the chain settles the
# condition at 3 instead of having to impose it. Hence
#
#     EVERY REAL m WITH V(m) > 0 GIVES A CHAIN OF THREE RHOMBI IN THE PLANE,
#     over the field K = Q(m, sqrt(V(m)), sqrt-3).
#
# Verified numerically to machine precision -- |a| = |b| = 1 and
# |1 + a + b|^2 = 1/3 -- and then exactly, in a degree-12 tower.
#
# THE FIELD IS NOW A CHOICE. Taking m cubic makes F = Q(m, sqrt V) a totally
# real sextic, and the residue degrees at 5 are read off the factorisation of
# prod_i (X^2 - V(m_i)) mod 5. Among the totally real cubics with V totally
# positive, 40 give a field where every prime above 5 has residue degree at
# least 3 -- blocking-capable by the theorem above. Built over
# T^3 - 9T^2 + 14T + 8, the chain is
#
#     10 points, 16 edges, chi = 4, 20 directions, MODULE RANK 6
#
# the first 4-chromatic graph here whose directions escape the spindle's
# rank-4 field, and the arithmetic no longer obstructs. It still admits a
# coset colouring: 20 directions do not cover PG(5,5).
#
# And lengthening the chain does not help, for a reason worth recording. The
# rhombus on w has edges w, zeta_6 w and diagonal w(1 - zeta_6) = w.zeta_6bar,
# so a step contributes exactly its zeta_6-ORBIT, three projective directions.
# Splitting w into w.zeta_6 and w.zeta_6bar -- always possible, since
# zeta_6 + zeta_6bar = 1 -- keeps the same orbit: measured, 20 directions at
# k = 3 and still 20 at k = 32, over 77 points and 161 edges. New directions
# need new orbits, which the chain does allow, since only the closing sum is
# constrained and w_1 .. w_{k-2} are free.

CHAIN_PARAMETRISATION = {
    "closing": "|1 + a + b|^2 = 1/3",
    "discriminant": "Delta = r^2 + 4r/3 - 8/9, depending only on r = a + abar",
    "curve": ["y1^2 = 3(4 - r^2)", "y2^2 = 3(8 - 12r - 9r^2)"],
    "rational_point": "(r, y1) = (1, 3) on the first conic",
    "parametrisation": {
        "r": "(m^2 - 6m - 3)/(m^2 + 3)",
        "y1": "3 + m(r - 1)",
        "V": "-39 m^4 + 540 m^3 - 666 m^2 - 324 m + 297",
        "y2": "sqrt(V)/(m^2 + 3)",
        "a": "(r + y1 sqrt-3 / 3)/2",
        "b": "(-8/3 - r + y2 sqrt-3 / 9) / (2(1 + abar))",
    },
    "free": ["r + 2 = 3(m-1)^2/(m^2+3) >= 0 and 2 - r = (m+3)^2/(m^2+3) >= 0, "
             "so |r| <= 2 at every real place",
             "a closing chain forces a prime above 3 to move, so building one "
             "settles the condition at 3"],
    "consequence": "every real m with V(m) > 0 gives a chain, over "
                   "K = Q(m, sqrt V(m), sqrt-3)",
}

CHAIN_OVER_A_CHOSEN_FIELD = {
    "cubic": "T^3 - 9T^2 + 14T + 8",
    "tower": "L = Q(m), F = L(sqrt V) totally real sextic, K = F(sqrt-3)",
    "blocking_capable_cubics_found": 40,
    "graph": {"points": 10, "edges": 16, "chi": 4, "directions": 20,
              "module_rank": 6},
    "blocks": False,
    "reading": "the first 4-chromatic graph here with module rank above 4; the "
               "arithmetic no longer obstructs, the direction count does",
}

CHAIN_LENGTH_ADDS_NO_DIRECTIONS = {
    "reason": "the rhombus on w has edges w, zeta_6 w and diagonal "
              "w(1 - zeta_6) = w.zeta_6bar, so a step contributes exactly its "
              "zeta_6-orbit",
    "splitting": "w = w.zeta_6 + w.zeta_6bar always works, and stays in the "
                 "orbit",
    "measured": {"k": [3, 32], "points": [10, 77], "edges": [16, 161],
                 "directions": [20, 20]},
    "what_does_add": "steps in new orbits, which the chain allows since only "
                     "the closing sum is constrained",
}


# -- blocking that carries weight: one chain, every edge load bearing -------
#
# The field is chosen first. Over the degree-12 tower K = Q(m, sqrt V(m),
# sqrt-3) with m a root of T^3 - 9T^2 + 14T + 8, every prime of the real
# subfield above 5 has residue degree at least 3, so the residue-degree
# theorem does not close it -- and measured directly, the 450 directions of
# its 75 zeta_6-orbits BLOCK, at rank 12. The material is there before any
# graph is drawn.
#
# Then the chain is grown into it. The move is to replace a step w by three
# unit steps summing to w: any u leaves z = w - u to be split as v1 + v2,
# which is a lookup once the pairwise sums of the enumerated steps are
# tabulated. The total sum is untouched, so |sum w_i|^2 = 1/3 survives --
# asserted exactly at every round -- so the closing edge survives and chi
# stays 4, while each replacement brings new orbits into the direction set.
#
#     round 22:  47 steps, 25 orbits, 150 directions, rank 12,  BLOCKS
#     graph:     141 points, 236 edges, chi = 4, 152 directions, BLOCKED
#
# Blocking is monotone in the direction set, so the steps' orbits blocking is
# enough to conclude the graph does; the graph's own 152 directions confirm it.
#
# WHY THIS IS DIFFERENT from everything above. The 107-point graph blocked by
# pendants, which change no chromatic number. The 367-point union blocked with
# every edge a spindle edge, but a hitting set for all 145 of its spindles had
# size one -- a bouquet tied at a knot. Here there is one chain, no copies to
# discard and no pendants to strip: every edge is an edge of a rhombus, and
# every rhombus carries one link of the forcing that walks the origin's colour
# out to the far end, where the closing edge contradicts it.

BLOCKING_THAT_CARRIES_WEIGHT = {
    "field": "Q(m, sqrt V(m), sqrt-3), degree 12, m a root of "
             "T^3 - 9T^2 + 14T + 8",
    "field_orbits": {"orbits": 75, "directions": 450, "rank": 12,
                     "block": True},
    "move": "replace a step w by three unit steps summing to w, which leaves "
            "the closing sum untouched and adds zeta_6-orbits",
    "chain": {"steps": 47, "orbits": 25, "directions": 150, "rank": 12,
              "blocks": True},
    "graph": {"points": 141, "edges": 236, "chi": 4, "directions": 152,
              "blocked": True},
    "load_bearing": "one chain, no copies and no pendants: every edge is a "
                    "rhombus edge",
    "but_the_core_collapses": {"points": 10, "edges": 16, "directions": 20,
                               "rank": 6, "blocks": False},
}


# -- retraction: "every rhombus carries a forcing link" was wrong -----------
#
# Predicted, then measured, and the measurement says no. The 4-critical core
# of the 141-point graph is
#
#     10 points, 16 edges, 20 directions, rank 6 -- and it does NOT block,
#
# which is a three-rhombus chain: the profile the k = 3 chain had before any
# growth. So the long chain is not minimal at all, and the blocking is still
# not load bearing in the strict sense. The claim is withdrawn.
#
# The reason is visible once looked for. Every partial sum
# B_j = (1 + zeta_6)(w_1 + .. + w_j) is forced to the origin's colour, so if
# ANY two of them land at distance 1, that pair already contradicts a
# 3-colouring and a shorter chain closes inside the long one. With 47 steps
# there are over a thousand such pairs and some of them hit. Greedy deletion
# then keeps the short one and discards everything else -- the same collapse
# the bouquet showed, arriving by a different route.
#
# The repair is a condition to impose during growth rather than a hope: accept
# a replacement only when no pair (B_i, B_j) other than the closing (B_0, B_k)
# sits at distance 1. Measured with that guard in place, the chain grows
# through 5, 7, 9 steps at ranks 8, 10, 12 with no premature closing.
#
# Recorded because a prediction about a critical core has now failed twice
# here, in two different constructions. They are not worth making.

CORE_COLLAPSE_WAS_PREDICTED_WRONG = {
    "claimed": "every rhombus of the chain carries a forcing link, so the "
               "4-critical core is the whole chain",
    "measured": {"points": 10, "edges": 16, "directions": 20, "rank": 6,
                 "blocks": False},
    "why": "every partial sum B_j is forced to the origin's colour, so any "
           "two of them at distance 1 close a shorter chain inside the long "
           "one",
    "repair": "reject a replacement unless no pair (B_i, B_j) other than the "
              "closing pair is at distance 1",
    "lesson": "a prediction about a critical core has now failed twice here, "
              "in two different constructions",
}


# -- the gate, strengthened: every finite abelian quotient ------------------
#
# A coset colouring is the case G = Z/5 of something much larger. For ANY
# finite abelian G and homomorphism phi from the edge module M to G with
# 0 not in phi(D), colour v by the colour of phi(v - v0) in a proper colouring
# of the Cayley graph Cay(G, phi(D)). Adjacent vertices differ by an element
# of D, phi sends it to a nonzero connection element, so the colours differ:
#
#     chi(Gamma) <= chi(Cay(G, phi(D)))  for every such phi,
#
# and therefore
#
#     EVERY 6-CHROMATIC UNIT-DISTANCE GRAPH HAS chi(Cay(G, phi(D))) >= 6
#     FOR EVERY FINITE ABELIAN QUOTIENT.
#
# Blocking is the bottom rung. At G = Z/5, phi(D) missing 0 means the Cayley
# graph is the complete graph K_5, whose chromatic number is exactly 5 -- so
# ANY valid phi settles it, which is why "no phi to Z/5" was the right
# condition. Above 5 the Cayley graph is no longer complete and its chromatic
# number has to be computed, so the screen keeps biting after blocking stops.
#
# `periodic_screen` runs it by CEGAR: solve for a phi, colour its Cayley
# graph, and if that needs more than five colours exclude this phi and solve
# again. UNSAT at a modulus means no phi exists there at all -- blocking, for
# that n. A hit at any modulus proves the graph 5-colourable outright, and no
# amount of blocking at 5 can save it.

STRONGER_GATE = {
    "statement": "chi(Gamma) <= chi(Cay(G, phi(D))) for every finite abelian "
                 "quotient phi with 0 not in phi(D)",
    "consequence": "a 6-chromatic unit-distance graph has Cayley chromatic "
                   "number at least 6 in every finite abelian quotient",
    "blocking_is_the_case": "G = Z/5, where phi(D) missing 0 makes the Cayley "
                            "graph K_5 and any valid phi settles it",
    "why_it_keeps_biting": "above 5 the Cayley graph is not complete, so its "
                           "chromatic number must be computed rather than "
                           "read off",
    "measured_on_denominator_29": {
        5: "no homomorphism at all -- blocking",
        6: "exhausted: all 48 homomorphisms need more than 5 colours",
        "7..20": "60 homomorphisms tried at each, every one needing more "
                 "than 5",
    },
}


def cayley_chromatic(n: int, conn, cap: int = 5) -> Optional[int]:
    """chi(Cay(Z/n, conn)) when it is at most `cap`, else None."""
    from pysat.solvers import Solver

    S = {s % n for s in conn} | {(-s) % n for s in conn}
    S.discard(0)
    edges = [(v, (v + s) % n) for v in range(n) for s in S if v < (v + s) % n]
    for k in range(2, cap + 1):
        cls = [[1 + v * k + c for c in range(k)] for v in range(n)]
        for a, b in edges:
            for c in range(k):
                cls.append([-(1 + a * k + c), -(1 + b * k + c)])
        with Solver(name="cd19", bootstrap_with=cls) as sv:
            if sv.solve():
                return k
    return None


def periodic_screen(vecs: Sequence[Sequence[int]], n: int, cap: int = 5,
                    rounds: int = 200) -> dict:
    """Look for a periodic `cap`-colouring through the quotient Z/n.

    Returns {"colourable": True, "phi": ..., "cayley_chi": k} on a hit, or
    {"colourable": False, "phis_tried": t, "exhausted": bool}. `exhausted`
    means the solver ran out of homomorphisms rather than out of rounds -- at
    n = 5 that is exactly blocking.
    """
    from pysat.formula import IDPool
    from pysat.solvers import Solver

    vecs = [tuple(v) for v in vecs]
    dim = len(vecs[0])
    pool = IDPool()
    cls = []

    def phi(i, val):
        return pool.id(("phi", i, val))

    for i in range(dim):
        cls.append([phi(i, v) for v in range(n)])
        for a in range(n):
            for b in range(a + 1, n):
                cls.append([-phi(i, a), -phi(i, b)])
    for t, d in enumerate(vecs):
        idx = [i for i in range(dim) if d[i] % n]
        if not idx:
            return {"colourable": False, "phis_tried": 0, "exhausted": True,
                    "reason": f"an edge vector is divisible by {n}"}

        def s(j, val):
            return pool.id(("s", t, j, val))

        for val in range(n):
            cls.append([-phi(idx[0], val), s(0, (val * d[idx[0]]) % n)])
        for j in range(1, len(idx)):
            for prev in range(n):
                for val in range(n):
                    cls.append([-s(j - 1, prev), -phi(idx[j], val),
                                s(j, (prev + val * d[idx[j]]) % n)])
        cls.append([-s(len(idx) - 1, 0)])

    tried = 0
    with Solver(name="cd19", bootstrap_with=cls) as sv:
        for _ in range(rounds):
            if not sv.solve():
                return {"colourable": False, "phis_tried": tried,
                        "exhausted": True}
            m = set(sv.get_model())
            c = tuple(next(v for v in range(n) if phi(i, v) in m)
                      for i in range(dim))
            tried += 1
            conn = {sum(x * y for x, y in zip(c, d)) % n for d in vecs}
            k = cayley_chromatic(n, conn, cap)
            if k is not None:
                return {"colourable": True, "phi": c, "cayley_chi": k,
                        "modulus": n, "phis_tried": tried}
            sv.add_clause([-phi(i, c[i]) for i in range(dim)])
    return {"colourable": False, "phis_tried": tried, "exhausted": False}


# -- how few orbits block, and why a sample cannot answer it ---------------
#
# The first chain reached blocking at 25 zeta_6-orbits, but that was whatever
# the growth happened to pick up. The real minimum matters, because a chain is
# likelier to be critical the shorter it is -- every rhombus has to earn its
# place.
#
# Greedy set cover against 30000 random functionals exhausted the sample at 11
# orbits while `has_homomorphism` still produced one escaping: at rank 12 there
# are 61 million functionals, so a sample says nothing on its own. Driven by
# CEGAR instead -- cover the sample, ASK for a functional the chosen orbits
# miss, add it, cover again -- the loop ends only when none exists, which is
# blocking exactly:
#
#     a blocking set of 22 orbits, 132 directions.
#
# So 25 was close to minimal, not wasteful; and a chain has to reach about 22
# well-chosen orbits, which is the target to steer growth towards rather than
# taking whatever replacement comes first.

MINIMUM_BLOCKING_ORBITS = {
    "field": "the degree-12 tower over T^3 - 9T^2 + 14T + 8",
    "orbits_available": 75,
    "directions_available": 450,
    "greedy_cegar_minimum": {"orbits": 22, "directions": 132},
    "first_chain_reached": {"orbits": 25, "directions": 150},
    "sample_alone_is_useless": "30000 random functionals were all killed by 11 "
                               "orbits while an exact check still found one "
                               "escaping, out of 61 million at rank 12",
}


# -- why every known construction stops at five ----------------------------
#
# A rotation rho has |rho| = 1, so rho.rhobar = 1, and its chord is
# |1 - rho|^2 = 2 - (rho + rhobar). Hence
#
#     the chord is rational  <=>  rho + rhobar is rational
#                            <=>  rho is a root of X^2 - (2-c)X + 1
#                            <=>  [Q(rho) : Q] <= 2.
#
# A ROTATION WITH RATIONAL CHORD LIVES IN A QUADRATIC FIELD. Compose several
# and the field generated is a compositum of quadratic fields -- multiquadratic
# -- whose Galois group is elementary abelian. Every decomposition group at 5
# is then elementary abelian with cyclic quotient by inertia, so the residue
# degree is at most 2, below the bound; and if K/F happens to ramify above 5
# the collapse of N to {+1,-1} settles it instead. Either way:
#
#     A MULTIQUADRATIC UNIT-DISTANCE GRAPH HAS A COSET 5-COLOURING,
#     SO ITS CHROMATIC NUMBER IS AT MOST 5.
#
# And every rotation in de Grey's construction has a rational chord. Measured:
#
#     hexagonal, 60 degrees          |1 - rho|^2 = 1      Q(sqrt-3)
#     Moser, 2 arcsin(1/(2 sqrt3))                 1/3    Q(sqrt-11)
#     Sb, 2 arcsin(1/4)                            1/4    Q(sqrt-15)
#     Ya, pi/2 + arcsin(1/8)                       9/4    Q(sqrt-7)
#     Yb, pi/2 - arcsin(1/8)                       7/4    Q(sqrt-7)
#
# whose compositum is Q(sqrt-3, sqrt-11, sqrt-15, sqrt-7) -- exactly the
# Q(sqrt3, sqrt5, sqrt7, sqrt11) the paper names, since sqrt-15 = sqrt-3.sqrt5.
#
#     COROLLARY. A 6-CHROMATIC UNIT-DISTANCE GRAPH MUST USE A ROTATION WHOSE
#     CHORD IS IRRATIONAL.
#
# That is the whole explanation of the barrier at five. Rational chords are
# what one reaches for -- they are the rotations that carry a lattice point to
# another at a rational distance -- and every one of them buys a single square
# root. No amount of ingenuity inside that habit can pass five, because the
# obstruction is arithmetic and is fixed the moment the rotations are chosen.

RATIONAL_CHORDS_CANNOT_REACH_SIX = {
    "lemma": "|1 - rho|^2 = 2 - (rho + rhobar), so a rational chord makes rho "
             "a root of X^2 - (2-c)X + 1 and [Q(rho):Q] <= 2",
    "consequence": "a construction from rotations with rational chords is "
                   "multiquadratic, hence has residue degree at most 2 at 5, "
                   "hence has a coset 5-colouring and chi <= 5",
    "de_grey_chords": {"hexagonal": "1", "moser": "1/3", "Sb": "1/4",
                       "Ya": "9/4", "Yb": "7/4"},
    "de_grey_field": "Q(sqrt-3, sqrt-11, sqrt-15, sqrt-7), which is the "
                     "Q(sqrt3, sqrt5, sqrt7, sqrt11) of the paper",
    "corollary": "a 6-chromatic unit-distance graph must use a rotation whose "
                 "chord is irrational",
    "the_chain_has_one": {
        "rotation": "a, with a + abar = r = (m^2-6m-3)/(m^2+3)",
        "chord": "2 - r = (919 + 222 m - 36 m^2)/397 over "
                 "T^3 - 9T^2 + 14T + 8",
        "degree_over_Q": 3,
        "note": "the first construction here meeting the condition the "
                "corollary demands",
    },
}


def rotation_field_degree(chord) -> dict:
    """Where a rotation of the given chord |1 - rho|^2 lives.

    Returns the degree of Q(rho) and, for a rational chord, the squarefree
    radicand of the quadratic field it generates. The point of the function is
    the degree: 2 for every rational chord, which is what caps a construction
    built from them at five colours.
    """
    q = Fraction(chord)
    # rho^2 - (2-q) rho + 1 = 0, discriminant (2-q)^2 - 4
    disc = (2 - q) ** 2 - 4
    num = disc.numerator * disc.denominator
    sign = -1 if num < 0 else 1
    num = abs(num)
    rad = 1
    d = 2
    while d * d <= num:
        e = 0
        while num % d == 0:
            num //= d
            e += 1
        if e % 2:
            rad *= d
        d += 1
    rad *= num
    return {"chord": q, "degree": 1 if disc == 0 else 2,
            "radicand": sign * rad,
            "note": "every rational chord gives degree at most 2"}


# -- the closed necklace, and why it is 4-critical --------------------------
#
# A chain of k rhombi glued tip to apex and closed by one edge is, as a graph,
# a cycle of k DIAMONDS -- each rhombus B_{j-1}, M_j, M'_j, B_j is K_4 minus
# the edge B_{j-1}B_j, five edges -- plus the closing edge B_k B_0. So it has
#
#     3k + 1 points and 5k + 1 edges, and nothing else, provided no two of
#     its points accidentally land at distance 1.
#
# That proviso is checkable by counting, and the 47-step chain meets it
# exactly: 142 points, 236 edges, and 5*47 + 1 = 236. Every rhombus edge is
# forced to be present by construction, so a total of 5k+1 leaves room for no
# others.
#
# Then 4-criticality is a proof, not a prediction -- which matters, because a
# prediction about a critical core has failed twice here.
#
#   chi >= 4: in each diamond, B_{j-1}, M_j, M'_j is a triangle and B_j is
#   adjacent to both middles, so c(B_j) = c(B_{j-1}). All tips share a colour,
#   and B_k is adjacent to B_0. Contradiction.
#
#   Remove a middle M_j: its diamond becomes the path B_{j-1} M'_j B_j and
#   stops forcing. Colour the tips before j with 0, those from j on with 1,
#   give M'_j the third colour, and each intact diamond's two middles the two
#   colours its tips do not use. B_k = 1 differs from B_0 = 0. Proper.
#
#   Remove a tip B_j: the two diamonds meeting there become triangles, the two
#   runs of tips colour independently, and the same assignment works. Removing
#   B_0 deletes the closing edge outright.
#
# So EVERY VERTEX IS CRITICAL. A closed rhombus necklace with no accidental
# adjacency is 4-critical, and its direction set is the union of the
# zeta_6-orbits of its steps together with the closing direction. Hence
#
#     A CLOSED RHOMBUS NECKLACE WHOSE STEP ORBITS BLOCK IS A 4-CRITICAL
#     BLOCKED UNIT-DISTANCE GRAPH.
#
# Which is what the growth was for. Over the degree-12 tower, with the
# premature-closing guard in place so no shorter necklace sits inside, the
# 47-step chain reaches 25 orbits and 150 directions, and those block.

CLOSED_NECKLACE_IS_CRITICAL = {
    "shape": "a cycle of k diamonds (K_4 minus an edge) glued tip to apex, "
             "plus one closing edge",
    "counts": "3k+1 points, 5k+1 edges, with no others when no two points "
              "accidentally meet at distance 1",
    "measured": {"k": 47, "points": 142, "edges": 236, "5k+1": 236},
    "chi_at_least_4": "each diamond forces its tip to its apex's colour, so "
                      "all tips agree, and the closing edge contradicts it",
    "criticality": "removing a middle turns its diamond into a path and stops "
                   "the forcing; removing a tip turns two diamonds into "
                   "triangles; either way the runs of tips colour "
                   "independently and three colours suffice",
    "consequence": "a closed rhombus necklace whose step orbits block is a "
                   "4-critical blocked unit-distance graph",
    "machine_confirmed": {
        "core": "142 points, 236 edges, 152 directions, rank 12, BLOCKED",
        "how": "greedy deletion over all 142 vertices could remove none of "
               "them: the 4-critical core is the whole graph",
        "note": "the proof above predicted this; unlike the two earlier "
                "predictions about critical cores, it was a proof",
    },
    "shorter_one": {"steps": 43, "orbits": 23, "directions": 138,
                    "blocks": True},
    "fails_the_stronger_gate": {
        5: "no homomorphism at all -- blocking",
        6: "60 phi tried, all needing more than 5",
        7: "no homomorphism at all -- blocking",
        8: "5-COLOURABLE: a homomorphism whose Cayley graph needs only 4",
    },
}


# -- the stronger gate bites, on my own object -----------------------------
#
# The necklace's directions block at 5 -- that is what makes it the first
# 4-critical blocked unit-distance graph -- and they survive n = 6 and n = 7.
# At n = 8 they do not: the seventh homomorphism tried has a Cayley graph of
# chromatic number FOUR, so
#
#     colour v by that colouring of phi(v - v0)
#
# is a proper 5-colouring of any graph over those directions. The necklace can
# never be the substrate of a 6-chromatic graph, however blocked and however
# critical it is.
#
# Which is the point of having built the stronger screen: blocking at 5 is
# necessary and NOT sufficient, and here is the first case where the
# difference is visible rather than theoretical. The denominator-29 directions
# survive every modulus from 5 to 20; the necklace's do not survive 8.
#
# It also turns into a design rule. Growing a necklace to block is not enough;
# it has to be grown so that no modulus admits a periodic 5-colouring, which
# is a stronger and equally checkable target.

NECKLACE_FAILS_THE_STRONGER_GATE = {
    "blocked_at": [5, 7],
    "survived": [6],
    "failed_at": 8,
    "how": "the seventh homomorphism tried has Cayley chromatic number 4",
    "consequence": "any graph over the necklace's directions is 5-colourable, "
                   "so it cannot be a substrate for a 6-chromatic graph",
    "contrast": "the denominator-29 directions survive every modulus 5 to 20",
    "design_rule": "grow for the stronger gate, not merely for blocking",
}


# -- what the n = 8 failure actually was -----------------------------------
#
# Diagnosed rather than left as a curiosity. The failing homomorphism sends
# the directions onto S = {1,2,3,5,6,7} -- everything but 4 -- and
# Cay(Z/8, S) has chromatic number 4, because {0,4},{1,5},{2,6},{3,7} are
# independent pairs. Missing any element other than 4 leaves chi = 8.
#
# And {0, 4} is a SUBGROUP of Z/8. Avoiding it is the same as a homomorphism
# to Z/8 / {0,4} = Z/4 that is nonzero on every direction -- a coset colouring
# with FOUR colours. So the n = 8 result was not a subtlety at all: it said
# the necklace is 4-colourable, which it is.
#
# That sharpens the screen and makes it cheaper at the same time. A coset
# colouring mod n gives chi <= n, so
#
#     A 6-CHROMATIC UNIT-DISTANCE GRAPH MUST BLOCK AT n = 2, 3, 4 AND 5.
#
# Four SAT calls, no Cayley chromatic numbers. Measured:
#
#     necklace, 138 directions       blocks at 2, 3, 5; NOT at 4
#     denominator-29, 300 directions blocks at 2, 3, 4 and 5
#     the field's 450 directions     blocks at 2, 3, 4 and 5
#
# So the necklace's gap is not forced -- the field has the material, and a
# longer one can reach it. That is what the growth now targets.

BLOCK_AT_EVERY_MODULUS_TO_FIVE = {
    "n8_was": "S = {1,2,3,5,6,7}, missing only 4; {0,4} is a subgroup of Z/8, "
              "so avoiding it is a coset colouring with four colours",
    "sharpened": "a 6-chromatic unit-distance graph must block at n = 2, 3, 4 "
                 "and 5, since a coset colouring mod n gives chi <= n",
    "measured": {"necklace": "blocks at 2, 3, 5 but not 4",
                 "denominator_29": "blocks at 2, 3, 4, 5",
                 "field_orbits": "blocks at 2, 3, 4, 5"},
    "reading": "the necklace's gap is not forced; the field has the material",
}


# -- a field with de Grey's spindle AND the residue degree that blocks ------
#
# A distance d spindles iff K holds a rotation with |1 - rho|^2 = 1/d^2. With
# t = rho + rhobar = 2 - 1/d^2 one gets 4 - t^2 = (4d^2 - 1)/d^4, so since
# K = F(sqrt-3) the condition is
#
#     3(4d^2 - 1) is a square in F.
#
# At d^2 = 3 -- de Grey's distance, the rhombus tip -- that is 33. And
# F = Q(m)(sqrt V) contains Q(sqrt33) exactly when V = 33 times a square in
# Q(m): if sqrt V lay in Q(m, sqrt D) then V = a^2 + b^2 D + 2ab sqrt D forces
# ab = 0, and b = 0 would make V a square outright.
#
# 33 is POSITIVE, so V = 33 s^2 is compatible with V totally positive, which
# the chain needs. Searching the totally real cubics with V totally positive
# and filtering by the necessary condition that N(V)/33^3 be a rational
# square turns up two, and one of them is the object:
#
#     x^3 - 10x^2 + 26x - 11,   totally real, irreducible, 5 INERT
#     V(m) = 1947 - 4653 m + 1848 m^2,  totally positive
#     V = 33 s^2  with  s = 13 - 26 m + 5 m^2   -- checked exactly
#
# So F = Q(m, sqrt33) and K = F(sqrt-3) = Q(m, sqrt-3, sqrt-11), degree 12,
# which holds the Moser rotation (5 + sqrt-11)/6. And 5 is inert in Q(m),
# where the cubic has no root mod 5, and inert in Q(sqrt33), since 33 = 3 mod
# 5 is a non-residue; so its residue degree in F is lcm(3,2) = 6, and K/F is
# unramified there because -3 is a unit at 5. Both conditions of the
# residue-degree theorem hold.
#
#     THE FIRST FIELD CARRYING BOTH THE ROTATION THAT TAKES FOUR COLOURS TO
#     FIVE AND THE ARITHMETIC THAT A SIXTH REQUIRES.
#
# STATED FOR WHAT IT IS. This is where a 6-chromatic graph could live, not one
# that does. And de Grey's OTHER rotations are not available here: chord 1/4
# needs sqrt-15, hence sqrt5, and F = Q(m).Q(sqrt33) has Q(sqrt33) as its only
# quadratic subfield because Q(m) is cubic. So his construction cannot be
# transplanted whole -- only the final spindling step is available, and the
# 4-chromatic forcing structure beneath it would have to be rebuilt from the
# rotations this field does have: those with 3(4d^2 - 1) in (Q*)^2 or in
# 33(Q*)^2.

FIELD_WITH_SPINDLE_AND_BLOCKING = {
    "cubic": "x^3 - 10x^2 + 26x - 11",
    "V": "1947 - 4653 m + 1848 m^2, totally positive",
    "V_is_33_times_a_square": "s = 13 - 26 m + 5 m^2, checked exactly",
    "F": "Q(m, sqrt33), degree 6, 5 inert with residue degree 6",
    "K": "Q(m, sqrt-3, sqrt-11), degree 12",
    "spindle_available": "the Moser rotation (5 + sqrt-11)/6, so d^2 = 3 "
                         "spindles -- de Grey's step from four colours to five",
    "blocks": "residue degree 6 >= 3 and K/F unramified above 5",
    "spindleable_distances": "those with 3(4d^2 - 1) in (Q*)^2 or 33(Q*)^2",
    "honest": "where a 6-chromatic graph could live, not one that does; de "
              "Grey's other rotations need sqrt5, which this F does not have",
}


# -- why four-colour forcing needs distance, not a gadget -------------------
#
# The rhombus forces at three colours because the triangle B, M, M' uses all
# three, so B' -- adjacent to M and M' -- has only B's colour left. The
# analogue at four would need a vertex whose neighbourhood uses three colours
# in every 4-colouring. It does not exist locally, and the reason is short.
#
# A triangle inside N(v) would make {v} u T a K_4, which no unit-distance
# graph in the plane contains. So N(v) is triangle-free. More: N(v) lies on
# the unit circle about v, where two points are adjacent exactly when they are
# 60 degrees apart, so each point has at most two neighbours there and every
# cycle is a full hexagon -- of even length. Hence
#
#     THE NEIGHBOURHOOD OF ANY VERTEX OF A UNIT-DISTANCE GRAPH IS BIPARTITE,
#
# so it is 2-colourable and at four colours v always keeps at least two
# choices. No vertex's colour is ever forced by its neighbourhood alone.
#
# Measured on the necklace, which makes the point concretely: 0 of its 8385
# non-adjacent pairs are monochromatic in every 4-colouring. Each diamond
# gives its tip two choices at four colours, and nothing downstream closes
# them. The necklace cannot be spindled to five.
#
# This is why de Grey's graph is 1581 vertices and not 10: four-colour forcing
# has to be assembled out of long-range structure, and cannot be bought with a
# local gadget the way the rhombus buys it at three.

FOUR_COLOUR_FORCING_IS_NOT_LOCAL = {
    "three_colours": "the rhombus: a triangle uses all three, so the tip has "
                     "only the apex's colour left",
    "why_not_four": "a triangle in N(v) would make a K_4, which the plane "
                    "forbids; and N(v) lies on a circle where adjacency is "
                    "60 degrees apart, so every cycle is a hexagon",
    "theorem": "the neighbourhood of any vertex of a unit-distance graph is "
               "bipartite, hence 2-colourable, so at four colours v always "
               "keeps two choices",
    "measured": "0 pairs of the necklace are monochromatic in every "
                "4-colouring, over all 8385 non-adjacent pairs",
    "consequence": "the necklace cannot be spindled to five; four-colour "
                   "forcing must be assembled from long-range structure, "
                   "which is why de Grey's graph has 1581 vertices",
}
