import TheoremWplus
import Mathlib.Topology.Instances.AddCircle.Defs
import Mathlib.Data.ZMod.Basic
import Mathlib.Basic.Real.Basic
import Mathlib.Algebra.Order.Archimedean.Real.Basic
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Positivity
import Mathlib.Analysis.Normed.Group.AddCircle
import Mathlib.Algebra.Category.Grp.Injective
import Mathlib.Data.Fintype.Pigeonhole

/-!
# Theorem W⁺ for distance graphs `G(ℤ, D)`, and Problem 3 of Liu's survey

For a finite set `D` of positive integers, the *distance graph* `G(ℤ, D)` has vertex set `ℤ`
and an edge between `x` and `x + d` for every `x ∈ ℤ` and `d ∈ D`. A `(p, q)`-colouring of
`G(ℤ, D)` (a homomorphism to the circular clique `K_{p/q}`) is a map `c : ℤ → ZMod p` such that
along every edge the colour difference `c (x + d) - c x`, read in `{0, …, p - 1}` (`ZMod.val`),
lies in `[q, p - q]`. The circular chromatic number is `χ_c(G) = inf {p / q : G has a
(p, q)-colouring}`. Write `‖t‖ = |t - round t|` for the distance from `t ∈ ℝ` to the nearest
integer, and `κ(D) = max_α min_{d ∈ D} ‖d α‖`.

## Main results (namespace `DistLiu`)

* `wplus_distance` (Theorem W⁺ for `G(ℤ, D)`): if `0 < q`, `2q ≤ p < 4q` and `c` is a
  `(p, q)`-colouring of `G(ℤ, D)`, then there is `α : ℝ` with `‖d α‖ ≥ q / p` for all `d ∈ D`.
* `wplus_distance_converse`: if `0 < q`, `2q ≤ p` and some `α` has `‖d α‖ ≥ q / p` for all
  `d ∈ D`, then `G(ℤ, D)` has a `(p, q)`-colouring, namely `c x = ⌊p · frac(x α)⌋ mod p`
  (`colourOf`, `colourOf_isColouring`; here `D` may be any finite set of integers).
* `liu_problem3`: if `|D| = 3` and the lonely runner theorem holds for the three speeds of `D`
  (hypothesis `hLR`: some `α` has `‖d α‖ ≥ 1/4` for all `d ∈ D`; Betke–Wills 1972,
  Cusick 1973), then every `(p, q)`-colouring of `G(ℤ, D)` with `0 < q ≤ p` gives an `α` with
  `‖d α‖ ≥ q / p` for all `d ∈ D`. With the converse (`liu_problem3_iff`): `G(ℤ, D)` has a
  `(p, q)`-colouring iff `q / p ≤ κ(D)`, i.e. `χ_c(G(ℤ, D)) = 1 / κ(D)` for every `D` with
  `|D| = 3`. This answers "no" to Problem 3 of D. D.-F. Liu, "From rainbow to the lonely runner:
  a survey on coloring parameters of distance graphs", Taiwanese J. Math. 12 (2008): "Does there
  exist a 3-element set `D` with `χ_c(ℤ, D) < 1/κ(D)`?"
* `lonely_runner_three`: the hypothesis `hLR` holds for every set of three positive integers
  (the lonely runner theorem for three speeds, with a short self-contained proof; more generally
  `lonely_runner_real` for three positive real speeds). Hence `liu_problem3_unconditional` and
  `liu_problem3_iff_unconditional`: `χ_c(G(ℤ, D)) = 1 / κ(D)` whenever `|D| = 3`, with no
  hypothesis.

## Proof of `wplus_distance`

It is the passage from finite groups to `ℤ` of `Recurrence.lean` (namespace `GKR`), with Theorem W⁺ for finite abelian
groups (`TheoremWplus.theoremWplus_general`) in place of Theorem W; since `D` is finite, one period
suffices and no compactness argument is needed.
1. Let `N = max D`. By pigeonhole two windows `[i, i + N)` and `[i + P, i + P + N)` (`P > 0`)
   carry the same colours (`exists_window`), so `c` is `P`-periodic on `[i, i + P + N)`
   (`periodic_of_window`).
2. Hence `col x = c (i + x.val)` is a homomorphism `Cay(ZMod P, ±D) → K_{p/q}`: for the step
   `+d` this is the hypothesis on `c` at `i + x.val`, and for the step `-d` the difference is
   negated, which maps `[q, p - q]` to itself. Theorem W⁺ gives a character `ξ` of the subgroup
   of `ZMod P` generated by `±D` with `ξ d ∈ [q/p, 1 - q/p] (mod 1)` for `d ∈ D`.
3. `ℝ/ℤ` is divisible, hence an injective `ℤ`-module, so `ξ` extends to `F : ZMod P →+ ℝ/ℤ`.
   A real lift `α` of `F 1` (necessarily `α ≡ j / P (mod 1)` for some integer `j`) satisfies
   `d α ≡ F d = ξ d (mod 1)`, hence `‖d α‖ = ‖ξ d‖ ≥ q / p` for `d ∈ D` (`le_abs_sub_round`).

## Proof of `wplus_distance_converse`

For `d ∈ D` let `f = frac(d α)`; `‖d α‖ ≥ q / p` means `f ∈ [q/p, 1 - q/p]`
(`fract_mem_of_le_abs_sub_round`). With `u = frac(x α)` we have
`frac((x + d) α) = u + f + m` for an integer `m`, so
`c (x + d) - c x ≡ ⌊p u + p f⌋ - ⌊p u⌋ (mod p)`, and `q ≤ p f ≤ p - q` gives
`q ≤ ⌊p u + p f⌋ - ⌊p u⌋ ≤ p - q`; this integer lies in `[0, p)`, so it is the value read
in `{0, …, p - 1}`.

## Proof of `lonely_runner_three`

Let `0 < a ≤ b ≤ c` and `P = c / a ≥ Q = c / b ≥ 1`. Take `t = x / (4c)` with `x` odd, so that
`‖c t‖ = ‖x / 4‖ = 1/4`. It suffices that `x ∈ [P, 3P]` (then `a t ∈ [1/4, 3/4]`) and
`x ∈ [(4m + 1) Q, (4m + 3) Q]` for some `m ∈ ℕ` (then `b t ∈ [m + 1/4, m + 3/4]`). Such `x` and
`m` exist (`exists_odd_window`); with `ρ = P / Q = b / a`:
* if `ρ ≥ 3`, the window for `m = ⌈(ρ - 1)/4⌉` lies inside `[P, 3P]` and has length `2Q ≥ 2`,
  so it contains an odd integer (`exists_odd_mem`); if `7/3 ≤ ρ < 3`, the same holds for `m = 1`;
* if `ρ < 7/3`, the intervals `[P, 3Q]` (`m = 0`) and `[5Q, 3P]` (`m = 1`) work as soon as one of
  them has length `≥ 2`; otherwise `Q < 2`, and `x = 3` (if `P ≤ 3`), `x = 5` (if `P > 3`,
  `3Q ≥ 5`) or `x = 9` (if `P > 3`, `3Q < 5`) works.
-/

set_option autoImplicit false


/-! ## Distance graphs -/

namespace DistLiu

/-! ### Distance to the nearest integer -/

/-- On `[a, 1 - a]` (with `a ≥ 0`) the distance to the nearest integer is at least `a`. -/
lemma le_abs_sub_round {a x : ℝ} (ha : 0 ≤ a) (h1 : a ≤ x) (h2 : x ≤ 1 - a) :
    a ≤ |x - round x| := by
  rcases le_or_gt (round x) 0 with h | h
  · have h' : (round x : ℝ) ≤ 0 := by exact_mod_cast h
    rw [abs_of_nonneg (by linarith)]
    linarith
  · have h'' : (1 : ℤ) ≤ round x := by omega
    have h' : (1 : ℝ) ≤ round x := by exact_mod_cast h''
    rw [abs_of_nonpos (by linarith)]
    linarith

/-- On `[k + a, k + 1 - a]` (`k ∈ ℤ`, `a ≥ 0`) the distance to the nearest integer is at
least `a`. -/
lemma le_abs_sub_round_of_mem {a y : ℝ} (k : ℤ) (ha : 0 ≤ a) (h1 : (k : ℝ) + a ≤ y)
    (h2 : y ≤ k + (1 - a)) : a ≤ |y - round y| := by
  have h := le_abs_sub_round ha (x := y - k) (by linarith) (by linarith)
  rwa [round_sub_intCast, Int.cast_sub, sub_sub_sub_cancel_right] at h

/-- Conversely, `‖t‖ ≥ a` forces `frac t ∈ [a, 1 - a]` (as `‖t‖ = min (frac t) (1 - frac t)`). -/
lemma fract_mem_of_le_abs_sub_round {a t : ℝ} (h : a ≤ |t - round t|) :
    a ≤ Int.fract t ∧ Int.fract t ≤ 1 - a := by
  rw [abs_sub_round_eq_min, le_min_iff] at h
  exact ⟨h.1, by linarith [h.2]⟩

/-! ### Periodicity on a long window (adapted from `Recurrence.lean`) -/

/-- Pigeonhole: some two windows of length `N` of a colouring of `ℤ` with finitely many colours
carry the same colours. -/
lemma exists_window {β : Type*} [Finite β] (c : ℤ → β) (N : ℕ) :
    ∃ (i : ℤ) (P : ℕ), 0 < P ∧ ∀ k : ℕ, k < N → c (i + k) = c (i + P + k) := by
  obtain ⟨a, b, hab, he⟩ :=
    Finite.exists_ne_map_eq_of_infinite (fun i : ℕ => fun k : Fin N => c ((i : ℤ) + (k : ℕ)))
  rcases Nat.lt_or_gt_of_ne hab with h | h
  · refine ⟨a, b - a, by omega, fun k hk => ?_⟩
    have := congr_fun he ⟨k, hk⟩
    simp only at this
    rw [this, show (a : ℤ) + ((b - a : ℕ) : ℤ) = b by rw [Nat.cast_sub h.le]; ring]
  · refine ⟨b, a - b, by omega, fun k hk => ?_⟩
    have := congr_fun he ⟨k, hk⟩
    simp only at this
    rw [← this, show (b : ℤ) + ((a - b : ℕ) : ℤ) = a by rw [Nat.cast_sub h.le]; ring]

/-- A colouring of `ℤ` that agrees on the windows `[i, i + N)` and `[i + P, i + P + N)` is
`P`-periodic on `[i, i + P + N)`. -/
lemma periodic_of_window {β : Type*} (c : ℤ → β) {i : ℤ} {P N : ℕ} (hP : 0 < P)
    (hw : ∀ k : ℕ, k < N → c (i + k) = c (i + P + k)) :
    ∀ m : ℕ, m < P + N → c (i + m) = c (i + (m % P : ℕ)) := by
  intro m
  induction m using Nat.strong_induction_on with
  | _ m ih =>
    intro hm
    rcases Nat.lt_or_ge m P with h | h
    · rw [Nat.mod_eq_of_lt h]
    · have h1 := hw (m - P) (by omega)
      rw [show i + (P : ℤ) + ((m - P : ℕ) : ℤ) = i + (m : ℤ) by rw [Nat.cast_sub h]; ring] at h1
      rw [← h1, ih (m - P) (by omega) (by omega), ← Nat.mod_eq_sub_mod h]

/-! ### Theorem W⁺ for `G(ℤ, D)` -/

/-- **Theorem W⁺ for distance graphs.** Let `D` be a finite set of positive integers, `0 < q`,
`2q ≤ p < 4q`, and `c : ℤ → ZMod p` a `(p, q)`-colouring of the distance graph `G(ℤ, D)`: along
every edge `x — x + d` (`d ∈ D`) the colour difference, read in `{0, …, p - 1}`, lies in
`[q, p - q]`. Then some `α : ℝ` satisfies `‖d α‖ ≥ q / p` for every `d ∈ D`, where
`‖t‖ = |t - round t|` is the distance to the nearest integer. -/
theorem wplus_distance (D : Finset ℤ) (hD : ∀ d ∈ D, 0 < d) (p q : ℕ) (hq : 0 < q)
    (h2 : 2 * q ≤ p) (h4 : p < 4 * q) (c : ℤ → ZMod p)
    (hc : ∀ x : ℤ, ∀ d ∈ D, q ≤ (c (x + d) - c x).val ∧ (c (x + d) - c x).val ≤ p - q) :
    ∃ α : ℝ, ∀ d ∈ D, (q : ℝ) / p ≤ |(d : ℝ) * α - round ((d : ℝ) * α)| := by
  classical
  have : Fact ((0 : ℝ) < 1) := ⟨one_pos⟩
  have hp0 : 0 < p := by omega
  have : NeZero p := ⟨hp0.ne'⟩
  -- the distances, as natural numbers, are at most `N = max D`
  have hDN : ∀ n : ℕ, (n : ℤ) ∈ D → n ≤ D.sup Int.toNat := by
    intro n hn
    simpa using Finset.le_sup (f := Int.toNat) hn
  -- step 1: `c` is `P`-periodic on a window `[i, i + P + N)`
  obtain ⟨i, P, hP, hw⟩ := exists_window c (D.sup Int.toNat)
  have hper := periodic_of_window c hP hw
  have : NeZero P := ⟨hP.ne'⟩
  -- step 2: the induced colouring of `ZMod P` and the symmetric set of steps `±D`
  let S : Set (ZMod P) := {x | ∃ n : ℕ, (n : ℤ) ∈ D ∧ (x = n ∨ x = -n)}
  have hS : ∀ s ∈ S, -s ∈ S := by
    rintro s ⟨n, hn, rfl | rfl⟩
    · exact ⟨n, hn, Or.inr rfl⟩
    · exact ⟨n, hn, Or.inl (neg_neg _)⟩
  let col : ZMod P → ZMod p := fun x => c (i + (x.val : ℤ))
  have hcol1 : ∀ g : ZMod P, ∀ n : ℕ, (n : ℤ) ∈ D →
      col (g + n) - col g = c (i + g.val + n) - c (i + g.val) := by
    intro g n hn
    have hv : (g + (n : ZMod P)).val = (g.val + n) % P := by
      rw [ZMod.val_add, ZMod.val_natCast, Nat.add_mod_mod]
    have hlt : g.val + n < P + D.sup Int.toNat := by
      have := ZMod.val_lt g
      have := hDN n hn
      omega
    show c (i + ((g + (n : ZMod P)).val : ℤ)) - c (i + (g.val : ℤ)) = _
    rw [hv, ← hper _ hlt, Nat.cast_add, ← add_assoc]
  have hcol : ∀ g, ∀ s ∈ S,
      q ≤ (col (g + s) - col g).val ∧ (col (g + s) - col g).val ≤ p - q := by
    rintro g s ⟨n, hn, rfl | rfl⟩
    · rw [hcol1 g n hn]
      exact hc (i + g.val) n hn
    · -- the step `-n` from `g` is the step `n` from `g - n`, reversed
      have h := hcol1 (g + -(n : ZMod P)) n hn
      rw [neg_add_cancel_right] at h
      have hb := hc (i + (g + -(n : ZMod P)).val) n hn
      rw [← h] at hb
      have hne : col g - col (g + -(n : ZMod P)) ≠ 0 := by
        intro h0
        rw [h0, ZMod.val_zero] at hb
        omega
      have hlt := ZMod.val_lt (col g - col (g + -(n : ZMod P)))
      rw [← neg_sub (col g) (col (g + -(n : ZMod P))), ZMod.neg_val, ite_eq_right hne]
      constructor <;> omega
  obtain ⟨ξ, hξ⟩ := TheoremWplus.theoremWplus_general S hS p q hp0 h4 col hcol
  -- step 3: extend `ξ` to `ZMod P` (`ℝ/ℤ` is divisible, hence injective) and lift `F 1` to `ℝ`
  obtain ⟨F, hF⟩ := (Module.Baer.of_divisible (AddCircle (1 : ℝ))).extension_property_addMonoidHom
    (AddSubgroup.closure S).subtype (AddSubgroup.subtype_injective _) ξ
  obtain ⟨α, hα⟩ := QuotientAddGroup.mk_surjective (F 1)
  refine ⟨α, fun d hd => ?_⟩
  obtain ⟨n, rfl⟩ : ∃ n : ℕ, d = n := ⟨d.toNat, (Int.toNat_of_nonneg (hD d hd).le).symm⟩
  obtain ⟨x, hx1, hx2, hx⟩ := hξ _ (⟨n, hd, Or.inl rfl⟩ : (n : ZMod P) ∈ S)
  have key : n • F 1 = (x : AddCircle (1 : ℝ)) := by
    rw [hx, ← hF, ← map_nsmul, nsmul_eq_mul, mul_one]
    rfl
  have h1 : |((n : ℤ) : ℝ) * α - round (((n : ℤ) : ℝ) * α)| = |x - round x| := by
    rw [← UnitAddCircle.norm_eq, ← UnitAddCircle.norm_eq, Int.cast_natCast, ← nsmul_eq_mul,
      AddCircle.coe_nsmul]
    congr 1
    rw [← key, ← hα]
  rw [h1]
  exact le_abs_sub_round (by positivity) hx1 hx2

/-! ### The converse -/

/-- The colouring `c_α(x) = ⌊p · frac(x α)⌋ mod p` of `ℤ`. -/
noncomputable def colourOf (p : ℕ) (α : ℝ) (x : ℤ) : ZMod p :=
  ((⌊(p : ℝ) * Int.fract ((x : ℝ) * α)⌋ : ℤ) : ZMod p)

/-- If `‖d α‖ ≥ q / p` for every `d ∈ D` (any finite set of integers), then `colourOf p α` is a
`(p, q)`-colouring of `G(ℤ, D)`: both bounds `q ≤ c (x + d) - c x ≤ p - q` hold. -/
theorem colourOf_isColouring (D : Finset ℤ) (p q : ℕ) (hp0 : 0 < p) (α : ℝ)
    (hα : ∀ d ∈ D, (q : ℝ) / p ≤ |(d : ℝ) * α - round ((d : ℝ) * α)|) :
    ∀ x : ℤ, ∀ d ∈ D, q ≤ (colourOf p α (x + d) - colourOf p α x).val ∧
      (colourOf p α (x + d) - colourOf p α x).val ≤ p - q := by
  intro x d hd
  have : NeZero p := ⟨hp0.ne'⟩
  have hp : (0 : ℝ) < p := by exact_mod_cast hp0
  -- `f = frac (d α) ∈ [q/p, 1 - q/p]`, so `p f ∈ [q, p - q]`
  obtain ⟨hf1, hf2⟩ := fract_mem_of_le_abs_sub_round (hα d hd)
  have hqp : (p : ℝ) * ((q : ℝ) / p) = q := by field_simp
  have hb1 : (q : ℝ) ≤ p * Int.fract ((d : ℝ) * α) := by nlinarith
  have hb2 : (p : ℝ) * Int.fract ((d : ℝ) * α) ≤ p - q := by nlinarith
  -- `frac ((x + d) α) = u + f + m` with `u = frac (x α)` and an integer `m`
  obtain ⟨m, hm⟩ : ∃ m : ℤ, Int.fract (((x + d : ℤ) : ℝ) * α) =
      Int.fract ((x : ℝ) * α) + Int.fract ((d : ℝ) * α) + m :=
    ⟨⌊(x : ℝ) * α⌋ + ⌊(d : ℝ) * α⌋ - ⌊((x + d : ℤ) : ℝ) * α⌋, by
      unfold Int.fract
      push_cast
      ring⟩
  set u := Int.fract ((x : ℝ) * α) with hu
  set f := Int.fract ((d : ℝ) * α) with hf
  -- so the colour difference is `Δ = ⌊p u + p f⌋ - ⌊p u⌋ (mod p)`
  have hdiff : colourOf p α (x + d) - colourOf p α x
      = ((⌊(p : ℝ) * u + p * f⌋ - ⌊(p : ℝ) * u⌋ : ℤ) : ZMod p) := by
    simp only [colourOf]
    rw [hm, ← hu, show (p : ℝ) * (u + f + m) = p * u + p * f + ((p * m : ℤ) : ℝ) by
      push_cast; ring, Int.floor_add_intCast]
    push_cast
    rw [ZMod.natCast_self]
    ring
  -- and `q ≤ Δ ≤ p - q`
  have hD1 : ⌊(p : ℝ) * u⌋ + (q : ℤ) ≤ ⌊(p : ℝ) * u + p * f⌋ := by
    rw [Int.le_floor]
    push_cast
    have := Int.floor_le ((p : ℝ) * u)
    linarith
  have hD2 : ⌊(p : ℝ) * u + p * f⌋ < ⌊(p : ℝ) * u⌋ + ((p : ℤ) - q) + 1 := by
    rw [Int.floor_lt]
    push_cast
    have := Int.lt_floor_add_one ((p : ℝ) * u)
    linarith
  rw [hdiff]
  have hv : (((⌊(p : ℝ) * u + p * f⌋ - ⌊(p : ℝ) * u⌋ : ℤ) : ZMod p).val : ℤ)
      = (⌊(p : ℝ) * u + p * f⌋ - ⌊(p : ℝ) * u⌋) % p := ZMod.val_intCast _
  have hlt := ZMod.val_lt (((⌊(p : ℝ) * u + p * f⌋ - ⌊(p : ℝ) * u⌋ : ℤ) : ZMod p))
  rcases Nat.eq_zero_or_pos q with hq | hq
  · subst hq
    constructor <;> omega
  · rw [Int.emod_eq_of_lt (by omega) (by omega)] at hv
    constructor <;> omega

/-- **Converse of Theorem W⁺ for distance graphs.** If `0 < q`, `2q ≤ p` and some `α : ℝ`
satisfies `‖d α‖ ≥ q / p` for every `d ∈ D`, then `G(ℤ, D)` has a `(p, q)`-colouring
(`colourOf p α`, i.e. `c x = ⌊p · frac(x α)⌋ mod p`, see `colourOf_isColouring`). -/
theorem wplus_distance_converse (D : Finset ℤ) (p q : ℕ) (hq : 0 < q) (h2 : 2 * q ≤ p)
    (hα : ∃ α : ℝ, ∀ d ∈ D, (q : ℝ) / p ≤ |(d : ℝ) * α - round ((d : ℝ) * α)|) :
    ∃ c : ℤ → ZMod p, ∀ x : ℤ, ∀ d ∈ D,
      q ≤ (c (x + d) - c x).val ∧ (c (x + d) - c x).val ≤ p - q := by
  obtain ⟨α, hα⟩ := hα
  exact ⟨colourOf p α, colourOf_isColouring D p q (by omega) α hα⟩

/-! ### Three distances: Problem 3 of Liu's survey -/

/-- **Problem 3 of D. D.-F. Liu's survey** ("From rainbow to the lonely runner: a survey on
coloring parameters of distance graphs", Taiwanese J. Math. 12 (2008)), answered "no".

Let `D` be a set of three positive integers and assume the lonely runner theorem for the three
speeds of `D` (hypothesis `hLR`: some `α` has `‖d α‖ ≥ 1/4` for all `d ∈ D`; Betke–Wills 1972,
Cusick 1973; it is proved below as `lonely_runner_three`, see `liu_problem3_unconditional`).
Then every `(p, q)`-colouring `c` of the distance graph `G(ℤ, D)` with `0 < q ≤ p` yields an
`α : ℝ` with `‖d α‖ ≥ q / p` for every `d ∈ D` (`‖t‖ = |t - round t|`).

Proof: a colouring forces `2q ≤ p`. If `p < 4q` this is Theorem W⁺ (`wplus_distance`); if
`p ≥ 4q` then `q / p ≤ 1/4` and `hLR` gives `α`.

Together with the converse `wplus_distance_converse` (see `liu_problem3_iff`) this says that
`G(ℤ, D)` has a `(p, q)`-colouring if and only if `q / p ≤ κ(D)`, where
`κ(D) = max_α min_{d ∈ D} ‖d α‖`; in other words `χ_c(G(ℤ, D)) = 1 / κ(D)` for every `D` with
`|D| = 3`, which is the answer "no" to Problem 3: "Does there exist a 3-element set `D` with
`χ_c(ℤ, D) < 1/κ(D)`?" -/
theorem liu_problem3 (D : Finset ℤ) (hD3 : D.card = 3) (hD : ∀ d ∈ D, 0 < d)
    (hLR : ∃ α : ℝ, ∀ d ∈ D, (1 : ℝ) / 4 ≤ |(d : ℝ) * α - round ((d : ℝ) * α)|)
    (p q : ℕ) (hq : 0 < q) (hqp : q ≤ p) (c : ℤ → ZMod p)
    (hc : ∀ x : ℤ, ∀ d ∈ D, q ≤ (c (x + d) - c x).val ∧ (c (x + d) - c x).val ≤ p - q) :
    ∃ α : ℝ, ∀ d ∈ D, (q : ℝ) / p ≤ |(d : ℝ) * α - round ((d : ℝ) * α)| := by
  -- a colouring forces `2q ≤ p`
  obtain ⟨d₀, hd₀⟩ : D.Nonempty := Finset.card_pos.1 (by omega)
  have h2 : 2 * q ≤ p := by
    have := hc 0 d₀ hd₀
    omega
  rcases lt_or_ge p (4 * q) with h4 | h4
  · exact wplus_distance D hD p q hq h2 h4 c hc
  · obtain ⟨α, hα⟩ := hLR
    refine ⟨α, fun d hd => le_trans ?_ (hα d hd)⟩
    have hp : (0 : ℝ) < p := by exact_mod_cast (show 0 < p by omega)
    have h4' : (4 : ℝ) * q ≤ p := by exact_mod_cast h4
    rw [div_le_div_iff₀ hp (by norm_num)]
    linarith

/-- **`χ_c(G(ℤ, D)) = 1 / κ(D)` for `|D| = 3`** (assuming the lonely runner theorem `hLR` for the
three speeds of `D`): for `0 < q ≤ p`, the distance graph `G(ℤ, D)` has a `(p, q)`-colouring if
and only if some `α : ℝ` has `‖d α‖ ≥ q / p` for every `d ∈ D`. -/
theorem liu_problem3_iff (D : Finset ℤ) (hD3 : D.card = 3) (hD : ∀ d ∈ D, 0 < d)
    (hLR : ∃ α : ℝ, ∀ d ∈ D, (1 : ℝ) / 4 ≤ |(d : ℝ) * α - round ((d : ℝ) * α)|)
    (p q : ℕ) (hq : 0 < q) (hqp : q ≤ p) :
    (∃ c : ℤ → ZMod p, ∀ x : ℤ, ∀ d ∈ D,
        q ≤ (c (x + d) - c x).val ∧ (c (x + d) - c x).val ≤ p - q) ↔
      ∃ α : ℝ, ∀ d ∈ D, (q : ℝ) / p ≤ |(d : ℝ) * α - round ((d : ℝ) * α)| := by
  constructor
  · rintro ⟨c, hc⟩
    exact liu_problem3 D hD3 hD hLR p q hq hqp c hc
  · rintro ⟨α, hα⟩
    -- `q / p ≤ ‖d α‖ ≤ 1/2` forces `2q ≤ p`
    obtain ⟨d₀, hd₀⟩ : D.Nonempty := Finset.card_pos.1 (by omega)
    have hp : (0 : ℝ) < p := by exact_mod_cast (show 0 < p by omega)
    have h2 : 2 * q ≤ p := by
      have h := (hα d₀ hd₀).trans (abs_sub_round _)
      rw [div_le_div_iff₀ hp (by norm_num)] at h
      exact_mod_cast (by linarith : (2 * q : ℝ) ≤ p)
    exact wplus_distance_converse D p q hq h2 ⟨α, hα⟩

/-! ### The lonely runner theorem for three speeds -/

/-- A closed interval of length at least `2` contains an odd integer. -/
lemma exists_odd_mem {y z : ℝ} (h : y + 2 ≤ z) : ∃ x : ℤ, Odd x ∧ y ≤ x ∧ (x : ℝ) ≤ z := by
  refine ⟨2 * ⌈(y - 1) / 2⌉ + 1, ⟨⌈(y - 1) / 2⌉, rfl⟩, ?_, ?_⟩
  · have := Int.le_ceil ((y - 1) / 2)
    push_cast
    linarith
  · have := Int.ceil_lt_add_one ((y - 1) / 2)
    push_cast
    linarith

/-- The combinatorial core: for reals `1 ≤ Q ≤ P` there are an odd integer `x` and `m : ℕ`
with `x ∈ [P, 3P]` and `x ∈ [(4m + 1) Q, (4m + 3) Q]`. -/
lemma exists_odd_window {P Q : ℝ} (hQ : 1 ≤ Q) (hQP : Q ≤ P) :
    ∃ x : ℤ, ∃ m : ℕ, Odd x ∧ P ≤ x ∧ (x : ℝ) ≤ 3 * P ∧
      (4 * (m : ℝ) + 1) * Q ≤ x ∧ (x : ℝ) ≤ (4 * (m : ℝ) + 3) * Q := by
  rcases le_or_gt (7 * Q) (3 * P) with h7 | h7
  · rcases lt_or_ge P (3 * Q) with h3 | h3
    · -- `7/3 ≤ P/Q < 3`: the window `[5Q, 7Q]` (`m = 1`) lies in `[P, 3P]`
      obtain ⟨x, hx, h1, h2⟩ := exists_odd_mem (show 5 * Q + 2 ≤ 7 * Q by linarith)
      exact ⟨x, 1, hx, by linarith, by linarith, by push_cast; linarith, by push_cast; linarith⟩
    · -- `P/Q ≥ 3`: the window with `m = ⌈(P/Q - 1)/4⌉` lies in `[P, 3P]`
      have hQ0 : 0 < Q := by linarith
      obtain ⟨y, hy0, hyQ⟩ : ∃ y : ℝ, 0 ≤ y ∧ 4 * y * Q = P - Q :=
        ⟨(P - Q) / (4 * Q), div_nonneg (by linarith) (by linarith), by field_simp⟩
      have hm1 : y ≤ ⌈y⌉₊ := Nat.le_ceil y
      have hm2 : (⌈y⌉₊ : ℝ) < y + 1 := Nat.ceil_lt_add_one hy0
      have e1 : P ≤ (4 * (⌈y⌉₊ : ℝ) + 1) * Q := by nlinarith
      have e2 : (4 * (⌈y⌉₊ : ℝ) + 3) * Q ≤ 3 * P := by nlinarith
      obtain ⟨x, hx, h1, h2⟩ := exists_odd_mem
        (show (4 * (⌈y⌉₊ : ℝ) + 1) * Q + 2 ≤ (4 * (⌈y⌉₊ : ℝ) + 3) * Q by nlinarith)
      exact ⟨x, ⌈y⌉₊, hx, by linarith, by linarith, h1, h2⟩
  · rcases le_or_gt (P + 2) (3 * Q) with ha | ha
    · -- the window `[P, 3Q]` (`m = 0`) has length `≥ 2`
      obtain ⟨x, hx, h1, h2⟩ := exists_odd_mem ha
      exact ⟨x, 0, hx, h1, by linarith, by push_cast; linarith, by push_cast; linarith⟩
    rcases le_or_gt (5 * Q + 2) (3 * P) with hb | hb
    · -- the window `[5Q, 3P]` (`m = 1`) has length `≥ 2`
      obtain ⟨x, hx, h1, h2⟩ := exists_odd_mem hb
      exact ⟨x, 1, hx, by linarith, h2, by push_cast; linarith, by push_cast; linarith⟩
    -- otherwise `Q < 2`, and one of `x = 3, 5, 9` works
    have hQ2 : Q < 2 := by linarith
    rcases le_or_gt P 3 with hP | hP
    · exact ⟨3, 0, ⟨1, by norm_num⟩, by push_cast; linarith, by push_cast; linarith,
        by push_cast; linarith, by push_cast; linarith⟩
    rcases le_or_gt 5 (3 * Q) with hQ5 | hQ5
    · exact ⟨5, 0, ⟨2, by norm_num⟩, by push_cast; linarith, by push_cast; linarith,
        by push_cast; linarith, by push_cast; linarith⟩
    · exact ⟨9, 1, ⟨4, by norm_num⟩, by push_cast; linarith, by push_cast; linarith,
        by push_cast; linarith, by push_cast; linarith⟩

/-- **The lonely runner theorem for three speeds `0 < a ≤ b ≤ c`.** With `x`, `m` from
`exists_odd_window` (for `P = c / a`, `Q = c / b`), at the time `t = x / (4c)` the fastest runner
is at distance exactly `1/4` (`x` is odd), `a t ∈ [1/4, 3/4]` and `b t ∈ [m + 1/4, m + 3/4]`. -/
lemma lonely_runner_sorted {a b c : ℝ} (ha : 0 < a) (hab : a ≤ b) (hbc : b ≤ c) :
    ∃ t : ℝ, 1 / 4 ≤ |a * t - round (a * t)| ∧ 1 / 4 ≤ |b * t - round (b * t)| ∧
      1 / 4 ≤ |c * t - round (c * t)| := by
  have hb : 0 < b := by linarith
  have hc : 0 < c := by linarith
  have hQ : 1 ≤ c / b := (one_le_div hb).2 hbc
  have hQP : c / b ≤ c / a := by
    rw [div_le_div_iff₀ hb ha]
    nlinarith
  obtain ⟨x, m, hx, h1, h2, h3, h4⟩ := exists_odd_window hQ hQP
  have hPa : a * (c / a) = c := by field_simp
  have hQb : b * (c / b) = c := by field_simp
  -- the window conditions, cleared of denominators
  have e1 : c ≤ a * x := by nlinarith
  have e2 : a * x ≤ 3 * c := by nlinarith
  have e3 : (4 * (m : ℝ) + 1) * c ≤ b * x := by nlinarith
  have e4 : b * x ≤ (4 * (m : ℝ) + 3) * c := by nlinarith
  have h4c : (0 : ℝ) < 4 * c := by positivity
  refine ⟨x / (4 * c), ?_, ?_, ?_⟩
  · rw [show a * ((x : ℝ) / (4 * c)) = a * x / (4 * c) by ring]
    refine le_abs_sub_round_of_mem 0 (by norm_num) ?_ ?_
    · rw [le_div_iff₀ h4c]; push_cast; linarith
    · rw [div_le_iff₀ h4c]; push_cast; linarith
  · rw [show b * ((x : ℝ) / (4 * c)) = b * x / (4 * c) by ring]
    refine le_abs_sub_round_of_mem m (by norm_num) ?_ ?_
    · rw [le_div_iff₀ h4c]; push_cast; linarith
    · rw [div_le_iff₀ h4c]; push_cast; linarith
  · rw [show c * ((x : ℝ) / (4 * c)) = x / 4 by field_simp]
    obtain ⟨j, rfl⟩ := hx
    rcases Int.even_or_odd j with ⟨i, rfl⟩ | ⟨i, rfl⟩
    · refine le_abs_sub_round_of_mem i (by norm_num) ?_ ?_ <;> push_cast <;> linarith
    · refine le_abs_sub_round_of_mem i (by norm_num) ?_ ?_ <;> push_cast <;> linarith

/-- **The lonely runner theorem for three speeds** (any three positive real speeds). -/
theorem lonely_runner_real {a b c : ℝ} (ha : 0 < a) (hb : 0 < b) (hc : 0 < c) :
    ∃ t : ℝ, 1 / 4 ≤ |a * t - round (a * t)| ∧ 1 / 4 ≤ |b * t - round (b * t)| ∧
      1 / 4 ≤ |c * t - round (c * t)| := by
  rcases le_total a b with h1 | h1 <;> rcases le_total b c with h2 | h2 <;>
    rcases le_total a c with h3 | h3
  · obtain ⟨t, x, y, z⟩ := lonely_runner_sorted ha h1 h2; exact ⟨t, x, y, z⟩
  · obtain ⟨t, x, y, z⟩ := lonely_runner_sorted ha h1 h2; exact ⟨t, x, y, z⟩
  · obtain ⟨t, x, z, y⟩ := lonely_runner_sorted ha h3 h2; exact ⟨t, x, y, z⟩
  · obtain ⟨t, z, x, y⟩ := lonely_runner_sorted hc h3 h1; exact ⟨t, x, y, z⟩
  · obtain ⟨t, y, x, z⟩ := lonely_runner_sorted hb h1 h3; exact ⟨t, x, y, z⟩
  · obtain ⟨t, y, z, x⟩ := lonely_runner_sorted hb h2 h3; exact ⟨t, x, y, z⟩
  · obtain ⟨t, z, y, x⟩ := lonely_runner_sorted hc h2 h1; exact ⟨t, x, y, z⟩
  · obtain ⟨t, z, y, x⟩ := lonely_runner_sorted hc h2 h1; exact ⟨t, x, y, z⟩

/-- **The lonely runner theorem for three speeds** in the form of the hypothesis `hLR` of
`liu_problem3`: for a set `D` of three positive integers some `α` has `‖d α‖ ≥ 1/4` for every
`d ∈ D`. -/
theorem lonely_runner_three (D : Finset ℤ) (hD3 : D.card = 3) (hD : ∀ d ∈ D, 0 < d) :
    ∃ α : ℝ, ∀ d ∈ D, (1 : ℝ) / 4 ≤ |(d : ℝ) * α - round ((d : ℝ) * α)| := by
  obtain ⟨a, b, c, -, -, -, rfl⟩ := Finset.card_eq_three.1 hD3
  have ha : (0 : ℝ) < a := by exact_mod_cast hD a (by simp)
  have hb : (0 : ℝ) < b := by exact_mod_cast hD b (by simp)
  have hc : (0 : ℝ) < c := by exact_mod_cast hD c (by simp)
  obtain ⟨t, h1, h2, h3⟩ := lonely_runner_real ha hb hc
  refine ⟨t, fun d hd => ?_⟩
  simp only [Finset.mem_insert, Finset.mem_singleton] at hd
  rcases hd with rfl | rfl | rfl
  · exact h1
  · exact h2
  · exact h3

/-! ### Problem 3 of Liu's survey, unconditionally -/

/-- **Problem 3 of Liu's survey, answered "no" unconditionally**: for every set `D` of three
positive integers and every `(p, q)`-colouring `c` of `G(ℤ, D)` with `0 < q ≤ p`, some `α : ℝ`
has `‖d α‖ ≥ q / p` for every `d ∈ D` (`liu_problem3` with `hLR` given by
`lonely_runner_three`). -/
theorem liu_problem3_unconditional (D : Finset ℤ) (hD3 : D.card = 3) (hD : ∀ d ∈ D, 0 < d)
    (p q : ℕ) (hq : 0 < q) (hqp : q ≤ p) (c : ℤ → ZMod p)
    (hc : ∀ x : ℤ, ∀ d ∈ D, q ≤ (c (x + d) - c x).val ∧ (c (x + d) - c x).val ≤ p - q) :
    ∃ α : ℝ, ∀ d ∈ D, (q : ℝ) / p ≤ |(d : ℝ) * α - round ((d : ℝ) * α)| :=
  liu_problem3 D hD3 hD (lonely_runner_three D hD3 hD) p q hq hqp c hc

/-- **`χ_c(G(ℤ, D)) = 1 / κ(D)` for every `D` with `|D| = 3`**: for `0 < q ≤ p`, the distance
graph `G(ℤ, D)` has a `(p, q)`-colouring if and only if some `α : ℝ` has `‖d α‖ ≥ q / p` for
every `d ∈ D`. -/
theorem liu_problem3_iff_unconditional (D : Finset ℤ) (hD3 : D.card = 3) (hD : ∀ d ∈ D, 0 < d)
    (p q : ℕ) (hq : 0 < q) (hqp : q ≤ p) :
    (∃ c : ℤ → ZMod p, ∀ x : ℤ, ∀ d ∈ D,
        q ≤ (c (x + d) - c x).val ∧ (c (x + d) - c x).val ≤ p - q) ↔
      ∃ α : ℝ, ∀ d ∈ D, (q : ℝ) / p ≤ |(d : ℝ) * α - round ((d : ℝ) * α)| :=
  liu_problem3_iff D hD3 hD (lonely_runner_three D hD3 hD) p q hq hqp

end DistLiu

#print axioms DistLiu.wplus_distance
#print axioms DistLiu.colourOf_isColouring
#print axioms DistLiu.wplus_distance_converse
#print axioms DistLiu.liu_problem3
#print axioms DistLiu.liu_problem3_iff
#print axioms DistLiu.lonely_runner_real
#print axioms DistLiu.lonely_runner_three
#print axioms DistLiu.liu_problem3_unconditional
#print axioms DistLiu.liu_problem3_iff_unconditional
