import FourColours
import PadicFour

/-!
# Four colours for every real field containing `√a` and `√b`, `a ≡ 2 (mod 3)`, `b ≡ 7 (mod 8)`

Proposition B9: if `K ⊆ ℝ` contains `√a` and `√b` with `a ≡ 2 (mod 3)` and `b ≡ 7 (mod 8)` (natural numbers),
then the unit-distance graph of `K²` is not 3-colourable.

* `no_character`: there is a finite symmetric set `U` of unit vectors of `K²` such that no character `ξ` of the
  group generated by `U` maps `U` into `[1/3, 2/3]` modulo 1.
* `not_colorable_three_of`: with Theorem W for infinite abelian groups (`FourColours.TheoremWStatement`), the
  unit-distance graph of `K²` is not 3-colourable.
* `not_colorable_three`: the same, unconditionally, with `TheoremWInf.theoremW`.
* `not_colorable_three_of_sq`: the transfer to every field `F` of characteristic 0 containing square roots of such
  `a` and `b` (for `sumSqGraph F`): `ℚ(√a, √b)` maps into `F`.
* `not_colorable_three_23`: as a check, the case `d ≡ 23 (mod 24)` of `FourColours.not_colorable_three`, with
  `a = b = d`.

*The set.* For `c ∈ ℕ` and `s ∈ K` with `s² = c`, `u_c = ((1 - c)/(1 + c), 2s/(1 + c))` and
`ū_c = ((1 - c)/(1 + c), -2s/(1 + c))`; they satisfy `(1 + c)(u_c + ū_c) = 2(1 - c) e` (`rel`), `e = (1, 0)`.
`U = G_N · {e, u_a, ū_a, u_b, ū_b}` with `N = 5^k` and `G_N` as in `FourColours` (`rotv`, `gam`, `Uset`, here over
an arbitrary `K : IntermediateField ℚ ℝ`).

*The proof.* As in `FourColours`: the character lifts to `ψ : closure U →+ ℝ` (the closure is finitely generated
and torsion-free even if `K` is infinite-dimensional over `ℚ`); for each base vector `v` the pair `(ψ v, ψ (iv))`
lies in `S_N` (`FourColours.inS`), so by `FourColours.rep_of_inS` its first coordinate is `(N/6) E_v + x_v` with
`E_v` typed (`E_v ≡ 3 (mod 6)`, or `E_v` even and prime to 3) and `|x_v| ≤ 1/4`. The two relations hold exactly
for the values of `ψ`, and for `N = 5^k`, `k = 8(a + b)`, they hold for the integers `E` (`FourColours.exact3`):
`(1 + a)(E_{u_a} + E_{ū_a}) + 2(a - 1) E_e = 0` and `(1 + b)(E_{u_b} + E_{ū_b}) + 2(b - 1) E_e = 0` (`contra`).
At 3: `3 ∣ 1 + a` and `3 ∤ 2(a - 1)`, so `3 ∣ E_e`, hence `E_e ≡ 3 (mod 6)` is odd. At 2: dividing the second
relation by 4 gives `2(β + 1)(E_{u_b} + E_{ū_b}) + (4β + 3) E_e = 0` for `b = 8β + 7`, so `E_e` is even.

*Decisions.* Only the first coordinates, and only the type of `E_e`, are used. The lemmas of `FourColours` are
imported, not copied; `rotv`, `gam`, `Uset` and their lemmas are restated for an arbitrary `K` (the originals are
stated for `QuadraticPlanes.L d`). `k = 8(a + b)` is far more than needed (`exact3` needs `8a, 8b < 5^k`).
The transfer needs no hypothesis relating `a` and `b` (such as `ab` not a square, or `a = b`): every root of the
minimal polynomial of `√c` over `ℚ` is `±s` when `s² = c`, so the minimal polynomials of `√a` and `√b` split in `F`,
and `IntermediateField.nonempty_algHom_adjoin_of_splits` gives a `ℚ`-algebra map `ℚ(√a, √b) → F` (which may send
`√b` to `-t`; that does not matter).
-/

namespace TwoRoots

open FourColours

/-! ## The arithmetic contradiction -/

/-- The arithmetic contradiction: the two relations for the first coordinates, and the type of `E_e`. -/
lemma contra {a b E₀ E₁ E₂ E₃ E₄ : ℤ} (ha : a % 3 = 2) (hb : b % 8 = 7) (h0 : typed E₀)
    (r1 : (1 + a) * E₁ + (1 + a) * E₂ + 2 * (a - 1) * E₀ = 0)
    (r2 : (1 + b) * E₃ + (1 + b) * E₄ + 2 * (b - 1) * E₀ = 0) : False := by
  obtain ⟨α, rfl⟩ : ∃ α, a = 3 * α + 2 := ⟨a / 3, by omega⟩
  obtain ⟨β, rfl⟩ : ∃ β, b = 8 * β + 7 := ⟨b / 8, by omega⟩
  have h3 : (3 : ℤ) ∣ (2 * (3 * α + 1)) * E₀ := ⟨-((α + 1) * (E₁ + E₂)), by linear_combination r1⟩
  have hE3 : (3 : ℤ) ∣ E₀ := by
    rcases Int.prime_three.dvd_or_dvd h3 with h | h
    · omega
    · exact h
  have h2 : (2 : ℤ) ∣ (4 * β + 3) * E₀ := ⟨-((β + 1) * (E₃ + E₄)), by
    apply mul_left_cancel₀ (show (4 : ℤ) ≠ 0 by norm_num)
    linear_combination r2⟩
  rcases Int.prime_two.dvd_or_dvd h2 with h | h <;> unfold typed at h0 <;> omega

/-! ## The vectors -/

section Vectors

variable (K : IntermediateField ℚ ℝ)

/-- The rotation of `v` by the Gaussian rational `(a + bi)/D`. -/
noncomputable def rotv (a b : ℤ) (D : ℕ) (v : K × K) : K × K :=
  ((a * v.1 - b * v.2) / D, (b * v.1 + a * v.2) / D)

/-- `e = (1, 0)`. -/
noncomputable def evec : K × K := (1, 0)

/-- `u_c = ((1 - c)/(1 + c), 2s/(1 + c))` for `s² = c`. -/
noncomputable def uvec (c : ℕ) (s : K) : K × K := ((1 - c) / (1 + c), 2 * s / (1 + c))

/-- `ū_c = ((1 - c)/(1 + c), -2s/(1 + c))` for `s² = c`. -/
noncomputable def ubar (c : ℕ) (s : K) : K × K := ((1 - c) / (1 + c), -2 * s / (1 + c))

/-- The five base vectors `e, u_a, ū_a, u_b, ū_b`. -/
noncomputable def V0 (a b : ℕ) (s t : K) : Fin 5 → K × K :=
  ![evec K, uvec K a s, ubar K a s, uvec K b t, ubar K b t]

/-- The set `U = G_N · {e, u_a, ū_a, u_b, ū_b}`, `N = 5^k`. -/
def Uset (a b : ℕ) (s t : K) (k : ℕ) : Set (K × K) :=
  Set.range fun x : Fin (k + 1) × Fin 8 × Fin 5 =>
    rotv K (gam x.1 x.2.1).1 (gam x.1 x.2.1).2 (5 ^ (x.1 : ℕ)) (V0 K a b s t x.2.2)

lemma unit_coe {x : K × K} (h : x.1 ^ 2 + x.2 ^ 2 = 1) : ((x.1 : ℝ)) ^ 2 + ((x.2 : ℝ)) ^ 2 = 1 := by
  have := congrArg (fun y : K => (y : ℝ)) h
  push_cast at this
  exact this

lemma rotv_unit {a b : ℤ} {D : ℕ} (hD : D ≠ 0) (hab : a ^ 2 + b ^ 2 = (D : ℤ) ^ 2) {v : K × K}
    (hv : v.1 ^ 2 + v.2 ^ 2 = 1) : (rotv K a b D v).1 ^ 2 + (rotv K a b D v).2 ^ 2 = 1 := by
  have hD' : (D : K) ≠ 0 := Nat.cast_ne_zero.2 hD
  have hab' : (a : K) ^ 2 + (b : K) ^ 2 = (D : K) ^ 2 := by exact_mod_cast hab
  simp only [rotv]
  field_simp
  linear_combination (v.1 ^ 2 + v.2 ^ 2) * hab' + (D : K) ^ 2 * hv

lemma one_add_ne_zero (c : ℕ) : (1 : K) + c ≠ 0 := by
  have : ((1 + c : ℕ) : K) ≠ 0 := Nat.cast_ne_zero.2 (by omega)
  push_cast at this
  exact this

lemma uvec_unit (c : ℕ) {s : K} (hs : s ^ 2 = c) : (uvec K c s).1 ^ 2 + (uvec K c s).2 ^ 2 = 1 := by
  have h := one_add_ne_zero K c
  simp only [uvec]
  field_simp
  linear_combination 4 * hs

lemma ubar_unit (c : ℕ) {s : K} (hs : s ^ 2 = c) : (ubar K c s).1 ^ 2 + (ubar K c s).2 ^ 2 = 1 := by
  have h := one_add_ne_zero K c
  simp only [ubar]
  field_simp
  linear_combination 4 * hs

lemma V0_unit (a b : ℕ) {s t : K} (hs : s ^ 2 = a) (ht : t ^ 2 = b) (i : Fin 5) :
    (V0 K a b s t i).1 ^ 2 + (V0 K a b s t i).2 ^ 2 = 1 := by
  fin_cases i
  · simp [V0, evec]
  · exact uvec_unit K a hs
  · exact ubar_unit K a hs
  · exact uvec_unit K b ht
  · exact ubar_unit K b ht

lemma Uset_unit (a b : ℕ) {s t : K} (hs : s ^ 2 = a) (ht : t ^ 2 = b) (k : ℕ) :
    ∀ u ∈ Uset K a b s t k, ((u.1 : ℝ)) ^ 2 + ((u.2 : ℝ)) ^ 2 = 1 := by
  rintro _ ⟨⟨j, c, i⟩, rfl⟩
  exact unit_coe K (rotv_unit K (by positivity) (gam_sq j c) (V0_unit K a b hs ht i))

lemma Uset_finite (a b : ℕ) (s t : K) (k : ℕ) : (Uset K a b s t k).Finite := Set.finite_range _

lemma neg_rotv (a b : ℤ) (D : ℕ) (v : K × K) : -rotv K a b D v = rotv K (-a) (-b) D v := by
  simp only [rotv, Prod.neg_mk, Prod.mk.injEq]; push_cast; constructor <;> ring

lemma Uset_neg (a b : ℕ) (s t : K) (k : ℕ) : ∀ u ∈ Uset K a b s t k, -u ∈ Uset K a b s t k := by
  rintro _ ⟨⟨j, c, i⟩, rfl⟩
  refine ⟨⟨j, ![4, 5, 6, 7, 0, 1, 2, 3] c, i⟩, ?_⟩
  simp only [neg_rotv]
  fin_cases c <;> simp [gam]

/-- `D (γ v) = a v + b (i v)` for `γ = (a + bi)/D`. -/
lemma rotv_smul (a b : ℤ) {D : ℕ} (hD : D ≠ 0) (v : K × K) :
    (D : ℤ) • rotv K a b D v = a • v + b • rotv K 0 1 1 v := by
  have hD' : (D : K) ≠ 0 := Nat.cast_ne_zero.2 hD
  refine Prod.ext ?_ ?_ <;> simp only [Prod.smul_fst, Prod.smul_snd, Prod.fst_add, Prod.snd_add] <;>
    simp only [rotv, zsmul_eq_mul] <;> push_cast <;> field_simp <;> ring

lemma mem_Uset (a b : ℕ) (s t : K) (k : ℕ) (j : ℕ) (hj : j ≤ k) (c : Fin 8) (i : Fin 5) :
    rotv K (gam j c).1 (gam j c).2 (5 ^ j) (V0 K a b s t i) ∈ Uset K a b s t k :=
  ⟨⟨⟨j, by omega⟩, c, i⟩, rfl⟩

lemma V0_mem (a b : ℕ) (s t : K) (k : ℕ) (i : Fin 5) : V0 K a b s t i ∈ Uset K a b s t k := by
  have := mem_Uset K a b s t k 0 (by omega) 0 i
  convert this using 1
  simp [gam, rotv]

lemma iV0_mem (a b : ℕ) (s t : K) (k : ℕ) (i : Fin 5) :
    rotv K 0 1 1 (V0 K a b s t i) ∈ Uset K a b s t k := by
  have := mem_Uset K a b s t k 0 (by omega) 1 i
  convert this using 1
  simp [gam]

/-- `(1 + c)(u_c + ū_c) + 2(c - 1) e = 0`. -/
lemma rel (c : ℕ) (s : K) :
    (1 + (c : ℤ)) • uvec K c s + (1 + (c : ℤ)) • ubar K c s + (2 * ((c : ℤ) - 1)) • evec K = 0 := by
  have h := one_add_ne_zero K c
  simp only [uvec, ubar, evec, Prod.smul_mk, Prod.mk_add_mk, zsmul_eq_mul, Prod.mk_eq_zero]
  push_cast
  constructor
  · field_simp
    ring
  · field_simp
    ring

end Vectors

/-! ## The theorems -/

theorem no_character (K : IntermediateField ℚ ℝ) (a b : ℕ) (ha : a % 3 = 2) (hb : b % 8 = 7) {s t : K}
    (hs : s ^ 2 = a) (ht : t ^ 2 = b) :
    ∃ U : Set (K × K), U.Finite ∧ (∀ u ∈ U, -u ∈ U) ∧
      (∀ u ∈ U, ((u.1 : ℝ)) ^ 2 + ((u.2 : ℝ)) ^ 2 = 1) ∧
      ∀ ξ : AddSubgroup.closure U →+ AddCircle (1 : ℝ), ∃ u, ∃ hu : u ∈ U, ∀ x : ℝ, 1 / 3 ≤ x → x ≤ 2 / 3 →
        (x : AddCircle (1 : ℝ)) ≠ ξ ⟨u, AddSubgroup.subset_closure hu⟩ := by
  set k : ℕ := 8 * (a + b) with hk
  have hk5 : (k : ℝ) < 5 ^ k := by exact_mod_cast Nat.lt_pow_self (by norm_num : 1 < 5)
  have hkR : 8 * ((a : ℝ) + b) < 5 ^ k := by rw [hk] at hk5; push_cast at hk5; exact hk5
  refine ⟨Uset K a b s t k, Uset_finite K a b s t k, Uset_neg K a b s t k, Uset_unit K a b hs ht k,
    fun ξ => ?_⟩
  by_contra hcon
  push Not at hcon
  obtain ⟨_, _⟩ := closure_finite_torsionFree (Uset K a b s t k) (Uset_finite K a b s t k)
  obtain ⟨ψ, hψ⟩ := exists_lift ξ
  have hgood : ∀ u (hu : u ∈ Uset K a b s t k), good (ψ ⟨u, AddSubgroup.subset_closure hu⟩) := by
    intro u hu
    obtain ⟨x, hx1, hx2, hx⟩ := hcon u hu
    rw [← hψ] at hx
    exact good_of_coe hx1 hx2 hx
  let w : Fin 5 → AddSubgroup.closure (Uset K a b s t k) := fun i =>
    ⟨V0 K a b s t i, AddSubgroup.subset_closure (V0_mem K a b s t k i)⟩
  let iw : Fin 5 → AddSubgroup.closure (Uset K a b s t k) := fun i =>
    ⟨rotv K 0 1 1 (V0 K a b s t i), AddSubgroup.subset_closure (iV0_mem K a b s t k i)⟩
  have hval : ∀ j (hj : j ≤ k) (c : Fin 8) (i : Fin 5),
      ψ ⟨rotv K (gam j c).1 (gam j c).2 (5 ^ j) (V0 K a b s t i),
        AddSubgroup.subset_closure (mem_Uset K a b s t k j hj c i)⟩ =
        ((gam j c).1 * ψ (w i) + (gam j c).2 * ψ (iw i)) / 5 ^ j := by
    intro j hj c i
    have h := rotv_smul K (gam j c).1 (gam j c).2 (D := 5 ^ j) (by positivity) (V0 K a b s t i)
    have h' : ((5 ^ j : ℕ) : ℤ) • (⟨rotv K (gam j c).1 (gam j c).2 (5 ^ j) (V0 K a b s t i),
        AddSubgroup.subset_closure (mem_Uset K a b s t k j hj c i)⟩ : AddSubgroup.closure (Uset K a b s t k)) =
        (gam j c).1 • w i + (gam j c).2 • iw i := Subtype.ext (by simpa [w, iw] using h)
    have h'' := congrArg ψ h'
    simp only [map_zsmul, map_add, zsmul_eq_mul] at h''
    push_cast at h''
    rw [eq_div_iff (by positivity)]
    linear_combination h''
  have hS : ∀ i, inS k (ψ (w i)) (ψ (iw i)) := by
    intro i j hj
    have g0 := hgood _ (mem_Uset K a b s t k j hj 0 i)
    have g1 := hgood _ (mem_Uset K a b s t k j hj 1 i)
    have g2 := hgood _ (mem_Uset K a b s t k j hj 2 i)
    have g3 := hgood _ (mem_Uset K a b s t k j hj 3 i)
    rw [hval j hj] at g0 g1 g2 g3
    refine ⟨good_congr g0 ?_, good_congr g1 ?_, good_congr g2 ?_, good_congr g3 ?_⟩ <;>
      simp [gam] <;> ring
  -- the two relations
  have hr1 : ((1 + (a : ℤ) : ℤ) : ℝ) * ψ (w 1) + ((1 + (a : ℤ) : ℤ) : ℝ) * ψ (w 2) +
      ((2 * ((a : ℤ) - 1) : ℤ) : ℝ) * ψ (w 0) = 0 := by
    have h : (1 + (a : ℤ)) • w 1 + (1 + (a : ℤ)) • w 2 + (2 * ((a : ℤ) - 1)) • w 0 = 0 :=
      Subtype.ext (by simpa [w, V0] using rel K a s)
    have := congrArg ψ h
    simp only [map_add, map_zsmul, zsmul_eq_mul, map_zero] at this
    exact this
  have hr2 : ((1 + (b : ℤ) : ℤ) : ℝ) * ψ (w 3) + ((1 + (b : ℤ) : ℤ) : ℝ) * ψ (w 4) +
      ((2 * ((b : ℤ) - 1) : ℤ) : ℝ) * ψ (w 0) = 0 := by
    have h : (1 + (b : ℤ)) • w 3 + (1 + (b : ℤ)) • w 4 + (2 * ((b : ℤ) - 1)) • w 0 = 0 :=
      Subtype.ext (by simpa [w, V0] using rel K b t)
    have := congrArg ψ h
    simp only [map_add, map_zsmul, zsmul_eq_mul, map_zero] at this
    exact this
  -- the types
  obtain ⟨E₀, x₀, h₀, hx₀, t₀⟩ := rep_fst (rep_of_inS k (hS 0))
  obtain ⟨E₁, x₁, h₁, hx₁, -⟩ := rep_fst (rep_of_inS k (hS 1))
  obtain ⟨E₂, x₂, h₂, hx₂, -⟩ := rep_fst (rep_of_inS k (hS 2))
  obtain ⟨E₃, x₃, h₃, hx₃, -⟩ := rep_fst (rep_of_inS k (hS 3))
  obtain ⟨E₄, x₄, h₄, hx₄, -⟩ := rep_fst (rep_of_inS k (hS 4))
  rw [h₀, h₁, h₂] at hr1
  rw [h₀, h₃, h₄] at hr2
  have ha1 : (1 : ℝ) ≤ a := by exact_mod_cast (show 1 ≤ a by omega)
  have hb1 : (1 : ℝ) ≤ b := by exact_mod_cast (show 1 ≤ b by omega)
  have e1 := exact3 hx₁ hx₂ hx₀ (by
    push_cast
    rw [abs_of_nonneg (by linarith), abs_of_nonneg (by linarith)]
    linarith) hr1
  have e2 := exact3 hx₃ hx₄ hx₀ (by
    push_cast
    rw [abs_of_nonneg (by linarith), abs_of_nonneg (by linarith)]
    linarith) hr2
  exact contra (a := a) (b := b) (by omega) (by omega) t₀ e1 e2

theorem not_colorable_three_of (hW : TheoremWStatement) (K : IntermediateField ℚ ℝ) (a b : ℕ)
    (ha : a % 3 = 2) (hb : b % 8 = 7) (hsa : Real.sqrt a ∈ K) (hsb : Real.sqrt b ∈ K) :
    ¬ (LocalColouring.unitDistGraph K).Colorable 3 := by
  rintro ⟨C⟩
  have hs : (⟨Real.sqrt a, hsa⟩ : K) ^ 2 = a :=
    Subtype.ext (by push_cast; exact Real.sq_sqrt (Nat.cast_nonneg _))
  have ht : (⟨Real.sqrt b, hsb⟩ : K) ^ 2 = b :=
    Subtype.ext (by push_cast; exact Real.sq_sqrt (Nat.cast_nonneg _))
  obtain ⟨U, hUf, hUs, hUu, hU⟩ := no_character K a b ha hb hs ht
  let c : K × K → ZMod 3 := fun p => ((C p : ℕ) : ZMod 3)
  have hc : ∀ g, ∀ s ∈ U, c (g + s) ≠ c g := by
    intro g s hs h
    have hadj : (LocalColouring.unitDistGraph K).Adj (g + s) g := by
      show (((g + s).1 : ℝ) - g.1) ^ 2 + (((g + s).2 : ℝ) - g.2) ^ 2 = 1
      simpa using hUu s hs
    apply C.valid hadj
    have h' := (ZMod.natCast_eq_natCast_iff' _ _ _).1 h
    exact Fin.ext (by have := (C (g + s)).isLt; have := (C g).isLt; omega)
  obtain ⟨ξ, hξ⟩ := hW U hUf hUs c hc
  obtain ⟨u, hu, hne⟩ := hU ξ
  obtain ⟨x, hx1, hx2, hx⟩ := hξ u hu
  exact hne x hx1 hx2 hx

/-- Proposition B9: `χ(K²) ≥ 4` for every real field `K` containing `√a` and `√b`, `a ≡ 2 (mod 3)`,
`b ≡ 7 (mod 8)`. -/
theorem not_colorable_three (K : IntermediateField ℚ ℝ) (a b : ℕ) (ha : a % 3 = 2) (hb : b % 8 = 7)
    (hsa : Real.sqrt a ∈ K) (hsb : Real.sqrt b ∈ K) :
    ¬ (LocalColouring.unitDistGraph K).Colorable 3 :=
  not_colorable_three_of theoremWStatement_holds K a b ha hb hsa hsb

/-! ## The transfer to fields of characteristic 0, and the case `d ≡ 23 (mod 24)` -/

section Transfer

open Polynomial QuadraticPlanes

/-- The minimal polynomial over `ℚ` of `√c` splits in every field containing a square root of `c`. -/
lemma integral_splits {F : Type*} [Field F] [CharZero F] (c : ℕ) {s : F} (hs : s ^ 2 = c) :
    IsIntegral ℚ √(c : ℝ) ∧ ((minpoly ℚ √(c : ℝ)).map (algebraMap ℚ F)).Splits := by
  refine ⟨PadicFour.isIntegral_sqrt c, ?_⟩
  have hdvd : minpoly ℚ √(c : ℝ) ∣ X ^ 2 - C (c : ℚ) :=
    minpoly.dvd ℚ _ (by simp [Real.sq_sqrt (Nat.cast_nonneg c)])
  have hfac : (X ^ 2 - C (c : ℚ)).map (algebraMap ℚ F) = (X - C s) * (X - C (-s)) := by
    simp only [Polynomial.map_sub, Polynomial.map_pow, map_X, map_C, eq_ratCast, Rat.cast_natCast, C_neg,
      sub_neg_eq_add]
    rw [← hs, C_pow]
    ring
  refine Splits.of_dvd ?_ ?_ (Polynomial.map_dvd _ hdvd)
  · rw [hfac]; exact (Splits.X_sub_C _).mul (Splits.X_sub_C _)
  · rw [hfac]
    exact mul_ne_zero (X_sub_C_ne_zero _) (X_sub_C_ne_zero _)

/-- A ring map `K → F` maps the unit-distance graph of `K²` to `sumSqGraph F`. -/
def hom {F : Type*} [Field F] {K : IntermediateField ℚ ℝ} (φ : K →+* F) :
    LocalColouring.unitDistGraph K →g sumSqGraph F where
  toFun x := (φ x.1, φ x.2)
  map_rel' {x y} h := by
    have h : ((x.1 : ℝ) - y.1) ^ 2 + ((x.2 : ℝ) - y.2) ^ 2 = 1 := h
    have h' : (x.1 - y.1) ^ 2 + (x.2 - y.2) ^ 2 = (1 : K) := by
      apply Subtype.ext
      push_cast
      exact h
    show (φ x.1 - φ y.1) ^ 2 + (φ x.2 - φ y.2) ^ 2 = 1
    simpa using congrArg φ h'

/-- The transfer: `χ(F²) ≥ 4` for every field `F` of characteristic 0 containing square roots of `a ≡ 2 (mod 3)`
and of `b ≡ 7 (mod 8)`. -/
theorem not_colorable_three_of_sq {F : Type*} [Field F] [CharZero F] {a b : ℕ} (ha : a % 3 = 2)
    (hb : b % 8 = 7) {s t : F} (hs : s ^ 2 = a) (ht : t ^ 2 = b) : ¬ (sumSqGraph F).Colorable 3 := by
  rintro ⟨C⟩
  let K := IntermediateField.adjoin ℚ ({√(a : ℝ), √(b : ℝ)} : Set ℝ)
  obtain ⟨φ⟩ := IntermediateField.nonempty_algHom_adjoin_of_splits (K := F) (S := ({√(a : ℝ), √(b : ℝ)} : Set ℝ))
    (by
      rintro x (rfl | rfl)
      · exact integral_splits a hs
      · exact integral_splits b ht)
  exact not_colorable_three K a b ha hb (IntermediateField.subset_adjoin ℚ _ (by simp))
    (IntermediateField.subset_adjoin ℚ _ (by simp)) ⟨C.comp (hom φ.toRingHom)⟩

/-- Check of the API: the case `d ≡ 23 (mod 24)` of `FourColours.not_colorable_three`, with `a = b = d`. -/
theorem not_colorable_three_23 (d : ℕ) (hd : d % 24 = 23) : ¬ (LocalColouring.unitDistGraph (L d)).Colorable 3 :=
  not_colorable_three (L d) d d (by omega) (by omega) (sqrt_mem d) (sqrt_mem d)

end Transfer

end TwoRoots
