"""Exact computation of S_N^(r) = {c in C : Re(conj(c) g) in [r, 1-r] + Z for all g in G_N}, N = 5^k.

All arithmetic is exact (fractions.Fraction).  A point c = x + iy is a pair (x, y).
For |j| <= k let rho^j = A + iB.  The conditions for g = e*rho^j (e a unit) are equivalent to
    f_{j,1}(c) = Re(conj(c) rho^j) = A x + B y  in [r, 1-r] + Z,
    f_{j,2}(c) = Im(conj(c) rho^j) = B x - A y  in [r, 1-r] + Z.
For 0 < r the set {f in [r,1-r]+Z} is a disjoint union of closed strips at mutual distance 2r > 0, so every connected
component of S_N^(r) is the intersection of one strip of each of the 2(2k+1) families: a closed convex polygon
(possibly a segment or a point).  Components never merge when r decreases; each has a 'kappa', the largest r' with
which it still meets S_N^(r'), namely the optimum of a small LP (computed exactly here).

Two independent enumerations are implemented:
  * lift_components(k, r): level by level, S_{5^k} = S_{5^{k-1}} (periodic mod 5^{k-1}) cut by the conditions at
    j = +-k; each component at level k-1 is translated by 5^{k-1}(a+bi), a,b in 0..4, and clipped;
  * direct_components(k, r, sym): every unit square [n+r,n+1-r] x [m+r,m+1-r] (n, m mod N) clipped by all strip
    families; with sym=True only the squares 0 <= m <= n <= (N-1)/2 (a fundamental domain of the dihedral symmetry
    group generated by c -> ic, c -> conj(c), c -> -c acting on the squares mod N), each weighted by its orbit size.
"""
from fractions import Fraction as F
from itertools import combinations
import math

ONE = F(1)


def cmul(a, b):
    return (a[0] * b[0] - a[1] * b[1], a[0] * b[1] + a[1] * b[0])


def conj(a):
    return (a[0], -a[1])


RHO = (F(3, 5), F(4, 5))


def rho_pow(j):
    r = RHO if j >= 0 else conj(RHO)
    z = (F(1), F(0))
    for _ in range(abs(j)):
        z = cmul(z, r)
    return z


def functionals(k):
    """list of (j, coord, (a, b)) with f(c) = a x + b y"""
    out = []
    for j in range(-k, k + 1):
        A, B = rho_pow(j)
        out.append((j, 1, (A, B)))
        out.append((j, 2, (B, -A)))
    return out


def floor(q):
    return q.numerator // q.denominator


# ---------------------------------------------------------------- convex polygon clipping (exact)
def clip(poly, a, b, c, sense):
    """keep the part of the convex polygon with sense*(a x + b y - c) >= 0"""
    out = []
    n = len(poly)
    vals = [sense * (a * p[0] + b * p[1] - c) for p in poly]
    for i in range(n):
        P, Q = poly[i], poly[(i + 1) % n]
        fp, fq = vals[i], vals[(i + 1) % n]
        if fp >= 0:
            out.append(P)
        if (fp > 0 and fq < 0) or (fp < 0 and fq > 0):
            t = fp / (fp - fq)
            out.append((P[0] + t * (Q[0] - P[0]), P[1] + t * (Q[1] - P[1])))
    res = []
    for p in out:
        if not res or res[-1] != p:
            res.append(p)
    while len(res) > 1 and res[0] == res[-1]:
        res.pop()
    return res


def strip_split(poly, a, b, lo, hi):
    """split the convex polygon by the periodic strips {a x + b y in [lo, hi] + Z}; returns list of (n, piece)"""
    vals = [a * p[0] + b * p[1] for p in poly]
    vmin, vmax = min(vals), max(vals)
    out = []
    for n in range(floor(vmin - hi), floor(vmax - lo) + 1):
        if n + hi < vmin or n + lo > vmax:
            continue
        q = clip(poly, a, b, n + lo, +1)
        if q:
            q = clip(q, a, b, n + hi, -1)
        if q:
            out.append((n, q))
    return out


def area(poly):
    if len(poly) < 3:
        return F(0)
    s = F(0)
    for i in range(len(poly)):
        x1, y1 = poly[i]
        x2, y2 = poly[(i + 1) % len(poly)]
        s += x1 * y2 - x2 * y1
    return abs(s) / 2


def centroid_pt(poly):
    """a point of the polygon: the average of its vertices (exact)"""
    n = len(poly)
    return (sum(p[0] for p in poly) / n, sum(p[1] for p in poly) / n)


# ---------------------------------------------------------------- enumerations
def lift_components(k, r, verbose=False):
    """components of S_{5^k}^(r) in C / 5^k Z[i], by lifting level by level.  Returns list of polygons."""
    lo, hi = r, 1 - r
    comps = [[(lo, lo), (hi, lo), (hi, hi), (lo, hi)]]          # level 0: the square [r,1-r]^2 mod Z[i]
    for kk in range(1, k + 1):
        Np = 5 ** (kk - 1)
        fams = []
        for j in (kk, -kk):
            A, B = rho_pow(j)
            fams.append((A, B))
            fams.append((B, -A))
        new = []
        for C in comps:
            for a in range(5):
                for b in range(5):
                    pieces = [[(p[0] + Np * a, p[1] + Np * b) for p in C]]
                    for (fa, fb) in fams:
                        nxt = []
                        for P in pieces:
                            nxt.extend(q for _, q in strip_split(P, fa, fb, lo, hi))
                        pieces = nxt
                        if not pieces:
                            break
                    new.extend(pieces)
        comps = new
        if verbose:
            print(f"  level {kk}: {len(comps)} components")
    return comps


def square_orbit(n, m, N):
    s = set()
    for (u, v) in ((n, m), (m, n)):
        for uu in (u, N - 1 - u):
            for vv in (v, N - 1 - v):
                s.add((uu, vv))
    return s


def direct_components(k, r, sym=True):
    """components of S_N^(r) from the unit squares; returns list of (polygon, weight)."""
    N = 5 ** k
    lo, hi = r, 1 - r
    fams = []
    for j in range(1, k + 1):
        for jj in (j, -j):
            A, B = rho_pow(jj)
            fams.append((A, B))
            fams.append((B, -A))
    out = []
    if sym:
        reps = [(n, m) for n in range((N - 1) // 2 + 1) for m in range(n + 1)]
    else:
        reps = [(n, m) for n in range(N) for m in range(N)]
    for (n, m) in reps:
        w = len(square_orbit(n, m, N)) if sym else 1
        pieces = [[(n + lo, m + lo), (n + hi, m + lo), (n + hi, m + hi), (n + lo, m + hi)]]
        for (fa, fb) in fams:
            nxt = []
            for P in pieces:
                nxt.extend(q for _, q in strip_split(P, fa, fb, lo, hi))
            pieces = nxt
            if not pieces:
                break
        for P in pieces:
            out.append((P, w))
    return out


# ---------------------------------------------------------------- invariants of a component
def strip_indices(pt, k):
    """for a point of a component: the integers n_f with f(pt) in [n_f + r, n_f + 1 - r]"""
    return [(fa, fb, floor(fa * pt[0] + fb * pt[1])) for (_, _, (fa, fb)) in functionals(k)]


def solve3(M, v):
    """exact 3x3 solve, None if singular"""
    (a, b, c), (d, e, f), (g, h, i) = M
    det = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
    if det == 0:
        return None
    x = (v[0] * (e * i - f * h) - b * (v[1] * i - f * v[2]) + c * (v[1] * h - e * v[2])) / det
    y = (a * (v[1] * i - f * v[2]) - v[0] * (d * i - f * g) + c * (d * v[2] - v[1] * g)) / det
    z = (a * (e * v[2] - v[1] * h) - b * (d * v[2] - v[1] * g) + v[0] * (d * h - e * g)) / det
    return (x, y, z)


def kappa_lp(cons):
    """maximise t subject to t <= a x + b y + c for (a, b, c) in cons.  Exact (vertex enumeration with a float
    pre-filter, then exact dual check).  Returns (t*, (x*, y*))."""
    # rows: -a x - b y + t <= c
    rows = [(-a, -b, ONE, c) for (a, b, c) in cons]
    fr = [(float(a), float(b), float(c)) for (a, b, c) in cons]
    best = None
    cand = []
    n = len(rows)
    for i1, i2, i3 in combinations(range(n), 3):
        M = [rows[i][:3] for i in (i1, i2, i3)]
        # float solve
        Mf = [[float(z) for z in row] for row in M]
        vf = [float(rows[i][3]) for i in (i1, i2, i3)]
        det = (Mf[0][0] * (Mf[1][1] * Mf[2][2] - Mf[1][2] * Mf[2][1]) - Mf[0][1] * (Mf[1][0] * Mf[2][2] - Mf[1][2] * Mf[2][0])
               + Mf[0][2] * (Mf[1][0] * Mf[2][1] - Mf[1][1] * Mf[2][0]))
        if abs(det) < 1e-12:
            continue
        import numpy as _np
        sol = _np.linalg.solve(_np.array(Mf), _np.array(vf))
        x, y, t = sol
        if any(t > a * x + b * y + c + 1e-9 for (a, b, c) in fr):
            continue
        cand.append((t, (i1, i2, i3)))
    cand.sort(reverse=True)
    # exact: take the best float candidates and verify exactly; the exact optimum is the max over exact-feasible
    # vertices; we check all candidates within 1e-7 of the float max
    if not cand:
        raise RuntimeError("no vertex")
    tmax = cand[0][0]
    for tf, tri in cand:
        if tf < tmax - 1e-7:
            break
        M = [rows[i][:3] for i in tri]
        v = [rows[i][3] for i in tri]
        s = solve3(M, v)
        if s is None:
            continue
        x, y, t = s
        if all(t <= a * x + b * y + c for (a, b, c) in cons):
            if best is None or t > best[0]:
                best = (t, (x, y), tri)
    # exact optimality certificate: dual multipliers for the best vertex, y >= 0 with sum y_i * row_i[:3] = (0,0,1)
    t, (x, y), tri = best
    M = [rows[i][:3] for i in tri]
    MT = [[M[0][c], M[1][c], M[2][c]] for c in range(3)]
    dual = solve3(MT, (F(0), F(0), ONE))
    if dual is None or any(d < 0 for d in dual):
        # degenerate vertex: fall back to full exact enumeration
        best2 = None
        for i1, i2, i3 in combinations(range(n), 3):
            M = [rows[i][:3] for i in (i1, i2, i3)]
            v = [rows[i][3] for i in (i1, i2, i3)]
            s = solve3(M, v)
            if s is None:
                continue
            xx, yy, tt = s
            if all(tt <= a * xx + b * yy + c for (a, b, c) in cons):
                if best2 is None or tt > best2[0]:
                    best2 = (tt, (xx, yy), (i1, i2, i3))
        return best2[0], best2[1], "enum"
    return t, (x, y), "dual"


def component_kappa(poly, k):
    """kappa of the component containing the polygon poly (exact) and an optimal point"""
    pt = centroid_pt(poly)
    cons = []
    for (fa, fb, nf) in strip_indices(pt, k):
        # t <= f - nf  and  t <= nf + 1 - f
        cons.append((fa, fb, F(-nf)))
        cons.append((-fa, -fb, F(nf + 1)))
    return kappa_lp(cons)


def kappa_point(pt, k):
    """min over G_N of ||Re(conj(c) g)|| at a point (exact)"""
    best = F(1, 2)
    for (_, _, (fa, fb)) in functionals(k):
        v = fa * pt[0] + fb * pt[1]
        fr = v - floor(v)
        best = min(best, fr, 1 - fr)
    return best


def values(pt, k):
    """the values (Re, Im)(conj(c) rho^j) mod 1, j = -k..k"""
    out = {}
    for j in range(-k, k + 1):
        A, B = rho_pow(j)
        u = A * pt[0] + B * pt[1]
        v = B * pt[0] - A * pt[1]
        out[j] = (u - floor(u), v - floor(v))
    return out


# ---------------------------------------------------------------- type points
def type_points(k):
    N = 5 ** k
    cst = [(F(N, 2), F(N, 2))]
    qs = [(F(N * a, 3), F(N * b, 3)) for a in (1, 2) for b in (1, 2)]
    return cst, qs


def torus_d2(p, q, N):
    """squared distance in C / N Z[i] (exact)"""
    dx = p[0] - q[0]
    dy = p[1] - q[1]
    dx = dx - N * floor(dx / N + F(1, 2))
    dy = dy - N * floor(dy / N + F(1, 2))
    return dx * dx + dy * dy


def classify(poly, k):
    """(type, name of nearest type point, max distance^2 of the polygon from it, min distance^2)"""
    N = 5 ** k
    cst, qs = type_points(k)
    pt = centroid_pt(poly)
    best = None
    for name, P in [("c", cst[0])] + [(f"q{i}", q) for i, q in enumerate(qs)]:
        d = torus_d2(pt, P, N)
        if best is None or d < best[0]:
            best = (d, name, P)
    _, name, P = best
    dmax = max(torus_d2(v, P, N) for v in poly)
    dmin_v = min(torus_d2(v, P, N) for v in poly)
    return name, P, dmax, dmin_v


# ---------------------------------------------------------------- faster exact LP (float LP + exact certificate)
def kappa_lp_fast(cons):
    """maximise t s.t. t <= a x + b y + c for (a,b,c) in cons.  A float LP (scipy HiGHS) suggests the active set;
    the answer is returned only with an exact certificate: an exactly feasible vertex (x, y, t) and exact
    nonnegative dual multipliers on three of its active constraints with sum y_i (-a_i, -b_i, 1) = (0, 0, 1)
    (so t is optimal by weak duality).  Falls back to exact vertex enumeration."""
    import numpy as np
    from scipy.optimize import linprog
    A = np.array([[-float(a), -float(b), 1.0] for (a, b, c) in cons])
    bvec = np.array([float(c) for (a, b, c) in cons])
    res = linprog(c=[0, 0, -1], A_ub=A, b_ub=bvec, bounds=[(None, None)] * 3, method="highs")
    if res.status == 0:
        x, y, t = res.x
        slack = bvec - A @ res.x
        order = [i for i in np.argsort(slack) if slack[i] < 1e-7][:9]
        rows = [(-a, -b, ONE, c) for (a, b, c) in cons]
        for tri in combinations(order, 3):
            M = [rows[i][:3] for i in tri]
            v = [rows[i][3] for i in tri]
            s = solve3(M, v)
            if s is None:
                continue
            xx, yy, tt = s
            if not all(tt <= a * xx + b * yy + c for (a, b, c) in cons):
                continue
            MT = [[M[0][cc], M[1][cc], M[2][cc]] for cc in range(3)]
            dual = solve3(MT, (F(0), F(0), ONE))
            if dual is None or any(d < 0 for d in dual):
                continue
            return tt, (xx, yy), "cert"
    t, xy, how = kappa_lp(cons)
    return t, xy, how


def component_kappa_fast(poly, k, r=None):
    pt = centroid_pt(poly)
    cons = []
    for (fa, fb, nf) in strip_indices(pt, k):
        cons.append((fa, fb, F(-nf)))
        cons.append((-fa, -fb, F(nf + 1)))
    return kappa_lp_fast(cons)


# ---------------------------------------------------------------- canonical forms and symmetry orbits
def cross(o, a, b):
    return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])


def clean(poly):
    """strictly convex vertex list (convex hull of the points; duplicates and collinear points removed)"""
    pts = sorted(set(poly))
    if len(pts) <= 1:
        return pts
    lower, upper = [], []
    for p in pts:
        while len(lower) >= 2 and cross(lower[-2], lower[-1], p) <= 0:
            lower.pop()
        lower.append(p)
    for p in reversed(pts):
        while len(upper) >= 2 and cross(upper[-2], upper[-1], p) <= 0:
            upper.pop()
        upper.append(p)
    hull = lower[:-1] + upper[:-1]
    return hull if hull else pts[:1]


SYMS = [lambda c: c, lambda c: (-c[1], c[0]), lambda c: (-c[0], -c[1]), lambda c: (c[1], -c[0]),
        lambda c: (c[0], -c[1]), lambda c: (c[1], c[0]), lambda c: (-c[0], c[1]), lambda c: (-c[1], -c[0])]


def modN(p, N):
    return (p[0] - N * floor(p[0] / N), p[1] - N * floor(p[1] / N))


def canon_point(p, N):
    return modN(p, N)


def orbit_key(poly, N):
    P = clean(poly)
    c = centroid_pt(P)
    return min(modN(g(c), N) for g in SYMS)


def component_kappa_shifted(poly, k):
    """as component_kappa_fast, but in coordinates centred at a point of the component (better conditioned float LP;
    the certificate is exact in the shifted coordinates, which is equivalent)."""
    pt = centroid_pt(poly)
    cons = []
    for (fa, fb, nf) in strip_indices(pt, k):
        base = fa * pt[0] + fb * pt[1] - nf          # value at pt minus n_f, in [r, 1-r]
        cons.append((fa, fb, base))                   # t <= f(pt + d) - n_f = fa d1 + fb d2 + base
        cons.append((-fa, -fb, 1 - base))             # t <= n_f + 1 - f(pt + d)
    t, d, how = kappa_lp_fast(cons)
    return t, (pt[0] + d[0], pt[1] + d[1]), how
